
import { ClassData } from '../../types';
import { f, sc } from '../dataHelpers';

const ARTIFICER_BASE = [
    f('magical_tinkering', 
      'Magical Tinkering', 
      'Магический мастеровой', 
      'At 1st level, you learn how to invest a spark of magic into mundane objects. To use this ability, you must have thieves\' tools or artisan\'s tools in hand. You then touch a Tiny nonmagical object as an action and give it one of the following magical properties of your choice:\n\n• The object sheds bright light in a 5-foot radius and dim light for an additional 5 feet.\n• Whenever tapped by a creature, the object emits a recorded message that can be heard up to 10 feet away. You utter the message when you bestow this property on the object, and the recording can be no more than 6 seconds long.\n• The object continuously emits your choice of an odor or a nonverbal sound (wind, waves, chirping, or the like). The chosen phenomenon is perceivable up to 10 feet away.\n• A static visual effect appears on one of the object\'s surfaces. This effect can be a picture, up to 25 words of text, lines and shapes, or a mixture of these elements, as you like.\n\nThe chosen property lasts indefinitely. As an action, you can touch the object and end the property early.\n\nYou can bestow magic on multiple objects, touching one object each time you use this feature, though a single object can only bear one property at a time. The maximum number of objects you can affect with this feature at one time is equal to your Intelligence modifier (minimum of one object). If you try to exceed your maximum, the oldest property immediately ends, and then the new property applies.', 
      'Вы научились вкладывать искру магии в обычные предметы. Чтобы использовать это умение, вы должны держать в руках воровские инструменты или инструменты ремесленника. Затем действием вы касаетесь Крошечного немагического объекта и наделяете его одним из следующих магических свойств на ваш выбор:\n\n• Зачарованный объект излучает яркий свет в радиусе 5 футов и тусклый свет в радиусе еще 5 футов.\n• Объект проигрывает записанное сообщение, которое можно услышать в пределах 10 футов каждый раз, когда до него дотрагивается существо. Вы произносите это сообщение, когда наделяете объект данным свойством, а сама запись не может быть длиннее 6 секунд.\n• Объект непрерывно испускает запах или издаёт звук на ваш выбор (ветер, волны, стрекотание и прочее). Выбранное явление можно ощутить на расстоянии 10 футов.\n• Статичный визуальный эффект появляется на одной из поверхностей объекта. Этот эффект может быть изображением, текстом до 25 слов, линиями и формами или совмещением этих элементов по вашему выбору.\n\nВыбранное свойство навсегда остается присущим объекту. Действием вы можете коснуться объекта и лишить его этого свойства.\n\nТаким образом можно наделить магическими свойствами несколько предметов, касаясь одного предмета каждый раз, когда вы используете это умение, но не больше, чем одно свойство на один предмет. Максимальное количество объектов, которые вы можете наделить магическими свойствами этим умением одновременно, равно вашему модификатору Интеллекта (минимум один объект). Если вы пытаетесь превысить свой максимум, самое старое свойство немедленно заканчивается, а затем начинает действовать новое свойство.', 
      1),
    
    f('spellcasting_artificer', 
      'Spellcasting', 
      'Использование заклинаний', 
      'You have studied the workings of magic and how to cast spells, channeling the magic through objects. To cast a spell, you must have a spellcasting focus (thieves\' tools or artisan\'s tools) in hand. You must be proficient with the tool to use it in this way.\n\n**Cantrips.** You know two cantrips of your choice from the artificer spell list. You learn additional artificer cantrips of your choice at higher levels.\n\n**Spell Slots.** The Artificer table shows how many spell slots you have to cast your artificer spells. To cast one of these spells, you must expend a slot of the spell\'s level or higher. You regain all expended spell slots when you finish a long rest.\n\n**Preparing Spells.** You prepare the list of artificer spells that are available for you to cast, choosing from the artificer spell list. When you do so, choose a number of artificer spells equal to your Intelligence modifier + half your artificer level, rounded down (minimum of one spell). The spells must be of a level for which you have spell slots.\n\n**Spellcasting Ability.** Intelligence is your spellcasting ability for your artificer spells. You use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for an artificer spell you cast and when making an attack roll with one.\n\n**Ritual Casting.** You can cast an artificer spell as a ritual if that spell has the ritual tag and you have the spell prepared.', 
      'Вы изучили то, как работает магия, и то, как накладывать заклинания, направляя её через предметы.\n\n**Необходимый инструмент.** Вы создаёте эффекты ваших заклинаний изобретателя с помощью ваших инструментов. При накладывании любого заклинания с помощью умения «Использование заклинаний» вы должны держать в руках воровские инструменты или любые из инструментов ремесленника в качестве магической фокусировки. Вы должны иметь владение инструментом, чтобы использовать его таким образом.\n\n**Заговоры.** Вы знаете два заговора на ваш выбор из списка заклинаний изобретателя. Вы узнаёте дополнительные заговоры изобретателя на более высоких уровнях.\n\n**Ячейки заклинаний.** Таблица «Изобретатель» показывает, сколько у вас ячеек. Вы восстанавливаете все потраченные ячейки заклинаний, когда заканчиваете продолжительный отдых.\n\n**Подготовка заклинаний.** Вы подготавливаете список заклинаний. Выберите количество заклинаний, равное модификатору Интеллекта + половине вашего уровня изобретателя, округлённому в меньшую сторону (минимум одно). Уровень заклинаний не должен превышать уровень самой высокой имеющейся у вас ячейки заклинаний.\n\n**Базовая характеристика заклинаний.** Интеллект является базовой характеристикой для ваших заклинаний изобретателя. Вы используете Интеллект в случаях, когда заклинание ссылается на базовую характеристику. Кроме того, вы используете модификатор Интеллекта при определении Сл спасбросков ваших заклинаний изобретателя и при броске атаки заклинаниями.\n\n**Ритуальное колдовство.** Вы можете сотворить заклинание изобретателя как ритуал, если в его описании присутствует слово «ритуал» и оно вами подготовлено.', 
      1),
    
    f('infuse_item', 
      'Infuse Item', 
      'Инфузирование предмета', 
      'At 2nd level, you gain the ability to imbue mundane items with certain magical infusions, turning those items into magic items.\n\n**Infusions Known.** When you gain this feature, pick four artificer infusions to learn. You learn more infusions of your choice when you reach certain levels in this class.\n\n**Infusing an Item.** Whenever you finish a long rest, you can touch a nonmagical object and imbue it with one of your artificer infusions, turning it into a magic item. An infusion works on only certain kinds of objects, as specified in the infusion\'s description. Your infusion remains in an item indefinitely, but when you die, the infusion vanishes after a number of days equal to your Intelligence modifier (minimum of 1 day). The infusion also vanishes if you replace your knowledge of the infusion.\n\nYou can infuse more than one nonmagical object at the end of a long rest; the maximum number of objects appears in the Infused Items column of the Artificer table. You must touch each of the objects, and each of your infusions can be in no more than one object at a time. If you try to exceed your maximum number of infusions, the oldest infusion ends, and then the new infusion applies.', 
      'Вы получаете способность вливать в обычные предметы определённую магию и превращать их в магические.\n\n**Известные инфузии.** Получив это умение, выберите четыре инфузии из раздела Инфузии изобретателя. При достижении определённых уровней вы изучаете дополнительные инфузии на ваш выбор.\n\n**Насыщение предмета магией.** Заканчивая продолжительный отдых, вы можете дотронуться до немагического объекта и с помощью инфузии сделать его магическим предметом. Инфузия действует только на те виды предметов, которые указаны в её описании. Ваша инфузия остаётся в предмете бесконечно долго, но если вы умираете, она исчезает через количество дней, равное вашему модификатору Интеллекта (минимум 1 день). Исчезает она также, если вы отказываетесь от знания этой инфузии, чтобы изучить другую.\n\nЗаканчивая продолжительный отдых, вы можете наполнить магией более одного немагического объекта. Максимальное их количество отображено в столбце «Инфузии предметов» таблицы «Изобретатель». Вы должны касаться предмета, и каждая из ваших инфузий может быть применена только к одному объекту единовременно. Если вы попытаетесь превысить максимальное количество инфузий, самая старая из них немедленно заканчивается, а затем применяется новая.', 
      2),
    
    f('artificer_specialist', 
      'Artificer Specialist', 
      'Специальность изобретателя', 
      'At 3rd level, you choose the type of specialist you are. Your choice grants you features at 5th, 9th, and 15th level.', 
      'На 3-м уровне вы выбираете свою специальность. Ваш выбор предоставляет вам умения на 3-м, 5-м, 9-м и 15-м уровнях.', 
      3),
    
    f('right_tool', 
      'The Right Tool for the Job', 
      'Подходящий инструмент', 
      'At 3rd level, you learn how to produce exactly the tool you need: with thieves\' tools or artisan\'s tools in hand, you can magically create one set of artisan\'s tools in an unoccupied space within 5 feet of you. This creation requires 1 hour of uninterrupted work, which can coincide with a short or long rest. Though the product of magic, the tools are nonmagical, and they vanish when you use this feature again.', 
      'На 3-м уровне вы научились создавать именно те инструменты, которые вам нужны. С помощью воровских инструментов или инструментов ремесленника вы можете волшебным образом создать один набор инструментов ремесленника в свободном пространстве в пределах 5 футов от вас. Это потребует 1 часа непрерывной работы, которая может быть проведена во время короткого или продолжительного отдыха. Хотя они и созданы с помощью магии, сами инструменты немагические и исчезают, когда вы снова используете это умение.', 
      3),
    
    f('ability_score_improvement_artificer', 
      'Ability Score Improvement', 
      'Увеличение характеристик', 
      'When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can\'t increase an ability score above 20 using this feature.', 
      'При достижении 4-го, 8-го, 12-го, 16-го и 19-го уровней вы можете повысить значение одной из ваших характеристик на 2 или двух характеристик на 1. Как обычно, значение характеристики при этом не должно превышать 20.', 
      4),
    
    f('tool_expertise', 
      'Tool Expertise', 
      'Компетентность во владении инструментами', 
      'At 6th level, your proficiency bonus is doubled for any ability check you make that uses your proficiency with a tool.', 
      'На 6-м уровне ваш бонус мастерства удваивается при всех проверках характеристик, совершаемых с использованием инструмента, которым вы владеете.', 
      6),
    
    f('flash_of_genius', 
      'Flash of Genius', 
      'Проблеск гениальности', 
      'At 7th level, you gain the ability to come up with solutions under pressure. When you or another creature you can see within 30 feet of you makes an ability check or a saving throw, you can use your reaction to add your Intelligence modifier to the roll.\n\nYou can use this feature a number of times equal to your Intelligence modifier (minimum of once). You regain all expended uses when you finish a long rest.', 
      'На 7-м уровне вы обрели способность находить решения проблем, будучи в стрессовых ситуациях. Когда вы или другое существо, видимое вами в пределах 30 футов, совершаете проверку характеристики или спасбросок, вы можете реакцией добавить к броску свой модификатор Интеллекта.\n\nВы можете использовать это умение количество раз, равное вашему модификатору Интеллекта (минимум один), и восстанавливаете все потраченные использования, когда заканчиваете продолжительный отдых.', 
      7),
    
    f('magic_item_adept', 
      'Magic Item Adept', 
      'Эксперт в обращении с магическими предметами', 
      'At 10th level, you have achieved a profound understanding of how to use and make magic items:\n• You can attune to up to four magic items at once.\n• If you craft a magic item with a rarity of common or uncommon, it takes you a quarter of the normal time, and it costs you half as much of the usual gold.', 
      'На 10-м уровне вы прекрасно понимаете то, как использовать и создавать магические предметы:\n• Вы можете настроиться на четыре магических предмета одновременно.\n• Если вы создаете магический предмет с редкостью «обычный» или «необычный», то на его создание у вас уходит четверть обычного времени и вдвое меньше золота.', 
      10),
    
    f('spell_storing_item', 
      'Spell-Storing Item', 
      'Хранящий заклинания предмет', 
      'At 11th level, you learn how to store a spell in an object. Whenever you finish a long rest, you can touch one simple or martial weapon or one item that you can use as a spellcasting focus, and you store a spell in it, choosing a 1st- or 2nd-level spell from the artificer spell list that requires 1 action to cast (you needn\'t have it prepared).\n\nWhile holding the object, a creature can take an action to produce the spell\'s effect from it, using your spellcasting ability modifier. If the spell requires concentration, the creature must concentrate. The spell stays in the object until it\'s been used a number of times equal to twice your Intelligence modifier (minimum of twice) or until you use this feature again.', 
      'На 11-м уровне вы можете хранить заклинание в предмете. Каждый раз, заканчивая продолжительный отдых, вы можете прикоснуться к одному простому или воинскому оружию или предмету, который вы можете использовать в качестве заклинательной фокусировки, и сохранить в нем одно заклинание 1-го или 2-го уровня из списка заклинаний изобретателя, которому необходимо 1 действие для накладывания (вам не обязательно подготавливать это заклинание).\n\nДержа этот объект в руке, существо может действием выпустить эффект заклинания из предмета, используя ваш модификатор базовой характеристики. Если заклинание требует концентрации, существо должно её поддерживать. Заклинание остается в объекте до тех пор, пока не будет использовано количество раз, равное удвоенному значению вашего модификатора Интеллекта (минимум дважды), или пока вы не воспользуетесь этим умением снова.', 
      11),
    
    f('magic_item_savant', 
      'Magic Item Savant', 
      'Учёный по магическим предметам', 
      'At 14th level, your skill with magic items deepens:\n• You can attune to up to five magic items at once.\n• You ignore all class, race, spell, and level requirements on attuning to or using a magic item.', 
      'На 14-м уровне ваш навык работы с магическими предметами становится глубже:\n• Вы можете настроиться на пять магических предметов одновременно.\n• Вы игнорируете все требования класса, расы, заклинания и уровня при настройке или использовании магических предметов.', 
      14),
    
    f('magic_item_master', 
      'Magic Item Master', 
      'Мастер в обращении с магическими предметами', 
      'At 18th level, you can attune to up to six magic items at once.', 
      'На 18-м уровне вы можете настроиться на шесть магических предметов одновременно.', 
      18),
    
    f('soul_of_artifice', 
      'Soul of Artifice', 
      'Душа изобретения', 
      'At 20th level, you develop a mystical connection to your magic items, which you can draw on for protection:\n\n• You gain a +1 bonus to all saving throws per magic item you are currently attuned to.\n• If you\'re reduced to 0 hit points but not killed out-right, you can use your reaction to end one of your artificer infusions, causing you to drop to 1 hit point instead of 0.', 
      'На 20-м уровне вы развиваете мистическую связь со своими магическими предметами, которые вы можете использовать для защиты:\n\n• Вы получаете бонус +1 ко всем спасброскам за каждый предмет, на который вы в данный момент настроены.\n• Если ваши хиты опустились до нуля, но вы не убиты, вы можете реакцией уничтожить одну из ваших инфузий, опустив количество ваших хитов до 1 вместо 0.', 
      20),
];

export const ARTIFICER_SPECIALIST_SPELLS: Record<string, string[]> = {
    'alchemist': ['Healing Word', 'Ray of Sickness', 'Flaming Sphere', 'Melf\'s Acid Arrow', 'Gaseous Form', 'Mass Healing Word', 'Blight', 'Death Ward', 'Cloudkill', 'Raise Dead'],
    'armorer': ['Magic Missile', 'Thunderwave', 'Mirror Image', 'Shatter', 'Hypnotic Pattern', 'Lightning Bolt', 'Fire Shield', 'Greater Invisibility', 'Passwall', 'Wall of Force'],
    'artillerist': ['Shield', 'Thunderwave', 'Scorching Ray', 'Shatter', 'Fireball', 'Wind Wall', 'Ice Storm', 'Wall of Fire', 'Cone of Cold', 'Wall of Force'],
    'battlesmith': ['Heroism', 'Shield', 'Branding Smite', 'Warding Bond', 'Aura of Vitality', 'Conjure Barrage', 'Aura of Purity', 'Fire Shield', 'Banishing Smite', 'Mass Cure Wounds']
};

export const ARTIFICER: ClassData = { 
    id: 'artificer', 
    name: { en: 'Artificer', ru: 'Изобретатель' }, 
    hitDie: 8, 
    primaryAbility: ['int'], 
    savingThrows: ['con', 'int'], 
    skillsChoice: { count: 2, options: ['arcana', 'history', 'investigation', 'medicine', 'nature', 'perception', 'sleight_of_hand'] }, 
    features: ARTIFICER_BASE, 
    spellcastingAbility: 'int', 
    multiclassRequirements: [{ requirements: { int: 13 } }],
    subclasses: [ 
        // 1. Alchemist
        sc('alchemist', 'Alchemist', 'Алхимик', [ 
            f('tool_proficiency_alchemist', 'Tool Proficiency', 'Владение инструментами', 
              'When you adopt this specialization at 3rd level, you gain proficiency with alchemist\'s supplies. If you already have this proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.', 
              'Вы получаете владение инструментами алхимика [alchemist\'s supplies]. Если Вы уже ими владеете, то получаете владение одним другим видом ремесленных инструментов по Вашему выбору.', 3),
            
            f('alchemist_spells', 'Alchemist Spells', 'Заклинания алхимика', 
              'Starting at 3rd level, you always have certain spells prepared after you reach particular levels in this class, as shown in the Alchemist Spells table. These spells count as artificer spells for you, but they don’t count against the number of artificer spells you prepare.\n\n3rd: healing word, ray of sickness\n5th: melf\'s acid arrow, flaming sphere\n9th: gaseous form, mass healing word\n13th: death ward, blight\n17th: cloudkill, raise dead', 
              'У вас всегда есть подготовленные заклинания, которые вы получаете на определённых уровнях, согласно таблице «Заклинания алхимика». Для вас они считаются заклинаниями изобретателя, однако они не учитываются в общем количестве заклинаний, которые вы можете подготовить.\n\n3-й: лечащее слово [healing word], луч болезни [ray of sickness]\n5-й: мельфова кислотная стрела [melf\'s acid arrow], пылающий шар [flaming sphere]\n9-й: газообразная форма [gaseous form], множественное лечащее слово [mass healing word]\n13-й: защита от смерти [death ward], усыхание [blight]\n17-й: облако смерти [cloudkill], оживление [raise dead]', 3),
            
            f('experimental_elixir', 'Experimental Elixir', 'Экспериментальный эликсир', 
              'Beginning at 3rd level, whenever you finish a long rest, you can magically produce an experimental elixir in an empty flask you touch. Roll on the Experimental Elixir table for the elixir\'s effect, which is triggered when someone drinks the elixir. As an action, a creature can drink the elixir or administer it to an incapacitated creature.\n\nYou can create additional experimental elixirs by expending a spell slot of 1st level or higher for each one. When you do so, you use your action to create the elixir in an empty flask you touch, and you choose the elixir\'s effect from the Experimental Elixir table.\n\nCreating an experimental elixir requires you to have alchemist supplies on your person, and any elixir you create with this feature lasts until it is drunk or until the end of your next long rest.\n\nWhen you reach certain levels in this class, you can make more elixirs at the end of a long rest: two at 6th level and three at 15th level. Roll for each elixir\'s effect separately. Each elixir requires its own flask.', 
              'Всякий раз, заканчивая продолжительный отдых, вы можете волшебным образом создать экспериментальный эликсир в пустом сосуде, коснувшись его.\n\nСовершите бросок по таблице «Экспериментальный эликсир» для определения эффекта, который возникнет, когда кто-то выпьет эликсир.\n\nДействием существо может выпить эликсир или влить его в недееспособное существо.\n\nВы можете Действием создать дополнительный экспериментальный эликсир, потратив ячейку заклинания 1-го уровня или выше за каждый эликсир. Для этого вы Действием создаёте эликсир в пустом сосуде, которого касаетесь, и самостоятельно выбираете эффект эликсира из таблицы Экспериментальный эликсир.\n\nСоздание экспериментального эликсира требует наличия у вас инструментов алхимика [alchemist\'s supplies].\n\nЛюбой эликсир, который вы создаёте с помощью этого умения, существует до тех пор, пока не будет выпит, или до конца вашего следующего продолжительного отдыха.\n\nКогда вы достигаете определённых уровней в этом классе, вы можете создавать дополнительные эликсиры в конце продолжительного отдыха: два на 6-м уровне и три на 15-м уровне.\n\nБросок для определения эффекта каждого из эликсиров выполняется отдельно, и для каждого эликсира требуется свой собственный сосуд.', 3),
            
            f('alchemical_savant', 'Alchemical Savant', 'Учёный-алхимик', 
              'At 5th level, you\'ve developed masterful command of magical chemicals, enhancing the healing and damage you create through them. Whenever you cast a spell using your alchemist\'s supplies as the spellcasting focus, you gain a bonus to one roll of the spell. That roll must restore hit points or be a damage roll that deals acid, fire, necrotic, or poison damage, and the bonus equals your Intelligence modifier (minimum of +1).', 
              'Вы достигли мастерства в использовании магических реагентов и научились усиливать исцеление и урон, наносимые с их помощью.\n\nКаждый раз, когда вы накладываете заклинание, используя инструменты алхимика [alchemist\'s supplies] в качестве фокусировки, вы получаете бонус к одному из бросков этого заклинания. Этот бросок должен восстанавливать хиты или наносить урон кислотой, огнём, некротической энергией или ядом.\n\nБонус равен вашему модификатору Интеллекта (минимум +1).', 5),
            
            f('experimental_elixir_6', 'Experimental Elixir', 'Экспериментальный эликсир', 
              'When you reach 6th level in this class, you can create additional elixirs at the end of a long rest (total of 2).', 
              'Когда вы достигаете 6-го уровня в этом классе, вы можете создавать дополнительные эликсир в конце продолжительного отдыха (всего 2).', 6),

            f('restorative_reagents', 'Restorative Reagents', 'Восстанавливающие реагенты', 
              'Starting at 9th level, you can incorporate restorative reagents into some of your works:\n\n• Whenever a creature drinks an experimental elixir you created, the creature gains temporary hit points equal to 2d6 + your Intelligence modifier (minimum of 1 temporary hit point).\n• You can cast Lesser Restoration without expending a spell slot and without preparing the spell, provided you use alchemist\'s supplies as the spellcasting focus. You can do so a number of times equal to your Intelligence modifier (minimum of once), and you regain all expended uses when you finish a long rest.', 
              'Начиная с 9 уровня вы можете добавить восстанавливающие реагенты в некоторые из ваших эликсиров:\n\n• Когда существо выпивает экспериментальный эликсир, который вы создали, оно получает количество временных хитов, равное 2к6 + ваш модификатор Интеллекта (минимум 1 временный хит).\n• Вы можете накладывать заклинание малое восстановление [lesser restoration] без использования ячейки заклинаний и без подготовки заклинания при условии, что вы используете инструменты алхимика [alchemist’s supplies] в качестве заклинательной фокусировки. Вы можете использовать это умение количество раз, равное вашему модификатору Интеллекта (минимум один раз), и вы восстанавливаете все потраченные использования, когда завершаете продолжительный отдых.', 9),
            
            f('chemical_mastery', 'Chemical Mastery', 'Химическое мастерство', 
              'By 15th level, you have been exposed to so many chemicals that they pose little risk to you, and you can use them to quickly end certain ailments:\n\n• You gain resistance to acid damage and poison damage, and you are now immune to the poisoned condition.\n• You can cast Greater Restoration and Heal without expending a spell slot, without preparing the spell, and without providing the material component, provided you use alchemist’s supplies as the spellcasting focus. Once you cast either spell with this feature, you can\'t cast that spell with it again until you finish a long rest.', 
              'Вы подвергались воздействию такого количества химических реагентов, что теперь они для вас почти безвредны, и вы можете использовать их, чтобы быстро справиться с некоторыми недугами:\n\n• Вы приобретаете сопротивление к урону кислотой и ядом, а также иммунитет к состоянию отравленный.\n• Вы можете накладывать заклинания высшее восстановление [greater restoration] и полное исцеление [heal] без использования ячейки заклинаний, подготовки и использования материальных компонентов при условии, что вы используете инструменты алхимика [alchemist\'s supplies] в качестве заклинательной фокусировки. Как только вы накладываете одно из этих заклинаний с помощью данного умения, вы не можете наложить его повторно, пока не закончите продолжительный отдых.', 15),

            f('experimental_elixir_15', 'Experimental Elixir', 'Экспериментальный эликсир', 
              'When you reach 15th level in this class, you can create additional elixirs at the end of a long rest (total of 3).', 
              'Когда вы достигаете 15-го уровня в этом классе, вы можете создавать дополнительные эликсир в конце продолжительного отдыха (всего 3).', 15)
        ], 'TCE', 
        'Alchemists’ and witches’ magic relies on the undisputed universal truth that mortals can’t resist bubbles.\n\nAn Alchemist is an expert at combining exotic reagents to produce mystical effects. Alchemists use their creations to give life and to leech it away. Alchemy is the oldest of artificer traditions, and its versatility has long been valued during times of war and peace.',
        'Магия алхимиков и ведьм опирается на бесспорную универсальную истину: смертные не могут устоять перед пузырьками.\n\nАлхимик — эксперт по созданию магических эффектов путём комбинирования экзотических реагентов. Алхимики используют свои творения, чтобы дарить и отбирать жизнь. Алхимия — древнейшая из изобретательских традиций, и её многофункциональность издавна ценилась и во время войн, и в годы мира.'),

        // 2. Armorer
        sc('armorer', 'Armorer', 'Бронник', [
            f('tools_of_the_trade_armorer', 'Tools of the Trade', 'Владение инструментами', 
              'When you adopt this specialization at 3rd level, you gain proficiency with heavy armor. You also gain proficiency with smith\'s tools. If you already have this tool proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.', 
              'Вы получаете владение тяжёлыми доспехами, а также владение инструментами кузнеца. Если вы уже владеете этим набором инструментов, то получаете владение другими инструментами ремесленника по вашему выбору.', 3),
            
            f('armorer_spells', 'Armorer Spells', 'Заклинания бронника', 
              'Starting at 3rd level, you always have certain spells prepared after you reach particular levels in this class, as shown in the Armorer Spells table. These spells count as artificer spells for you, but they don\'t count against the number of artificer spells you prepare.\n\n3rd: magic missile, thunderwave\n5th: mirror image, shatter\n9th: hypnotic pattern, lightning bolt\n13th: fire shield, greater invisibility\n17th: passwall, wall of force', 
              'У вас всегда есть подготовленные заклинания, которые вы получаете на определенных уровнях, согласно таблице «Заклинания бронника». Для вас они считаются заклинаниями изобретателя, однако они не учитываются в общем количестве заклинаний, которые вы можете подготовить.\n\n3-й: волшебная стрела [magic missile], волна грома [thunderwave]\n5-й: отражения [mirror image], дребезги [shatter]\n9-й: гипнотический узор [hypnotic pattern], молния [lightning bolt]\n13-й: огненный щит [fire shield], высшая невидимость [greater invisibility]\n17-й: создание прохода [passwall], силовая стена [wall of force]', 3),
            
            f('arcane_armor', 'Arcane Armor', 'Мистический доспех', 
              'Beginning at 3rd level, your metallurgical pursuits have led to you making armor a conduit for your magic. As an action, you can turn a suit of armor you are wearing into Arcane Armor, provided you have smith\'s tools in hand.\n\nYou gain the following benefits while wearing this armor:\n\n• If the armor normally has a Strength requirement, the arcane armor lacks this requirement for you.\n• You can use the arcane armor as a spellcasting focus for your artificer spells.\n• The armor attaches to you and can’t be removed against your will. It also expands to cover your entire body, although you can retract or deploy the helmet as a bonus action. The armor replaces any missing limbs, functioning identically to a body part it is replacing.\n• You can doff or don the armor as an action.\n\nThe armor continues to be Arcane Armor until you don another suit of armor or you die.', 
              'Ваши опыты с металлами привели к тому, что вы сделали доспех проводником своей магии. Если у вас в руках находятся инструменты кузнеца, то действием вы можете превратить доспех, который на вас надет, в мистический.\n\nПока вы облачены в этот доспех, вы получаете следующие преимущества:\n\n• Если обычно доспех имеет определённые требования к Силе, то для вашего мистического доспеха это не нужно.\n• Вы можете использовать мистический доспех в качестве заклинательной фокусировки для ваших заклинаний изобретателя.\n• Доспех соединён с вами и не может быть снят против вашей воли. Он полностью покрывает ваше тело, однако вы можете сложить шлем или развернуть его обратно бонусным действием. Доспех заменяет любые отсутствующие у вас конечности — замена функционирует идентично оригинальным частям тела.\n• Действием вы можете снять или надеть доспех.\n\nБроня остаётся мистическим доспехом, пока вы не облачитесь в другой комплект доспехов или не умрёте.', 3),
            
            f('armor_model', 'Armor Model', 'Модель доспеха', 
              'Beginning at 3rd level, you can customize your Arcane Armor. When you do so, choose one of the following armor models: Guardian or Infiltrator. The model you choose gives you special benefits while you wear it.\n\nEach model includes a special weapon. When you attack with that weapon, you can add your Intelligence modifier, instead of Strength or Dexterity, to the attack and damage rolls.\n\nYou can change the armor\'s model whenever you finish a short or long rest, provided you have smith\'s tools in hand.\n\n**Guardian.** You design your armor to be in the front line of conflict. It has the following features:\n\n**Thunder Gauntlets.** Each of the armor\'s gauntlets counts as a simple melee weapon while you aren\'t holding anything in it, and it deals 1d8 thunder damage on a hit. A creature hit by the gauntlet has disadvantage on attack rolls against targets other than you until the start of your next turn, as the armor magically emits a distracting pulse when the creature attacks someone else.\n\n**Defensive Field.** As a bonus action, you can gain temporary hit points equal to your level in this class, replacing any temporary hit points you already have. You lose these temporary hit points if you doff the armor. You can use this bonus action a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.\n\n**Infiltrator.** You customize your armor for subtle undertakings. It has the following features:\n\n**Lightning Launcher.** A gemlike node appears on one of your armored fists or on the chest (your choice). It counts as a simple ranged weapon, with a normal range of 90 feet and a long range of 300 feet, and it deals 1d6 lightning damage on a hit. Once on each of your turns when you hit a creature with it, you can deal an extra 1d6 lightning damage to that target.\n\n**Powered Steps.** Your walking speed increases by 5 feet.\n\n**Dampening Field.** You have advantage on Dexterity (Stealth) checks. If the armor normally imposes disadvantage on such checks, the advantage and disadvantage cancel each other, as normal.', 
              'Вы можете модифицировать свой мистический доспех. Выберите одну из двух нижеописанных моделей: «страж» или «лазутчик». Модель, которую вы выбираете, даёт вам особые преимущества во время использования.\n\nКаждая модель обладает специальным оружием. Когда вы им атакуете, можете добавить к броскам атаки и урона свой модификатор Интеллекта вместо Силы или Ловкости.\n\nВы можете изменить модель доспеха по окончании короткого или продолжительного отдыха при условии, что держите в руках инструменты кузнеца.\n\n**Страж.** Вы настраиваете свой доспех таким образом, чтобы быть в гуще сражения. Он имеет следующие особенности:\n\n**Громовые перчатки.** Каждая из латных перчаток вашего доспеха, пока вы ничего в них не держите, считается простым рукопашным оружием и наносит 1к8 урона звуком при попадании. Существо, по которому попали перчаткой, до начала вашего следующего хода совершает броски атаки с помехой против всех целей кроме вас, так как доспех магическим образом испускает отвлекающий импульс, когда существо атакует кого-то другого.\n\n**Защитное поле.** Бонусным действием вы можете получить количество временных хитов, равное вашему уровню в этом классе, заменив ими любые временные хиты, которые у вас уже есть. Вы теряете эти временные хиты, если снимаете доспех. Вы можете использовать эту особенность количество раз, равное вашему бонусу мастерства, и восстанавливаете все использования, когда заканчиваете продолжительный отдых.\n\n**Лазутчик.** Вы настраиваете доспех для того, чтобы действовать деликатно. Он имеет следующие особенности:\n\n**Метатель молний.** Похожий на драгоценный камень нарост появляется на одном из ваших бронированных кулаков или на груди (по вашему выбору). Он считается простым дальнобойным оружием с нормальной дистанцией в 90 футов и максимальной дистанцией в 300 футов, наносящим 1к6 урона электричеством при попадании. Один раз в каждый свой ход, когда вы попадаете по существу этим оружием, вы можете дополнительно нанести ему 1к6 урона электричеством.\n\n**Заряженные шаги.** Ваша скорость ходьбы увеличивается на 5 футов.\n\n**Заглушающее поле.** Вы совершаете с преимуществом проверки Ловкости (Скрытность). Если доспех накладывает помеху на данную проверку, то преимущество и помеха отменяют друг друга, как и обычно.', 3),
            
            f('extra_attack_armorer', 'Extra Attack', 'Дополнительная атака', 
              'Starting at 5th level, you can attack twice, rather than once, whenever you take the Attack action on your turn.', 
              'Когда вы совершаете в свой ход действие Атака, то можете совершить две атаки вместо одной.', 5),
            
            f('armor_modifications', 'Armor Modifications', 'Модификации доспеха', 
              'At 9th level, you learn how to use your artificer infusions to specially modify your Arcane Armor. That armor now counts as separate items for the purposes of your Infuse Items feature: armor (the chest piece), boots, helmet, and the armor\'s special weapon. Each of those items can bear one of your infusions, and the infusions transfer over if you change your armor\'s model with the Armor Model feature. In addition, the maximum number of items you can infuse at once increases by 2, but those extra items must be part of your Arcane Armor.', 
              'Вы узнаёте, как использовать инфузии, чтобы особым образом модифицировать свой мистический доспех. Теперь для вашего умения «Инфузирование предмета» каждый элемент доспеха считается отдельным предметом: доспех (нагрудник), ботинки, шлем и специальное оружие доспеха. Любой из этих предметов может быть насыщен одной из ваших инфузий, которые остаются, даже если вы меняете модель доспеха с помощью соответствующего умения. Кроме того, ваше максимальное количество насыщенных магией предметов увеличивается на два при условии, что они являются частями вашего мистического доспеха.', 9),
            
            f('perfected_armor', 'Perfected Armor', 'Идеальная броня', 
              'At 15th level, your Arcane Armor gains additional benefits based on its model, as shown below.\n\n**Guardian.** When a Huge or smaller creature you can see ends its turn within 30 feet of you, you can use your reaction to magically force it to make a Strength saving throw against your spell save DC. On a failed save, you pull the creature up to 25 feet directly to an unoccupied space. If you pull the target to a space within 5 feet of you, you can make a melee weapon attack against it as part of this reaction. You can use this reaction a number of times equal to your proficiency bonus, and you regain all expended uses of it when you finish a long rest.\n\n**Infiltrator.** Any creature that takes lightning damage from your Lightning Launcher glimmers with magical light until the start of your next turn. The glimmering creature sheds dim light in a 5-foot radius, and it has disadvantage on attack rolls against you, as the light jolts it if it attacks you. In addition, the next attack roll against it has advantage, and if that attack hits, the target takes an extra 1d6 lightning damage.', 
              'Ваш мистический доспех получает дополнительные преимущества в зависимости от его модели.\n\n**Страж.** Когда существо Огромного или меньшего размера, которое вы можете видеть, заканчивает свой ход в пределах 30 футов от вас, вы можете использовать свою реакцию и магическим образом заставить это существо совершить спасбросок Силы против Сл спасброска ваших заклинаний. При провале существо притягивается к вам на расстояние до 25 футов в свободное пространство. Если вы притягиваете существо к месту в пределах 5 футов рядом с вами, то можете совершить рукопашную атаку оружием по этому существу частью той же реакции. Вы можете использовать реакцию подобным образом количество раз, равное вашему бонусу мастерства. Вы восстанавливаете все потраченные использования после окончания продолжительного отдыха.\n\n**Лазутчик.** Любое существо, получившее урон от «Метателя молний», начинает мерцать магическим светом до начала вашего следующего хода. Существо излучает тусклый свет в радиусе 5 футов и совершает броски атаки против вас с помехой, так как свет слепит его при попытке атаковать. Кроме того, следующая атака по этому существу совершается с преимуществом, и, если атака попадает, то цель дополнительно получает 1к6 урона электричеством.', 15)
        ], 'TCE', 
        'An Artificer who specializes as an Armorer modifies armor to function almost like a second skin. The armor is enhanced to hone the artificer’s magic, unleash potent attacks, and generate a formidable defense. The artificer bonds with this armor, becoming one with it even as they experiment with it and refine its magical capabilities.',
        'Изобретатель, выбравший специальность бронника, модифицирует броню, делая её практически второй кожей. Доспех изменяют, чтобы можно было использовать магию изобретателя, обрушивать на врагов мощные атаки и увеличить защиту. Изобретатель связывает себя с этой бронёй, оставаясь с ней единым целым даже во время экспериментов, и совершенствует её магические возможности.'),

        // 3. Artillerist
        sc('artillerist', 'Artillerist', 'Артиллерист', [
            f('tool_proficiency_artillerist', 'Tool Proficiency', 'Владение инструментами', 
              'You gain proficiency with woodcarver\'s tools. If you already have this proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.', 
              'Вы получаете владение инструментами резчика по дереву. Если вы уже владеете этим набором инструментов, то вы получаете владение другими инструментами ремесленника по вашему выбору.', 3),
            
            f('artillerist_spells', 'Artillerist Spells', 'Заклинания артиллериста', 
              'You always have certain spells prepared after you reach particular levels in this class, as shown in the Artillerist Spells table. These spells count as artificer spells for you, but they don’t count against the number of artificer spells you prepare.\n\n3rd: shield, thunderwave\n5th: scorching ray, shatter\n9th: fireball, wind wall\n13th: ice storm, wall of fire\n17th: cone of cold, wall of force', 
              'У вас всегда есть подготовленные заклинания, которые вы получаете на определённых уровнях, согласно таблице «Заклинания артиллериста». Для вас они считаются заклинаниями изобретателя, однако они не учитываются в общем количестве заклинаний, которые вы можете подготовить.\n\n3-й: волна грома [thunderwave], щит [shield]\n5-й: дребезги [shatter], палящий луч [scorching ray]\n9-й: огненный шар [fireball], стена ветров [wind wall]\n13-й: град [ice storm], огненная стена [wall of fire]\n17-й: конус холода [cone of cold], силовая стена [wall of force]', 3),
            
            f('eldritch_cannon', 'Eldritch Cannon', 'Мистическая пушка', 
              'You\'ve learned how to create a magical cannon. Using woodcarver\'s tools or smith\'s tools, you can take an action to magically create a Small or Tiny eldritch cannon in an unoccupied space on a horizontal surface within 5 feet of you. A Small eldritch cannon occupies its space, and a Tiny one can be held in one hand.\n\nOnce you create a cannon, you can\'t do so again until you finish a long rest or until you expend a spell slot to create one. You can have only one cannon at a time and can\'t create one while your cannon is present.\n\nThe cannon is a magical object. Regardless of its size, the cannon has an AC of 18 and a number of hit points equal to five times your artificer level. It is immune to poison damage and psychic damage. If it is forced to make an ability check or a saving throw, treat all its ability scores as 10 (+0). If the mending spell is cast on it, it regains 2d6 hit points. It disappears if it is reduced to 0 hit points or after 1 hour. You can dismiss it early as an action.\n\nWhen you create the cannon, you determine its appearance and whether it has legs. You also decide which type it is, choosing from the options on the Eldritch Cannons table. On each of your turns, you can take a bonus action to cause the cannon to activate if you are within 60 feet of it. As part of the same bonus action, you can direct the cannon to walk or climb up to 15 feet to an unoccupied space, provided it has legs.\n\n**Flamethrower:** The cannon exhales fire in an adjacent 15-foot cone that you designate. Each creature in that area must make a Dexterity saving throw against your spell save DC, taking 2d8 fire damage on a failed save or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren\'t being worn or carried.\n**Force Ballista:** Make a ranged spell attack, originating from the cannon, at one creature or object within 120 feet of it. On a hit, the target takes 2d8 force damage, and if the target is a creature, it is pushed up to 5 feet away from the cannon.\n**Protector:** The cannon emits a burst of positive energy that grants itself and each creature of your choice within 10 feet of it a number of temporary hit points equal to 1d8 + your Intelligence modifier (minimum of +1).', 
              'Вы научились создавать мистическую пушку. Используя инструменты резчика по дереву или инструменты кузнеца, вы можете действием создать Маленькую или Крошечную мистическую пушку в свободном пространстве на горизонтальной поверхности в пределах 5 футов от вас. Маленькая пушка занимает своё пространство, тогда как Крошечную можно держать в одной руке.\n\nСоздав пушку, вы не сможете сделать это снова, пока не закончите продолжительный отдых или не потратите ячейку заклинаний. Единовременно вы можете иметь только одну пушку, и, пока она существует, вы не можете создать новую.\n\nПушка — это магический предмет. Независимо от размера она имеет КД 18 и количество хитов, равное вашему пятикратному уровню в классе изобретателя. Пушка имеет иммунитет к урону ядом и психической энергией. Если нужно будет совершить проверку характеристики или спасбросок, считайте все её характеристики равными 10 (+0). При накладывании на пушку заговора починка [mending] она восстанавливает 2к6 хитов. Пушка исчезает, если её хиты опускаются до 0, либо спустя 1 час. Действием вы можете заставить её исчезнуть раньше.\n\nКогда вы создаете пушку, то определяете её внешний вид и то, есть ли у неё ноги. Также вы сами определяете какого именно она будет типа, выбирая из таблицы «Мистические пушки». В каждый ваш ход вы можете бонусным действием активировать пушку, если находитесь в пределах 60 футов от неё. Частью того же бонусного действия вы можете приказать пушке передвинуться или взобраться на высоту до 15 футов в свободное пространство при условии, что у неё есть ноги.\n\n**Огнемёт:** Пушка извергает поток огня в 15-футовом конусе от неё в указанном вами направлении. Каждое существо в зоне поражения должно совершить спасбросок Ловкости против Сл спасброска ваших заклинаний, получая 2к8 урона огнём при провале и половину этого урона при успехе. Огонь поджигает горючие предметы в области, которые никто не несёт и не носит.\n**Силовая баллиста:** Совершите дальнобойную атаку заклинанием, исходящую из пушки, по существу или предмету, находящемуся на расстоянии до 120 футов от пушки. При попадании цель получает 2к8 урона силовым полем, и, если цель — существо, она отталкивается на 5 футов от пушки.\n**Защитник:** Пушка испускает вспышку положительной энергии, которая даёт каждому существу по вашему выбору в пределах 10 футов от пушки и самой пушке количество временных хитов, равное 1к8 + ваш модификатор Интеллекта (минимум +1).', 3),
            
            f('arcane_firearm', 'Arcane Firearm', 'Мистическое огнестрельное оружие', 
              'You know how to turn a wand, staff, or rod into an arcane firearm, a conduit for your destructive spells. When you finish a long rest, you can use woodcarver\'s tools to carve special sigils into a wand, staff, or rod and thereby turn it into your arcane firearm. The sigils disappear from the object if you later carve them on a different item. Otherwise, the sigils last indefinitely.\n\nYou can use your arcane firearm as a spellcasting focus for your artificer spells. When you cast an artificer spell through the firearm, roll a d8, and you gain a bonus to one of the spell\'s damage rolls equal to the number rolled.', 
              'Вы знаете, как превратить волшебную палочку, посох или жезл в мистическое огнестрельное оружие, проводник ваших разрушительных заклинаний. Когда вы заканчиваете продолжительный отдых, вы можете использовать инструменты резчика по дереву, чтобы вырезать на палочке, посохе или жезле специальные символы и сделать этот предмет своим мистическим огнестрельным оружием. Символы исчезнут с предмета, если вы вырежете их на другом предмете позже. В противном случае они сохраняются бесконечно.\n\nВы можете использовать своё мистическое огнестрельное оружие как заклинательную фокусировку для ваших заклинаний изобретателя. Когда вы накладываете заклинание изобретателя с помощью огнестрельного оружия, бросьте к8 и добавьте результат этого броска к одному из бросков урона заклинания.', 5),
            
            f('explosive_cannon', 'Explosive Cannon', 'Взрывоопасная пушка', 
              'Every eldritch cannon you create is now more destructive:\n\n• The cannon\'s damage rolls all increase by 1d8.\n• As an action, you can command the cannon to detonate if you are within 60 feet of it. Doing so destroys the cannon and forces each creature within 20 feet of it to make a Dexterity saving throw against your spell save DC, taking 3d8 force damage on a failed save or half as much damage on a successful one.', 
              'Каждая создаваемая вами мистическая пушка становится более разрушительной:\n\nВсе броски урона пушки увеличиваются на 1к8.\nЕсли вы находитесь в пределах 60 футов от пушки, то можете действием приказать ей взорваться. Это уничтожает пушку и заставляет каждое существо в пределах 20 футов от неё совершить спасбросок Ловкости против Сл спасброска ваших заклинаний, получая 3к8 урона силовым полем при провале и половину этого урона при успехе.', 9),
            
            f('fortified_position', 'Fortified Position', 'Укреплённая позиция', 
              'You\'re a master at forming well-defended emplacements using your eldritch cannon:\n\n• You and your allies have half cover while within 10 feet of a cannon you create, as a result of a shimmering field of magical protection that the cannon emits.\n• You can now have two cannons at the same time. You can create two with the same action (but not the same spell slot), and you can activate both of them with the same bonus action. You determine whether the cannons are identical to each other or different. You can\'t create a third cannon while you have two.', 
              'Вы — мастер по созданию хорошо защищённых огневых позиций с использованием мистической пушки:\n\nВы и ваши союзники получаете укрытие наполовину в пределах 10 футов от вашей мистической пушки из-за излучаемого ею мерцающего поля магической защиты.\nТеперь у вас может быть две пушки одновременно. Вы можете создавать две пушки одним действием (но не за одну ячейку заклинаний), и активировать их одновременно бонусным действием. Вы определяете, одинаковы ли эти пушки или отличаются друг от друга. Вы не можете создать третью пушку, пока у вас есть две.', 15)
        ], 'TCE', 
        'Artillerist\nSource: Tasha’s Cauldron of Everything\n\n"A lot of artificers ask the question, \'Can collateral damage be even more collateral?\'"\n—TASHA\n\nAn Artillerist specializes in using magic to hurl energy, projectiles, and explosions on a battlefield. This destructive power was valued by all the armies of the Great War. Now that the war is over, some artillerists have used their specialized knowledge to help rebuild. The world-traveling gnome artificer Vi has been especially vocal about making things right: "It\'s time we fixed things instead of blowing them all to hell."',
        'Артиллерист\nИсточник: «Tasha’‎s Cauldron of Everything»\n\nНекоторые изобретатели задаются непростым вопросом:\n«Может ли сопутствующий ущерб быть еще больше?»\n- ТАША\n\nАртиллерист специализируется на использовании в бою магии для метания огня, снарядов и вспышек энергии. Эта разрушительная сила ценится армиями многих миров. Когда же война заканчивается, некоторые из этих специалистов стремятся обеспечить другим спокойную жизнь, тратя силы на борьбу с ростом напряжённости. Путешествующая по мирам гном-изобретательница Ви особенно активно выступает за то, чтобы всё исправить: «Настало время исправлять ситуацию, а не взрывать всё к чёрту».'),

        // 4. Battle Smith
        sc('battlesmith', 'Battle Smith', 'Боевой кузнец', [
            f('tool_proficiency_battlesmith', 'Tool Proficiency', 'Владение инструментами', 
              'When you adopt this specialization at 3rd level, you gain proficiency with smith\'s tools. If you already have this proficiency, you gain proficiency with one other type of artisan\'s tools of your choice.', 
              'Вы получаете владение инструментами кузнеца. Если вы уже владеете этим набором инструментов, то вы получаете владение другими инструментами ремесленника по вашему выбору.', 3),
            
            f('battlesmith_spells', 'Battle Smith Spells', 'Заклинания боевого кузнеца', 
              'Starting at 3rd level, you always have certain spells prepared after you reach particular levels in this class, as shown in the Battle Smith Spells table. These spells count as artificer spells for you, but they don’t count against the number of artificer spells you prepare.\n\n3rd: heroism, shield\n5th: branding smite, warding bond\n9th: aura of vitality, conjure barrage\n13th: aura of purity, fire shield\n17th: banishing smite, mass cure wounds', 
              'У вас всегда есть подготовленные заклинания, которые вы получаете на определённых уровнях, согласно таблице «Заклинания боевого кузнеца». Для вас они считаются заклинаниями изобретателя, однако не учитываются в общем количестве заклинаний, которые вы можете подготовить.\n\n3-й: щит [shield], героизм [heroism]\n5-й: клеймящая кара [branding smite], охраняющая связь [warding bond]\n9-й: аура живучести [aura of vitality], призыв заграждения [conjure barrage]\n13-й: аура очищения [aura of purity], огненный щит [fire shield]\n17-й: изгоняющая кара [banishing smite], множественное лечение ран [mass cure wounds]', 3),
            
            f('battle_ready', 'Battle Ready', 'Боевая готовность', 
              'When you reach 3rd level, your combat training and your experiments with magic have paid off in two ways:\n• You gain proficiency with martial weapons.\n• When you attack with a magic weapon, you can use your Intelligence modifier, instead of Strength or Dexterity, for the attack and damage rolls.', 
              'Ваша боевая подготовка и эксперименты с магией окупились, даровав две особенности:\n\nВы получаете владение воинским оружием.\nКогда вы атакуете магическим оружием, то можете использовать ваш модификатор Интеллекта вместо модификатора Силы или Ловкости для бросков атаки и урона.', 3),
            
            f('steel_defender', 'Steel Defender', 'Стальной защитник', 
              'By 3rd level, your tinkering has borne you a faithful companion, a steel defender. It\'s friendly to you and your companions, and it obeys your commands. You determine the creature\'s appearance and whether it has two legs or four; your choice has no effect on its game statistics.\n\nIn combat, the defender shares your initiative count, but it takes its turn immediately after yours. It can move and use its reaction on its own, but the only action it takes on its turn is the Dodge action, unless you take a bonus action on your turn to command it to take another action. That action can be one in its stat block or some other action. If you are incapacitated, the defender can take any action of its choice, not just Dodge.\n\nIf the mending spell is cast on it, it regains 2d6 hit points. If it has died within the last hour, you can use your smith\'s tools as an action to revive it, provided you are within 5 feet of it and you expend a spell slot of 1st level or higher. The defender returns to life after 1 minute with all its hit points restored.\n\nAt the end of a long rest, you can create a new steel defender if you have smith\'s tools with you. If you already have a defender from this feature, the first one immediately perishes. The defender also perishes if you die.', 
              'Ваше искусство позволило обзавестись спутником — стальным защитником [steel defender]. Он дружелюбен к вам и вашим союзникам, и подчиняется вашим командам. Вы определяете внешний вид этого существа, а также то, две у него ноги или четыре — это не влияет на игровые характеристики.\n\nВ бою стальной защитник имеет такую же инициативу, как и вы, и ходит сразу после вас. Он может перемещаться и использовать свою реакцию самостоятельно, но единственное действие, которое он может совершать в свой ход — это Уклонение, если только вы не используете своё бонусное действие, чтобы приказать ему сделать что-то другое. Это действие может быть одним из тех, что описаны в его блоке статистики, или же любым другим. Если вы недееспособны, то защитник может использовать любое действие по своему усмотрению, а не только Уклонение.\n\nЕсли на защитника накладывается заговор починка [mending], то он восстанавливает 2к6 хитов. Если он умирает, то в течение часа вы можете действием оживить его, используя инструменты кузнеца. Вы должны находиться в 5 футах от стального защитника, и нужно будет потратить одну ячейку заклинания 1-го уровня или выше. Защитник возвращается к жизни через 1 минуту с полным количеством хитов.\n\nВы можете создать нового защитника в конце продолжительного отдыха, если у вас есть инструменты кузнеца. Если у вас уже есть защитник, созданный с помощью этого умения, то он мгновенно погибает. Защитник также погибает, если вы умираете.', 3),
            
            f('extra_attack_battlesmith', 'Extra Attack', 'Дополнительная атака', 
              'Starting at 5th level, you can attack twice, rather than once, whenever you take the Attack action on your turn.', 
              'Когда вы совершаете в свой ход действие Атака, то можете совершить две атаки вместо одной.', 5),
            
            f('arcane_jolt', 'Arcane Jolt', 'Магическая встряска', 
              'At 9th level, you\'ve learn new ways to channel magical energy to harm or heal. When either you hit a target with a magic weapon attack or your steel defender hits a target with an attack, you can channel magical energy through the strike to create one of the following effects:\n• The target takes an extra 2d6 force damage.\n• Choose one creature or object you can see within 30 feet of the target. Healing energy flows into the chosen recipient, restoring 2d6 hit points to it.\n\nYou can use this energy a number of times equal to your Intelligence modifier (minimum of once), but you can do so no more than once on a turn. You regain all expended uses when you finish a long rest.', 
              'Вы изучаете новые способы направлять магическую энергию, чтобы нанести вред или исцелить. Когда вы попадаете по цели атакой магическим оружием, или ваш стальной защитник попадает по цели, вы можете направить магическую энергию через этот удар для создания одного из следующих эффектов:\n\nЦель дополнительно получает 2к6 урона силовым полем.\nВыберите одно существо или объект, который вы можете видеть в радиусе 30 футов от цели. К выбранной цели направляется целительная энергия, восстанавливая ей 2к6 хитов.\nВы можете направлять эту магическую энергию количество раз, равное вашему модификатору Интеллекта (минимум один раз), но не более одного раза за ход. Вы восстанавливаете все потраченные использования после окончания продолжительного отдыха.', 9),
            
            f('improved_defender', 'Improved Defender', 'Улучшенный защитник', 
              'At 15th level, your Arcane Jolt and steel defender become more powerful:\n• The extra damage and the healing of your Arcane Jolt both increase to 4d6.\n• Your steel defender gains a +2 bonus to Armor Class.\n• Whenever your steel defender uses its Deflect Attack, the attacker takes force damage equal to 1d4 + your Intelligence modifier.', 
              'Ваше умение «Магическая встряска» и стальной защитник усиливаются:\n\nДополнительный урон и исцеление от «Магической встряски» увеличиваются до 4к6.\nВаш стальной защитник получает бонус +2 к КД.\nКаждый раз, когда ваш стальной защитник использует «Отражение атаки», атакующий получает урон силовым полем, равный 1к4 + ваш модификатор Интеллекта.', 15)
        ], 'TCE', 
        'Battle Smith\nSource: Tasha’s Cauldron of Everything\n\nArmies require protection, and someone has to put things back together if those defenses fail. A combination of protector and medic, a Battle Smith is an expert at defending others and repairing both objects and organics. In their work, Battle Smiths are accompanied by a steel defender, a protective companion of their own creation. Many soldiers tell stories of nearly dying before being saved by a Battle Smith and a steel defender.\n\nIn the world of Eberron, Battle Smiths played a key role in House Cannith\'s work on battle constructs and the warforged, and after the Last War, these artificers led the effort to aid those who were injured in the war\'s horrific battles.',
        'Боевой кузнец\nИсточник: «Tasha’s Cauldron of Everything»\n\nВойска нуждаются в защите, и кто-то должен восстанавливать её, если она разрушена. Сочетающий в себе защитника и медика боевой кузнец является экспертом по защите других и восстановлению как матчасти, так и личного состава. В работе боевому кузнецу, как правило, помогает сопровождающий его железный защитник — компаньон, которого он создаёт сам. Многие воины рассказывают истории о том, как чуть не погибли, но были спасены боевым кузнецом и его железным защитником.\n\nВ мире Эберрон боевые кузнецы играют ключевую роль в работе дома Каннит по созданию боевых конструктов и кованых, и именно эти изобретатели возглавляют усилия, направленные на помощь раненым в ужасных сражениях Последней войны.')
    ] 
};
