
import { ClassData } from '../../types';
import { f, sc } from '../dataHelpers';

const BARD_BASE = [
    f('spellcasting_bard', 
      'Spellcasting', 
      'Использование заклинаний', 
      'You have learned to untangle and reshape the fabric of reality in harmony with your wishes and music. Your spells are part of your vast repertoire, magic that you can tune to different situations.\n\n**Cantrips.** You know two cantrips of your choice from the bard spell list. You learn additional bard cantrips of your choice at higher levels.\n\n**Spell Slots.** The Bard table shows how many spell slots you have to cast your bard spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell\'s level or higher. You regain all expended spell slots when you finish a long rest.\n\n**Spells Known of 1st Level and Higher.** You know four 1st-level spells of your choice from the bard spell list. The Spells Known column of the Bard table shows when you learn more bard spells of your choice.\n\n**Spellcasting Ability.** Charisma is your spellcasting ability for your bard spells.\n\n**Ritual Casting.** You can cast any bard spell you know as a ritual if that spell has the ritual tag.\n\n**Spellcasting Focus.** You can use a musical instrument as a spellcasting focus for your bard spells.', 
      'Вы научились изменять ткань реальности в соответствии с вашими волей и музыкой. Ваши заклинания являются частью вашего обширного репертуара; это магия, которой вы найдёте применение в любой ситуации.\n\n**Заговоры (заклинания 0-го уровня).** Вы знаете два заговора из списка доступных для барда на ваш выбор. При достижении более высоких уровней вы выучите новые, в соответствии с колонкой «известные заговоры».\n\n**Ячейки заклинаний.** Таблица «Бард» показывает, сколько ячеек заклинаний у вас есть для заклинаний барда 1-го и других уровней. Для накладывания заклинания вы должны потратить ячейку соответствующего либо превышающего уровня. Вы восстанавливаете все потраченные ячейки в конце продолжительного отдыха.\n\n**Известные заклинания первого и более высоких уровней.** Вы знаете четыре заклинания 1-го уровня на свой выбор из списка доступных барду. Колонка «известные заклинания» показывает, когда вы сможете выучить новые заклинания. Кроме того, когда вы получаете новый уровень в этом классе, вы можете одно из известных вам заклинаний барда заменить на другое.\n\n**Базовая характеристика заклинаний.** При накладывании заклинаний бард использует свою Харизму. Ваша магия проистекает из сердечности и душевности, которую вы вкладываете в исполнение музыки и произнесение речей.\n\n**Ритуальное колдовство.** Вы можете сотворить любое известное вам заклинание барда в качестве ритуала, если заклинание позволяет это.\n\n**Фокусировка заклинания.** Вы можете использовать музыкальный инструмент в качестве фокусировки для ваших заклинаний барда.', 
      1),
    
    f('additional_bard_spells',
      'Additional Bard Spells',
      'Дополнительные заклинания барда',
      'The spells in the following list expand the bard spell list in the Player\'s Handbook.\n1st: Command, Color Spray\n2nd: Aid, Enlarge/Reduce, Mirror Image\n3rd: Intellect Fortress, Mass Healing Word, Slow\n4th: Phantasmal Killer\n5th: Rary\'s Telepathic Bond\n6th: Heroes\' Feast\n7th: Dream of the Blue Veil, Prismatic Spray\n8th: Antipathy/Sympathy\n9th: Prismatic Wall',
      'Заклинания в следующем списке расширяют список заклинаний барда из «Книги игрока».\n1: приказ [command], сверкающие брызги [color spray]\n2: отражения [mirror image], подмога [aid], увеличение/уменьшение [enlarge/reduce]\n3: замедление [slow], крепость интеллекта [intellect fortress], множественное лечащее слово [mass healing word]\n4: воображаемый убийца [phantasmal killer]\n5: ментальная связь Рэри [Rary’s telepathic bond] (ритуал)\n6: пир героев [heroes’ feast]\n7: радужные брызги [prismatic spray], сон синей вуали [dream of the blue veil]\n8: антипатия/симпатия [antipathy/sympathy]\n9: радужная стена [prismatic wall]',
      1,
      undefined,
      undefined,
      'TCE'
    ),

    f('bardic_inspiration', 
      'Bardic Inspiration', 
      'Вдохновение барда', 
      'You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 60 feet of you who can hear you. That creature gains one Bardic Inspiration die, a d6.\n\nOnce within the next 10 minutes, the creature can roll the die and add the number rolled to one ability check, attack roll, or saving throw it makes. The creature can wait until after it rolls the d20 before deciding to use the Bardic Inspiration die, but must decide before the DM says whether the roll succeeds or fails. Once the Bardic Inspiration die is rolled, it is lost. A creature can have only one Bardic Inspiration die at a time.\n\nYou can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain any expended uses when you finish a long rest.\n\nYour Bardic Inspiration die changes when you reach certain levels in this class. The die becomes a d8 at 5th level, a d10 at 10th level, and a d12 at 15th level.', 
      'Своими словами или музыкой вы можете вдохновлять других. Для этого вы должны бонусным действием выбрать одно существо, отличное от вас, в пределах 60 футов, которое может вас слышать. Это существо получает кость бардовского вдохновения — к6.\n\nВ течение следующих 10 минут это существо может один раз бросить эту кость и добавить результат к проверке характеристики, броску атаки или спасброску, который оно совершает. Существо может принять решение о броске кости вдохновения уже после броска к20, но должно сделать это прежде, чем Мастер объявит результат броска. Как только кость бардовского вдохновения брошена, она исчезает. Существо может иметь только одну такую кость одновременно.\n\nВы можете использовать это умение количество раз, равное модификатору вашей Харизмы, но как минимум один раз. Потраченные использования этого умения восстанавливаются после продолжительного отдыха.\n\nВаша кость бардовского вдохновения изменяется с ростом вашего уровня в этом классе. Она становится к8 на 5-м уровне, к10 на 10-м уровне и к12 на 15-м уровне.', 
      1),
    
    f('jack_of_all_trades', 
      'Jack of All Trades', 
      'Мастер на все руки', 
      'Starting at 2nd level, you can add half your proficiency bonus, rounded down, to any ability check you make that doesn\'t already include your proficiency bonus.', 
      'Вы можете добавлять половину бонуса мастерства, округлённую в меньшую сторону, ко всем проверкам характеристики, куда этот бонус еще не включён.', 
      2),
    
    f('song_of_rest', 
      'Song of Rest', 
      'Песнь отдыха', 
      'Beginning at 2nd level, you can use soothing music or oration to help revitalize your wounded allies during a short rest. If you or any friendly creatures who can hear your performance regain hit points at the end of the short rest by spending one or more Hit Dice, each of those creatures regains an extra 1d6 hit points. The extra hit points increase when you reach certain levels in this class: to 1d8 at 9th level, to 1d10 at 13th level, and to 1d12 at 17th level.', 
      'Вы с помощью успокаивающей музыки или речей можете помочь своим раненым союзникам восстановить их силы во время короткого отдыха. Если вы или любые союзные существа, способные слышать ваше исполнение, восстанавливаете хиты в конце короткого отдыха, используя Кости Хитов, каждое потратившее Кость Хитов существо восстанавливает дополнительно 1к6 хитов.\n\nКоличество дополнительно восстанавливаемых хитов растёт с вашим уровнем в этом классе: 1к8 на 9-м уровне, 1к10 на 13 уровне и 1к12 на 17 уровне.', 
      2),

    f('magical_inspiration',
      'Magical Inspiration',
      'Магическое вдохновение',
      'If a creature has a Bardic Inspiration die from you and casts a spell that restores hit points or deals damage, the creature can roll that die and choose a target affected by the spell. Add the number rolled as a bonus to the hit points regained or the damage dealt. The Bardic Inspiration die is then lost.',
      'Если существо, имея вашу кость бардовского вдохновения, накладывает заклинание, восстанавливающее хиты или наносящее урон, то это существо может бросить эту кость и выбрать цель, затронутую заклинанием. Добавьте выпавшее на кости значение в качестве бонуса к восстановлению хитов или урону. После этого кость бардовского вдохновения тратится.',
      2,
      'Add BI die to spell damage or healing.',
      'Добавить кость ВБ к урону или лечению заклинания.',
      'TCE'
    ),
    
    f('bard_college', 
      'Bard College', 
      'Коллегия бардов', 
      'At 3rd level, you delve into the advanced techniques of a bard college of your choice. Your choice grants you features at 3rd level and again at 6th and 14th level.', 
      'На 3-м уровне вы выбираете архетип, стиль и техники которого вы стремитесь перенять. Выбранный вами архетип даёт вам умения на 3-м, 7-м, 10-м, 15-м и 18-м уровнях.', 
      3),
    
    f('expertise_bard_1', 
      'Expertise', 
      'Компетентность', 
      'At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.\n\nAt 10th level, you can choose another two skill proficiencies to gain this benefit.', 
      'Выберите 2 навыка из тех, которыми вы владеете. Ваш бонус мастерства для этих навыков удваивается.\n\nНа 10-м уровне вы можете выбрать еще 2 навыка и получить для них это преимущество.', 
      3),

    f('ability_score_improvement_bard', 
      'Ability Score Improvement', 
      'Увеличение характеристик', 
      'When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can\'t increase an ability score above 20 using this feature.', 
      'При достижении 4-го, 8-го, 12-го, 16-го и 19-го уровней вы можете повысить значение одной из ваших характеристик на 2 или двух характеристик на 1. Как обычно, значение характеристики при этом не должно превышать 20.', 
      4),

    f('bardic_versatility', 
      'Bardic Versatility', 
      'Многогранность барда', 
      'Whenever you reach a level in this class that grants the Ability Score Improvement feature, you can do one of the following, representing a change in focus as you use your skills and magic:\n\n* Replace one of the skills you chose for the Expertise feature with one of your other skill proficiencies that isn\'t benefiting from Expertise.\n* Replace one cantrip you learned from this class\'s Spellcasting feature with another cantrip from the bard spell list.', 
      'Всякий раз, когда вы достигаете в этом классе уровня, который предоставляет вам «Увеличение характеристик», вы можете сделать одно из следующих действий, представляющих собой изменение вашей специализации на навыках и магии:\n\n* Замените один из навыков, выбранный вами с помощью умения «Компетентность», одним из ваших других навыков, который не имеет бонуса от этого умения.\n* Замените один заговор, который вы получили от умения «Использование заклинаний» этого класса, другим заговором из списка заклинаний барда.', 
      4,
      undefined,
      undefined,
      'TCE'
    ),
    
    f('font_of_inspiration', 
      'Font of Inspiration', 
      'Источник вдохновения', 
      'Beginning when you reach 5th level, you regain all of your expended uses of Bardic Inspiration when you finish a short or long rest.', 
      'Вы восстанавливаете истраченные вдохновения барда и после короткого, и после продолжительного отдыха.', 
      5),
    
    f('countercharm', 
      'Countercharm', 
      'Контрочарование', 
      'At 6th level, you gain the ability to use musical notes or words of power to disrupt mind-influencing effects. As an action, you can start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 30 feet of you have advantage on saving throws against being frightened or charmed. A creature must be able to hear you to gain this benefit. The performance ends early if you are incapacitated or silenced or if you voluntarily end it (no action required).', 
      'Вы получаете возможность использовать звуки или слова силы для разрушения воздействующих на разум эффектов. Вы можете действием начать исполнение, которое продлится до конца вашего следующего хода. В течение этого времени вы и все дружественные существа в пределах 30 футов от вас совершают спасброски от запугивания и очарования с преимуществом. Чтобы получить это преимущество, существа должны слышать вас. Исполнение заканчивается преждевременно, если вы оказываетесь недееспособны, теряете способность говорить, или прекращаете исполнение добровольно (на это не требуется действие).', 
      6),
    
    f('magical_secrets_1', 
      'Magical Secrets (Lvl 10)', 
      'Тайны магии (Ур 10)', 
      'By 10th level, you have plundered magical knowledge from a wide spectrum of disciplines. You choose two spells from any classes, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip. The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table.', 
      'Вы успели набрать знаний из самого широкого спектра магических дисциплин. Выберите два заклинания любых классов, включая ваш собственный. Выбранное заклинание должно быть того уровня, который вы можете использовать согласно таблице Бард, или являться заговором. Теперь эти заклинания считаются для вас заклинаниями барда и учитываются в общем количестве известных вам заклинаний согласно таблице «Бард».', 
      10),
    
    f('expertise_bard_2', 
      'Expertise (Lvl 10)', 
      'Компетентность (Ур 10)', 
      'At 10th level, you can choose another two skill proficiencies to gain this benefit.', 
      'На 10-м уровне вы можете выбрать еще 2 навыка и получить для них это преимущество.', 
      10),
    
    f('magical_secrets_2', 
      'Magical Secrets (Lvl 14)', 
      'Тайны магии (Ур 14)', 
      'At 14th level, you learn two additional spells from any class.', 
      'На 14-м уровне вы узнаёте ещё два дополнительных заклинания из списков любых классов.', 
      14),
    
    f('magical_secrets_3', 
      'Magical Secrets (Lvl 18)', 
      'Тайны магии (Ур 18)', 
      'At 18th level, you learn two additional spells from any class.', 
      'На 18-м уровне вы узнаёте ещё два дополнительных заклинания из списков любых классов.', 
      18),
    
    f('superior_inspiration', 
      'Superior Inspiration', 
      'Превосходное вдохновение', 
      'At 20th level, when you roll initiative and have no uses of Bardic Inspiration left, you regain one use.', 
      'Если на момент броска инициативы у вас не осталось неиспользованных вдохновений, вы получаете одно.', 
      20),
];

export const BARD: ClassData = { 
    id: 'bard', 
    name: { en: 'Bard', ru: 'Бард' }, 
    hitDie: 8, 
    primaryAbility: ['cha'], 
    savingThrows: ['dex', 'cha'], 
    skillsChoice: { count: 3, options: ['acrobatics', 'animal_handling', 'arcana', 'athletics', 'deception', 'history', 'insight', 'intimidation', 'investigation', 'medicine', 'nature', 'perception', 'performance', 'persuasion', 'religion', 'sleight_of_hand', 'stealth', 'survival'] }, 
    features: BARD_BASE, 
    spellcastingAbility: 'cha', 
    multiclassRequirements: [{ requirements: { cha: 13 } }],
    subclasses: [ 
        // 1. College of Lore (PHB)
        sc('lore', 'College of Lore', 'Коллегия Знаний', [
            f('bonus_proficiencies_lore', 
              'Bonus Proficiencies', 
              'Дополнительные навыки', 
              'When you join the College of Lore at 3rd level, you gain proficiency with three skills of your choice.', 
              'Если вы присоединяетесь к коллегии знаний, вы овладеваете тремя навыками на ваш выбор.', 
              3
            ),
            f('cutting_words', 
              'Cutting Words', 
              'Острое словцо', 
              'Also at 3rd level, you learn how to use your wit to distract, confuse, and otherwise sap the confidence and competence of others. When a creature that you can see within 60 feet of you makes an attack roll, an ability check, or a damage roll, you can use your reaction to expend one of your uses of Bardic Inspiration, rolling a Bardic Inspiration die and subtracting the number rolled from the creature\'s roll. You can choose to use this feature after the creature makes its roll, but before the DM determines whether the attack roll or ability check succeeds or fails, or before the creature deals its damage. The creature is immune if it can\'t hear you or if it\'s immune to being charmed.', 
              'Вы узнаёте, как использовать собственное остроумие, чтобы отвлечь, смутить или по-другому подорвать способности и уверенность противников. Если существо, которое вы можете видеть, в пределах 60 футов от вас совершает бросок атаки, урона или проверку характеристики, вы можете реакцией потратить одну из ваших костей бардовского вдохновения, и вычесть результат броска этой кости из броска этого существа. Вы можете принять решение об использовании этого умения после броска существа, но до того момента, когда Мастер объявит результат броска или проверки. Существо не подвержено этому умению, если не может слышать вас, или обладает иммунитетом к очарованию.', 
              3,
              'Use reaction to subtract Bardic Inspiration die from creature\'s roll.',
              'Используйте реакцию, чтобы вычесть кость бардовского вдохновения из броска существа.'
            ),
            f('additional_magical_secrets', 
              'Additional Magical Secrets', 
              'Дополнительные тайны магии', 
              'At 6th level, you learn two spells of your choice from any class. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip. The chosen spells count as bard spells for you but don\'t count against the number of bard spells you know.', 
              'Вы можете выучить 2 заклинания из доступных любому классу на свой выбор. Их уровень не должен превышать уровня заклинаний, которые вы можете использовать на этом уровне, как показано в таблице Барда. Они также могут быть заговорами. Выбранные заклинания теперь считаются для вас заклинаниями барда, но они не учитываются в общем количестве известных вам заклинаний барда.', 
              6
            ),
            f('peerless_skill', 
              'Peerless Skill', 
              'Непревзойдённый навык', 
              'Starting at 14th level, when you make an ability check, you can expend one use of Bardic Inspiration. Roll a Bardic Inspiration die and add the number rolled to your ability check. You can choose to do so after you roll the die for the ability check, but before the DM tells you whether you succeed or fail.', 
              'Если вы совершаете проверку характеристики, вы можете бросить кость бардовского вдохновения и добавить результат к проверке. Вы можете принять решение об использовании этого умения после броска проверки, но до того, как Мастер объявит результат этой проверки.', 
              14
            )
        ]),

        // 2. College of Valor (PHB)
        sc('valor', 'College of Valor', 'Коллегия Доблести', [
            f('bonus_proficiencies_valor', 
              'Bonus Proficiencies', 
              'Дополнительные навыки', 
              'When you join the College of Valor at 3rd level, you gain proficiency with medium armor, shields, and martial weapons.', 
              'Присоединяясь к коллегии доблести, вы получаете владение средними доспехами, щитами и воинским оружием.', 
              3),
            f('combat_inspiration', 
              'Combat Inspiration', 
              'Боевое вдохновение', 
              'Also at 3rd level, you learn to inspire others in battle. A creature that has a Bardic Inspiration die from you can roll that die and add the number rolled to a weapon damage roll it just made. Alternatively, when an attack roll is made against the creature, it can use its reaction to roll the Bardic Inspiration die and add the number rolled to its AC against that attack, after seeing the roll but before knowing whether it hits or misses.', 
              'Вы узнаёте, как вдохновлять других в бою. Существо, получившее от вас кость бардовского вдохновения, может бросить эту кость и добавить результат к своему броску урона оружием. В качестве альтернативы, если существо атаковано, оно может реакцией совершить бросок кости вдохновения и добавить результат к своему КД от этой атаки. Оно может сделать это после броска атаки, но до того, как узнает, попали ли по нему.', 
              3,
              'Creature with your Inspiration die can add it to weapon damage or use reaction to add it to AC against an attack.',
              'Кость вдохновения можно добавить к урону оружием или к Классу Доспеха против одной атаки (реакцией).'),
            f('extra_attack_bard', 
              'Extra Attack', 
              'Дополнительная атака', 
              'Starting at 6th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.', 
              'Если вы в свой ход совершаете действие Атака, вы можете совершить две атаки вместо одной.', 
              6),
            f('battle_magic', 
              'Battle Magic', 
              'Боевая магия', 
              'At 14th level, you have mastered the art of weaving spellcasting and weapon use into a single harmonious act. When you use your action to cast a bard spell, you can make one weapon attack as a bonus action.', 
              'Вы научились сплетать использование заклинаний и оружия в одно гармоничное действие. Если вы действием используете заклинание барда, вы можете бонусным действием совершить одну атаку оружием.', 
              14,
              'When you use your action to cast a bard spell, you can make one weapon attack as a bonus action.',
              'Если вы действием используете заклинание барда, вы можете бонусным действием совершить одну атаку оружием.')
        ], 'PHB',
        'Bards of the College of Valor are daring skalds whose tales keep alive the memory of the great heroes of the past, and thereby inspire a new generation of heroes. These bards gather in mead halls or around campfires to sing the deeds of the mighty, both past and present. They travel the land to witness great events firsthand and to ensure that the memory of those events doesn\'t pass from the world. With their songs, they inspire others to reach the same heights of accomplishment as the heroes of old.',
        'Барды коллегии доблести это отважные скальды, чьи сказания не дают забыть великих героев прошлого и вдохновляют на подвиги нынешних героев. Такие барды собираются в медовых залах или вокруг походных костров, чтоб воспеть великие свершения прошлого и настоящего. Они путешествуют, чтобы стать очевидцами великих событий, и не дать памяти о них угаснуть. Своими песнями они вдохновляют на достижения, достойные памяти предков.'),

        // 3. College of Glamour (XGtE)
        sc('glamour', 'College of Glamour', 'Коллегия Очарования', [
            f('mantle_of_inspiration', 
              'Mantle of Inspiration', 
              'Мантия вдохновения', 
              'When you join the College of Glamour at 3rd level, you gain the ability to weave a song of fey magic that imbues your allies with vigor and speed.\n\nAs a bonus action, you can expend one use of your Bardic Inspiration to grant yourself a wondrous appearance. When you do so, choose a number of creatures you can see and that can see you within 60 feet of you, up to a number equal to your Charisma modifier (minimum of one). Each of them gains 5 temporary hit points. When a creature gains these temporary hit points, it can immediately use its reaction to move up to its speed, without provoking opportunity attacks.\n\nThe number of temporary hit points increases when you reach certain levels in this class: to 8 at 5th level, 11 at 10th level, and 14 at 15th level.', 
              'Вступая в коллегию очарования на 3-м уровне, вы получаете возможность слагать песни, сплетённые с чарами фей, которые наполняют ваших союзников отвагой и проворством.\n\nВы можете бонусным действием потратить одно использование своего «Вдохновения барда», чтобы придать себе поразительный внеземной облик. Когда вы делаете это, выберите несколько союзников, которых вы можете видеть, и которые могут видеть вас в пределах 60 футов от вас. Количество выбранных целей не должно превышать ваш модификатор Харизмы (минимум 1). Каждая выбранная цель получает 5 временных хитов. Когда цель получает временные хиты от этого умения, она также немедленно может реакцией переместиться на расстояние, не превышающее своей скорости, не вызывая провоцированных атак.\n\nКоличество временных хитов увеличивается, когда вы достигаете определенных уровней в этом классе: до 8 на 5-м уровне, 11 на 10-м уровне и 14 на 15-м уровне.', 
              3,
              'As a bonus action, spend one Bardic Inspiration die to grant temporary hit points to allies. They can use their reaction to move up to their speed without provoking opportunity attacks.',
              'Бонусным действием потратьте кость бардовского вдохновения, чтобы дать временные хиты союзникам. Они могут реакцией переместиться на свою скорость, не вызывая провоцированных атак.'
              ),
            f('enthralling_performance', 
              'Enthralling Performance', 
              'Завораживающее выступление', 
              'Starting at 3rd level, you can charge your performance with seductive, fey magic.\n\nIf you perform for at least 1 minute, you can attempt to inspire wonder in your audience by singing, reciting a poem, or dancing. At the end of the performance, choose a number of humanoids within 60 feet of you who watched and listened to all of it, up to a number equal to your Charisma modifier (minimum of one). Each target must succeed on a Wisdom saving throw against your spell save DC or be charmed by you. While charmed in this way, the target idolizes you, it speaks glowingly of you to anyone who speaks to it, and it hinders anyone who opposes you, avoiding violence unless it was already inclined to fight on your behalf. This effect ends on a target after 1 hour, if it takes any damage, if you attack it, or if it witnesses you attacking or damaging any of its allies.\n\nIf a target succeeds on its saving throw, the target has no hint that you tried to charm it.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.', 
              'Начиная с 3-го уровня, вы можете наполнить свое выступление притягательными чарами фей.\n\nЕсли вы выступаете как минимум в течение 1 минуты, то можете попытаться очаровать слушателей своим пением, чтением стихотворения или танцем. В конце выступления выберите такое число Гуманоидов в пределах 60 футов от вас, которые смотрели и слушали все выступление, количество которых не превышает ваш модификатор Харизмы (минимум 1). Каждая цель должна преуспеть в спасброске Мудрости против Сл спасброска от ваших заклинаний, иначе будет очарована вами. Очарованные таким образом существа боготворят вас и говорят о вас крайне восторженно с любым заговорившим с ними. Они мешают вашим недругам, хотя при этом избегают насилия, если только к этому моменту уже и так не были настроены драться за вас. Эффект на цели заканчивается через 1 час, если цель получает любой урон, если вы атакуете её или если она замечает, как вы атакуете или наносите урон кому-то из её союзников.\n\nЕсли цель преуспевает в спасброске, то она не замечает никаких признаков того, что вы пытались её очаровать.\n\nИспользовав это умение, вы не можете использовать его повторно до окончания короткого или продолжительного отдыха.', 
              3,
              'Perform for 1 minute to charm humanoids. They idolize you and hinder your enemies. Effect lasts 1 hour. Ends if they take damage, you attack them, or they see you attack their allies.',
              'Выступайте 1 минуту, чтобы очаровать гуманоидов. Они боготворят вас и мешают врагам. Длится 1 час. Спадет при уроне, вашей атаке или если увидят вашу атаку по их союзникам.'
              ),
            f('mantle_of_majesty', 
              'Mantle of Majesty', 
              'Мантия величия', 
              'At 6th level, you gain the ability to cloak yourself in a fey magic that makes others want to serve you.\n\nAs a bonus action, you cast Command, without expending a spell slot, and you take on an appearance of unearthly beauty for 1 minute or until your concentration ends (as if you were concentrating on a spell). During this time, you can cast Command as a bonus action on each of your turns, without expending a spell slot.\n\nAny creature charmed by you automatically fails its saving throw against the Command you cast with this feature.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.', 
              'На 6-м уровне вы получаете возможность укутаться в чары фей, заставляющие других хотеть служить вам.\n\nБонусным действием вы можете сотворить заклинание приказ [command] без траты ячейки заклинания и принимаете облик неземной красоты на 1 минуту или до тех пор, пока не завершится ваша концентрация (как если бы вы концентрировались на заклинании). В течение этого времени вы можете накладывать заклинание приказ [command] бонусным действием в каждый свой ход, не тратя ячейку заклинания.\n\nЛюбое существо, очарованное вами, автоматически проваливает спасбросок против заклинания приказ [command], которое вы накладываете с помощью этого умения.\n\nИспользовав это умение, вы не можете использовать его повторно до окончания продолжительного отдыха.', 
              6,
              'As a bonus action, cast Command without a spell slot. For 1 minute, you can cast Command as a bonus action on each of your turns without expending a spell slot.',
              'Бонусным действием наложите Приказ без ячейки. В течение 1 минуты вы можете накладывать Приказ бонусным действием в каждый свой ход, не тратя ячейку заклинания.'
              ),
            f('unbreakable_majesty', 
              'Unbreakable Majesty', 
              'Несокрушимое величие', 
              'At 14th level, your appearance permanently gains an otherworldly aspect that makes you look more lovely and fierce.\n\nIn addition, as a bonus action, you can assume a magically majestic presence for 1 minute or until you are incapacitated. For the duration, whenever any creature attacks you for the first time on a turn, the attacker must make a Charisma saving throw against your spell save DC. On a failed save, it can\'t attack you on this turn, and it must choose a new target for its attack or the attack is wasted. If a creature succeeds on its saving throw, it can attack you on this turn, but it has disadvantage on any saving throw it makes against your spells on your next turn.\n\nOnce you assume this majestic presence, you can\'t do so again until you finish a short or long rest.', 
              'На 14-м уровне ваша внешность приобретает потусторонние черты, заставляя вас выглядеть горячим и прекрасным.\n\nКроме того, вы можете бонусным действием принять магически величественный вид на 1 минуту или пока вы не станете недееспособны. В течение этого времени, когда существо пытается атаковать вас в первый раз за ход, атакующий должен сделать спасбросок Харизмы против вашей Сл спасброска от ваших заклинаний. При провале оно не может атаковать вас в этот ход и должно выбрать новую цель для атаки, иначе атака будет потрачена зря. При успехе оно может атаковать вас в этот ход, но будет совершать с помехой спасброски против ваших заклинаний в ваш следующий ход.\n\nПриняв этот величественный вид, вы не можете использовать его повторно до окончания короткого или продолжительного отдыха.', 
              14,
              'As a bonus action, assume a majestic presence for 1 minute. Attackers must make a Charisma saving throw. On a failure, they cannot attack you. On a success, they have disadvantage on saving throws against your spells.',
              'Бонусным действием примите величественный вид на 1 минуту. Атакующие делают спасбросок Харизмы. При провале они не могут атаковать вас. При успехе у них помеха на спасброски против ваших заклинаний.'
              )
        ], 'XGE',
        'The College of Glamour is the home of bards who mastered their craft in the vibrant realm of the Feywild or under the tutelage of someone who dwelled there. Tutored by satyrs, eladrin, and other fey, these bards learn to use their magic to delight and captivate others.',
        'Коллегия Очарования является домом для тех бардов, чьё мастерство было взращено в Стране Фей или под руководством того, кто проживал там. Обученные сатирами, эладринами и другими фейскими существами, эти барды учатся использовать свою магию, чтобы восхищать и очаровывать окружающих.'),

        // 4. College of Swords (XGtE)
        sc('swords', 'College of Swords', 'Коллегия Мечей', [
            f('bonus_proficiencies_swords', 
              'Bonus Proficiencies', 
              'Дополнительные владения', 
              'When you join the College of Swords at 3rd level, you gain proficiency with medium armor and the scimitar. If you\'re proficient with a simple or martial melee weapon, you can use it as a spellcasting focus for your bard spells.', 
              'Когда вы вступаете в Коллегию Мечей на 3-м уровне, вы получают владение средними доспехами и скимитарами. Если вы владеете простым или воинским оружием ближнего боя, то можете использовать его в качестве фокусировки для ваших заклинаний барда.', 
              3),
            f('fighting_style_swords', 
              'Fighting Style', 
              'Боевой стиль', 
              'At 3rd level, you adopt a style of fighting as your specialty. Choose one of the following options: Dueling or Two-Weapon Fighting.', 
              'На 3-м уровне вы выбираете боевой стиль, соответствующий вашей специализации. Выберите один из следующих вариантов: Дуэлянт или Сражение двумя оружиями.', 
              3),
            f('blade_flourish', 
              'Blade Flourish', 
              'Росчерк клинка', 
              'At 3rd level, you learn to perform impressive displays of martial prowess and speed. Whenever you take the Attack action on your turn, your walking speed increases by 10 feet until the end of the turn, and if a weapon attack that you make as part of this action hits a creature, you can use one of the following Blade Flourish options of your choice. You can use only one Blade Flourish option per turn.\n\n**Defensive Flourish.** You can expend one use of your Bardic Inspiration to cause the weapon to deal extra damage to the target you hit. The damage equals the number you roll on the Bardic Inspiration die. You also add the number rolled to your AC until the start of your next turn.\n\n**Slashing Flourish.** You can expend one use of your Bardic Inspiration to cause the weapon to deal extra damage to the target you hit and to any other creature of your choice that you can see within 5 feet of you. The damage equals the number you roll on the Bardic Inspiration die.\n\n**Mobile Flourish.** You can expend one use of your Bardic Inspiration to cause the weapon to deal extra damage to the target you hit. The damage equals the number you roll on the Bardic Inspiration die. You can also push the target up to 5 feet away from you, plus a number of feet equal to the number you roll on that die. You can then immediately use your reaction to move up to your walking speed to an unoccupied space within 5 feet of the target.', 
              'На 3-м уровне вы учитесь исполнять впечатляющие демонстрации боевого мастерства и проворства. Когда вы совершаете действие Атака в свой ход, ваша скорость ходьбы увеличивается на 10 футов до конца хода, а если атака оружием, которую вы совершаете частью этого действия, попадает по существу, вы можете использовать один из вариантов «Росчерка клинка» по своему выбору. Вы можете использовать только один вариант за ход.\n\n**Оборонительный росчерк.** Вы можете потратить одно «Вдохновение барда», чтобы нанести дополнительный урон цели. Урон равен числу, выпавшему на кости вдохновения. Вы также добавляете это число к своему Классу Доспеха до начала вашего следующего хода.\n\n**Режущий росчерк.** Вы можете потратить одно «Вдохновение барда», чтобы нанести дополнительный урон цели и любому другому существу по вашему выбору, которое вы видите в 5 футах от себя. Урон равен числу, выпавшему на кости вдохновения.\n\n**Мобильный росчерк.** Вы можете потратить одно «Вдохновение барда», чтобы нанести дополнительный урон цели. Урон равен числу, выпавшему на кости вдохновения. Вы также можете оттолкнуть цель на 5 футов от себя плюс количество футов, выпавшее на кости. После этого вы можете реакцией переместиться на расстояние своей скорости в незанятое место в 5 футах от цели.', 
              3,
              'Attack action increases speed by 10 ft. On hit, spend Bardic Inspiration for extra damage and effect: boost AC, push and move, or damage adjacent target.',
              'При действии Атака скорость растет на 10 футов. При попадании можно потратить Вдохновение для дополнительного урона и эффекта: защита, толчок с перемещением или урон по соседней цели.'),
            f('extra_attack_bard', 
              'Extra Attack', 
              'Дополнительная атака', 
              'Starting at 6th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.', 
              'Начиная с 6-го уровня, если вы в свой ход совершаете действие Атака, вы можете совершить две атаки вместо одной.', 
              6),
            f('master_flourish', 
              'Master\'s Flourish', 
              'Мастерский Росчерк', 
              'Starting at 14th level, whenever you use a Blade Flourish option, you can roll a d6 and use it instead of expending a Bardic Inspiration die.', 
              'Начиная с 14-го уровня, когда вы используете вариант «Росчерка клинка», вы можете совершить бросок к6 и использовать его вместо траты кости бардовского вдохновения.', 
              14)
        ], 'XGE',
        'Bards of the College of Swords are called blades, and they entertain through daring feats of weapon prowess. Blade performers perform stunts such as sword swallowing, knife throwing and juggling, and mock combats. Though they use their weapons for entertainment, they are also highly trained and skilled warriors in their own right.',
        'Барды Коллегии Мечей называют клинками, и они выступают на публике, выказывая свое мастерство обращения с оружием. Клинки выполняют такие трюки как шпагоглотание, метание и жонглирование кинжалами и демонстрационные бои. Хоть они и используют свое оружие для развлечения, они хорошо натренированные и умелые бойцы.'),

        // 5. College of Whispers (XGtE)
        sc('whispers', 'College of Whispers', 'Коллегия Шёпотов', [
            f('psychic_blades_whispers',
              'Psychic Blades',
              'Психические клинки',
              'When you join the College of Whispers at 3rd level, you have the ability to make your weapon attacks magically toxic to a creature\'s mind. When you hit a creature with a weapon attack, you can expend one use of your Bardic Inspiration to deal an extra 2d6 psychic damage to that target. You can do so only once per round on your turn.\n\nThe psychic damage increases when you reach certain levels in this class, increasing to 3d6 at 5th level, 5d6 at 10th level, and 8d6 at 15th level.',
              'При вступлении в коллегию шёпотов вы получаете возможность сделать свою атаку оружием магически токсичной для разума существа. Когда вы попадаете по существу атакой оружием, вы можете потратить одно «Вдохновение барда» и нанести цели дополнительные 2к6 урона психической энергией. Вы можете использовать это умение один раз за раунд в свой ход.\n\nУрон психической энергией увеличивается, когда вы получаете определенный уровень в этом классе, увеличиваясь до 3к6 на 5-м уровне, 5к6 на 10-м уровне и 8к6 на 15-м уровне.',
              3,
              'When you hit a creature with a weapon attack, expend one Bardic Inspiration to deal extra psychic damage (2d6/3d6/5d6/8d6). Once per round.',
              'При попадании атакой оружием, потратьте Вдохновение барда, чтобы нанести доп. урон психической энергией (2к6/3к6/5к6/8к6). Раз в раунд.'
            ),
            f('words_of_terror',
              'Words of Terror',
              'Слова ужаса',
              'At 3rd level, you learn to infuse innocent-seeming words with an insidious magic that can inspire terror. If you speak to a humanoid alone for at least 1 minute, you can attempt to seed paranoia in its mind. At the end of the conversation, the target must succeed on a Wisdom saving throw against your spell save DC or be frightened of you or another creature of your choice. The target is frightened in this way for 1 hour, until it is attacked or damaged, or until it witnesses its allies being attacked or damaged. If the target succeeds on its saving throw, the target has no hint that you tried to frighten it.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.',
              'Вы учитесь наполнять кажущиеся безобидными слова коварной магией, которая вызывает ужас. Если вы разговариваете с Гуманоидом наедине, в течение по крайней мере 1 минуты, то можете попытаться посеять семя паранойи в его разуме.\n\nВ конце беседы цель должна преуспеть в спасброске Мудрости против вашей Сл спасброска от ваших заклинаний, иначе будет напугана вами или другим существом по вашему выбору. Цель напугана на 1 час таким образом, пока не будет атакована или не получит урон, или пока она не заметит, что её союзники атакованы или получили урон. Если цель преуспевает в спасброске, то она не замечает никаких признаков того, что вы пытались ее испугать.\n\nИспользовав это умение, вы не можете использовать его повторно до окончания короткого или продолжительного отдыха.',
              3,
              'Speak to humanoid alone for 1 minute. Wisdom save or be Frightened (1 hour).',
              'Разговор с гуманоидом 1 минуту. Спас Мудрости или испуган (1 час).'
            ),
            f('mantle_of_whispers',
              'Mantle of Whispers',
              'Мантия шёпотов',
              'At 6th level, you gain the ability to adopt a humanoid\'s persona. When a humanoid dies within 30 feet of you, you can use your reaction to capture its shadow using your reaction. You can capture only one shadow at a time. You can use your action to adopt the dead humanoid\'s persona. For 1 hour, you magically become the creature\'s double, gaining access to information that the humanoid would freely share with a casual acquaintance. Another creature can see through this disguise with a successful Wisdom (Insight) check contested by your Charisma (Deception) check, but you gain a +5 bonus to your check.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.',
              'Вы получаете возможность принимать личность Гуманоида. Когда Гуманоид умирает в пределах 30 футов от вас, вы можете реакцией магическим образом поймать его тень. Вы удерживаете эту тень, пока не используете её, или до окончания короткого или продолжительного отдыха.\n\nДействием вы можете использовать тень. Когда вы это делаете, она исчезает, магически превращаясь в маскировку, которая появляется на вас. Теперь вы выглядите как этот мёртвый Гуманоид, но кажетесь живым и здоровым. Маскировка длится 1 час или пока вы не закончите её бонусным действием. Находясь под этой маскировкой, вы получаете доступ ко всей информации, которой это существо могло бы свободно поделиться со случайным знакомым. Другие существа могут обнаружить вашу истинную сущность, в состязании их Мудрости (Проницательность) против вашей Харизмы (Обман), при этом вы получаете бонус +5 к своей проверке.\n\nКогда вы ловите тень этим умением, вы не можете поймать другую тень, до окончания короткого или продолжительного отдыха.',
              6,
              'Reaction: Capture shadow of dying humanoid. Action: Become perfect disguise (1 hr). +5 Deception.',
              'Реакция: Поймать тень. Действие: Маскировка под умершего (1 час). +5 Обман.'
            ),
            f('shadow_lore',
              'Shadow Lore',
              'Знание тени',
              'At 14th level, you gain the ability to weave dark magic into your words and tap into a creature\'s deepest fears. As an action, you magically whisper a phrase that only one creature of your choice within 30 feet of you can hear. The target must make a Wisdom saving throw against your spell save DC. It automatically succeeds if it doesn\'t share a language with you or if it can\'t hear you. On a successful save, your whisper sounds like unintelligible mumbling and has no effect.\n\nOn a failed save, the target is charmed by you for the next 8 hours or until you or your allies attack it, damage it, or force it to make a saving throw. It interprets the whispers as a description of its most mortifying secret. While charmed, the creature obeys your commands for fear that you will reveal its secret. It won\'t risk its life for you or fight for you, unless it was already inclined to do so.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.',
              'Вы получаете способность вплетать в свою речь тёмную магию и дергать за ниточки самых глубоких страхов существа.\nДействием, вы магическим образом нашёптываете фразу, которую слышит только одно существо по вашему выбору в пределах 30 футов от вас. Цель должна совершить спасбросок Мудрости против Сл спасброска от ваших заклинаний. Цель автоматически преуспевает в броске, если она не разговаривает с вами хотя бы на одном общем языке, или не может слышать вас. В случае успеха, ваш шёпот звучит как неразборчивое бормотание и не имеет никакого эффекта.\n\nЕсли цель проваливает спасбросок, то она попадает под ваше очарование на следующие 8 часов или пока вы или ваши союзники не атакуют ее, не причинят ей вред или не заставят сделать спасбросок. Цель интерпретирует шёпот как описание самого страшного её секрета. Хотя вы не узнаете этой тайны, цель убеждена в том, что вы знаете её.\n\nОчарованное таким образом существо подчиняется вашим командам из страха, что вы раскроете его тайну. Оно не будет рисковать своей жизнью ради вас или сражаться за вас, если уже не было склонно делать это.\n\nИспользовав это умение, вы не можете использовать его повторно до окончания короткого или продолжительного отдыха.',
              14,
              'Action: Charm creature (8 hrs). It obeys commands, fearing you know its secret.',
              'Действие: Очаровать существо (8 часов). Подчиняется, боясь, что вы знаете тайну.'
            )
        ], 'XGE',
        'Most folk are happy to welcome a bard into their midst. The representatives of the College of Whispers use this to their advantage. They appear to be like other bards, sharing news, singing songs, and telling tales to the audiences they gather. In truth, the College of Whispers teaches its students that they are wolves among sheep. These bards use their knowledge and magic to uncover secrets and turn them against others through extortion and threats.',
        'Все рады приветствовать бардов в своём обществе, и представители Коллегии Шёпотов используют это в своих интересах. Они с виду подобны всем прочим бардам: делятся новостями, поют песни и рассказывают истории своей аудитории. На самом же деле коллегия шёпотов учит своих последователей, что они должны быть подобны волкам среди овец. Эти барды используют свои знания и магию, чтобы раскрывать чужие тайны и оборачивать их против других через шантаж и угрозы.'),

        // 6. College of Eloquence (TCoE)
        sc('eloquence', 'College of Eloquence', 'Коллегия Красноречия', [
            f('silver_tongue', 
              'Silver Tongue', 
              'Златоуст', 
              'You are a master at saying the right thing at the right time. When you make a Charisma (Persuasion) or Charisma (Deception) check, you can treat a d20 roll of 9 or lower as a 10.', 
              'Вы мастер говорить нужные вещи в нужное время. Когда вы совершаете проверку Харизмы (Убеждение или Обман), вы можете при выпадении на к20 результата «1–9» считать, что выпало «10».', 
              3),
            f('unsettling_words', 
              'Unsettling Words', 
              'Тревожащие слова', 
              'You can spin words that unsettle a creature and cause it to doubt itself. As a bonus action, you can expend one use of your Bardic Inspiration and choose one creature you can see within 60 feet of you. Roll the Bardic Inspiration die. The creature must subtract the number rolled from the next saving throw it makes before the start of your next turn.', 
              'Вместе с магией вы можете сплетать слова, которые выбивают существо из колеи и заставляют его сомневаться в себе. Бонусным действием вы можете потратить одно использование «Вдохновения барда» и выбрать существо, которое вы можете видеть в пределах 60 футов от вас. Совершите бросок кости бардовского вдохновения. Существо должно вычесть выпавший результат из следующего спасброска, который оно совершит до начала вашего следующего хода.', 
              3,
              'Bonus Action: Expend a use of Bardic Inspiration to choose a creature within 60 feet. It subtracts the number rolled from its next saving throw.',
              'Бонусным действием потратьте использование Вдохновения барда. Выберите существо в пределах 60 футов. Оно вычитает результат броска из следующего спасброска.'
            ),
            f('unfailing_inspiration', 
              'Unfailing Inspiration', 
              'Неисчерпаемое вдохновение', 
              'Your inspiring words are so persuasive that others feel driven to succeed. When a creature adds one of your Bardic Inspiration dice to its ability check, attack roll, or saving throw and the roll fails, the creature can keep the Bardic Inspiration die.', 
              'Ваши вдохновляющие слова настолько убедительны, что другие чувствуют стремление к успеху. Когда существо добавляет вашу кость бардовского вдохновения к проверке характеристики, броску атаки или спасброску, но бросок оказывается провален, то существо не теряет кость бардовского вдохновения.', 
              6),
            f('universal_speech', 
              'Universal Speech', 
              'Универсальная речь', 
              'You have gained the ability to make your speech intelligible to any creature. As an action, choose one or more creatures within 60 feet of you, up to a number equal to your Charisma modifier (minimum of one creature). The chosen creatures can magically understand you, regardless of the language you speak, for 1 hour.\n\nOnce you use this feature, you can\'t use it again until you finish a long rest, unless you expend a spell slot to use it again.', 
              'Вы приобретаете способность сделать свою речь понятной любому существу. Действием выберите одно или несколько существ в радиусе 60 футов от вас, количество которых не превышает ваш модификатор Харизмы (минимум одно существо). Выбранные существа могут в течение 1 часа магическим образом понимать вас независимо от языка, на котором вы говорите.\n\nКак только вы воспользуетесь этим умением, вы не можете использовать его снова, пока не закончите продолжительный отдых или не израсходуете ячейку заклинания любого уровня, чтобы использовать его снова.', 
              6,
              'Action: Choose creatures within 60 feet. They can magically understand you for 1 hour regardless of language. Recharges on long rest or spell slot expenditure.',
              'Действием выберите существ в радиусе 60 футов. Они магически понимают вас 1 час. Восстанавливается после долгого отдыха или за ячейку заклинания.'
            ),
            f('infectious_inspiration', 
              'Infectious Inspiration', 
              'Заразительное вдохновение', 
              'When you successfully inspire someone, the power of your eloquence spreads to someone else. When a creature within 60 feet of you adds one of your Bardic Inspiration dice to its ability check, attack roll, or saving throw and the roll succeeds, you can use your reaction to encourage a different creature (other than yourself) that can hear you within 60 feet of you, giving it a Bardic Inspiration die without expending any of your Bardic Inspiration uses.\n\nYou can use this reaction a number of times equal to your Charisma modifier (minimum of once), and you regain all expended uses when you finish a long rest.', 
              'Когда вы успешно вдохновляете кого-то, сила вашего красноречия может распространиться на кого-то другого. Когда существо в пределах 60 футов от вас добавляет вашу кость бардовского вдохновения к проверке характеристики, броску атаки или спасброску и бросок оканчивается успехом, вы можете реакцией дать кость бардовского вдохновения другому существу слышащему вас (кроме вас) в пределах 60 футов от вас, не уменьшая ваше количество применений умения «Вдохновение барда».\n\nВы можете использовать эту реакцию количество раз, равное вашему модификатору Харизмы (минимум один раз). Все потраченные использования восстанавливаются после окончания продолжительного отдыха.', 
              14,
              'Reaction: When an ally succeeds on a roll using your Bardic Inspiration, you can give another ally a Bardic Inspiration die without expending a use.',
              'Реакция: Когда союзник успешно использует ваше Вдохновение, вы можете дать другому союзнику кость Вдохновения без затрат.'
            )
        ], 'TCE',
        'Adherents of the College of Eloquence master the art of oratory. These bards wield a blend of logic and theatrical wordplay, winning over skeptics and detractors with logical arguments and plucking at heartstrings to appeal to the emotions of audiences.',
        'Приверженцы коллегии красноречия посвящают себя ораторскому искусству. Эти барды владеют смесью логики и театральных приёмов, переубеждая скептиков и недоброжелателей логическими аргументами, в то же время обращаясь к сердцам, чтобы войти в эмоциональное доверие аудитории.'),

        // 7. College of Creation (TCoE)
        sc('creation', 'College of Creation', 'Коллегия Созидания', [
            f('mote_of_potential', 
              'Mote of Potential', 
              'Частица потенциала', 
              'Whenever you give a creature a Bardic Inspiration die, you can utter a note from the Song of Creation to create a Tiny mote of potential, which orbits within 5 feet of that creature. The mote is intangible and invulnerable, and it lasts until the Bardic Inspiration die is lost. The mote looks like a musical note, a star, a flower, or another symbol of art or life that you choose. When the creature uses the Bardic Inspiration die, the mote provides an additional effect based on whether the die benefits an ability check, an attack roll, or a saving throw, as detailed below:\n* **Ability Check.** When the creature rolls the Bardic Inspiration die to add it to an ability check, the mote vanishes in a flash of color, and the creature can roll the Bardic Inspiration die again and choose which roll to use.\n* **Attack Roll.** Immediately after the creature rolls the Bardic Inspiration die to add it to an attack roll against a target, the mote shatters thunderously. The target and each creature of your choice that you can see within 5 feet of it must succeed on a Constitution saving throw against your spell save DC or take thunder damage equal to the number rolled on the Bardic Inspiration die.\n* **Saving Throw.** Immediately after the creature rolls the Bardic Inspiration die to add it to a saving throw, the mote vanishes with the sound of soft music, causing the creature to gain temporary hit points equal to the number rolled on the Bardic Inspiration die plus your Charisma modifier (minimum of 1 temporary hit point).', 
              'Всякий раз, когда вы даете существу кость бардовского вдохновения, вы можете произнести ноту из Песни Созидания, чтобы создать Крошечную частицу потенциала, которая будет вращаться вокруг существа на расстоянии 5 футов. Частица неосязаема и неуязвима, и она не исчезнет, пока кость бардовского вдохновения не будет потрачена. Частица выглядит как музыкальная нота, звезда, цветок или другой символ искусства или жизни, который вы выбираете.\n\nКогда существо использует кость бардовского вдохновения, частица создает дополнительный эффект, основанный на том, приносит ли кость пользу проверке характеристики, броску атаки или спасброску, как сказано ниже:\n\n* **Проверка характеристики.** Когда существо бросает кость бардовского вдохновения, чтобы добавить его к проверке характеристики, частица проявляется и на мгновение испускает красочные, безвредные искры, а существо может снова бросить кость бардовского вдохновения и выбрать, какой результат использовать.\n* **Бросок атаки.** Сразу же после того, как существо бросает кость бардовского вдохновения, чтобы добавить её к броску атаки против цели, частица с грохотом разбивается. Цель и каждое существо по вашему выбору, которое вы можете видеть в пределах 5 футов от неё, должны преуспеть в спасброске Телосложения против Сл ваших заклинаний, иначе получат урон звуком, равный значению, выпавшему на кости бардовского вдохновения.\n* **Спасбросок.** Сразу же после того, как существо бросает кость бардовского вдохновения и добавляет её к спасброску, частица исчезает со звуками мягкой музыки, в результате чего существо получает количество временных хитов, равное значению, выпавшему на кости бардовского вдохновения, плюс ваш модификатор Харизмы (минимум 1 временный хит).', 
              3,
              'Bardic Inspiration grants extra benefits based on roll type. Ability Check: Roll die twice, choose result. Attack Roll: Target and each creature within 5 ft take thunder damage equal to the number rolled (Con save negates). Saving Throw: Creature gains temp HP equal to the number rolled + your Cha modifier.',
              'Вдохновение барда дает доп. эффекты в зависимости от типа броска. Проверка хар-ки: Бросьте кость дважды и выберите результат. Атака: Цель и существа в 5 фт получают урон звуком, равный результату (Спас Тел). Спасбросок: Существо получает Врем. ХП, равные результату + мод. Хар.'
            ),
            f('performance_of_creation', 
              'Performance of Creation', 
              'Созидательное выступление', 
              'As an action, you can channel the magic of the Song of Creation to create one nonmagical item of your choice in an unoccupied space within 10 feet of you. The item must appear on a surface or in a liquid that can support it. The gp value of the item can\'t be more than 20 times your bard level, and the item must be Medium or smaller. The item glimmers softly, and a creature can faintly hear music when touching it. The created item disappears after a number of hours equal to your proficiency bonus. For examples of items you can create, see the equipment chapter of the Player\'s Handbook. Once you create an item with this feature, you can\'t do so again until you finish a long rest, unless you expend a spell slot of 2nd level or higher to use this feature again. You can have only one item created by this feature at a time; if you use this action and already have an item from this feature, the first one immediately vanishes. The size of the item you can create with this feature increases by one category when you reach 6th level (Large) and 14th level (Huge).', 
              'Действием вы можете направить магию Песни Созидания для создания одного немагического предмета по вашему выбору в свободном пространстве в пределах 10 футов от вас. Предмет должен находиться на поверхности или в жидкости, которая может поддерживать его на плаву. Стоимость предмета в зм не может быть более чем в 20 раз больше вашего уровня барда, а размер должен быть Средним или меньше. Предмет слегка мерцает, а коснувшись его, можно услышать слабую музыку. Созданный предмет исчезает через количество часов, равное вашему бонусу мастерства. Примеры предметов, которые вы можете создать, смотрите в главе «Снаряжение» «Книги игрока».\n\nПосле того, как вы создадите предмет этим умением, вы не можете сделать это снова, пока не закончите продолжительный отдых или не израсходуете ячейку заклинания 2-го уровня или выше, чтобы применить это умение снова. У вас может быть только один предмет, созданный этим умением, одновременно: если вы используете это действие снова, то предыдущий предмет немедленно исчезает. Максимально возможный размер предмета, который вы можете создать с помощью этого умения, увеличивается на одну категорию, когда вы достигаете 6-го уровня (Большой) и 14-го уровня (Огромный).', 
              3,
              'Create nonmagical item. Max GP value: 20 x Level. Duration: PB hours.',
              'Создать немагический предмет. Макс цена: 20 х Уровень зм. Длительность: БМ часов.'),
            f('animating_performance', 
              'Animating Performance', 
              'Оживляющее выступление', 
              'As an action, you can target a Large or smaller nonmagical item you can see within 30 feet of you and animate it. The animate item uses the Dancing Item stat block, which uses your proficiency bonus (PB). The item is friendly to you and your companions and obeys your commands. It lives for 1 hour, until it is reduced to 0 hit points, or until you die. In combat, the item shares your initiative count, but it takes its turn immediately after yours. It can move and use its reaction on its own, but the only action it takes on its turn is the Dodge action, unless you take a bonus action on your turn to command it to take another action. That action can be one in its stat block or some other action. If you are incapacitated, the item can take any action of its choice, not just Dodge. When you use your Bardic Inspiration feature, you can command the item as part of the same bonus action you use for Bardic Inspiration. Once you animate an item with this feature, you can\'t do so again until you finish a long rest, unless you expend a spell slot of 3rd level or higher to use this feature again. You can have only one item animated by this feature at a time; if you use this action and already have a dancing item from this feature, the first one immediately becomes inanimate.', 
              'Действием вы можете нацелиться на немагический предмет не больше Большого размера, который вы можете видеть в пределах 30 футов от вас, который никто не держит и не несёт, и оживить его. Пробуждённый предмет использует блок статистики танцующий предмет [dancing Item], зависящий от вашего бонуса мастерства (БМ). Этот предмет дружелюбен к вам и вашим спутникам и подчиняется вашим командам. Он оживает либо на 1 час, либо до тех пор, пока его хиты не упадут до 0, либо пока вы не умрете.\n\nВ бою предмет получает вашу инициативу и ходит сразу же после вас. Он может перемещаться и использовать свою реакцию самостоятельно, но единственное действие, которое он может совершать в свой ход — это Уклонение, если только вы не используете своё бонусное действие, чтобы приказать ему сделать что-то другое. Это действие может быть одним из действий из его блока статистики или любым другим действием. Если вы недееспособны, то предмет может использовать любое действие по своему выбору, а не только Уклонение.\n\nКогда вы используете умение «Вдохновение барда», частью того же бонусного действия вы можете отдавать приказы этому оживленному предмету.\n\nПосле того, как вы оживляете предмет с помощью этого умения, вы не можете сделать это снова, пока не закончите продолжительный отдых или не израсходуете ячейку заклинания 3-го уровня или выше, чтобы снова воспользоваться этим умением. Вы можете одновременно иметь только один предмет, пробуждённый этим умением. Если вы используете это действие и уже имеете танцующий предмет от этого умения, то первый из них мгновенно становится неодушевленным.', 
              6,
              'Animate Large/smaller item (Dancing Item). Bonus Action to command.',
              'Оживить Большой/меньший предмет (Танцующий Предмет). Бонусное действие для команды.'),
            f('creative_crescendo', 
              'Creative Crescendo', 
              'Крещендо созидания', 
              'When you use your Performance of Creation feature, you can create more than one item at once. The number of items equals your Charisma modifier (minimum of two items). If you create an item that would exceed that number, you choose which of the previously created items disappears. Only one of these items can be of the maximum size you can create; the rest must be Small or Tiny. You are no longer limited by gp value when creating items with Performance of Creation.', 
              'При использовании умения «Созидательное выступление» вы можете создать больше одного предмета. Количество предметов равно вашему модификатору Харизмы (минимум два предмета). Если вы создадите предмет сверх этого числа, то вы можете выбрать, какой из уже существующих предметов исчезнет. Только один из этих предметов может иметь максимальный доступный размер, остальные должны быть Маленькими или Крошечными.\n\nВы больше не ограничены стоимостью в зм при создании предметов с помощью умения «Созидательное выступление».', 
              14)
        ], 'TCE',
        'Bards believe the cosmos is a work of art—the creation of the first dragons and gods. That creative work included harmonies that continue to resonate through existence today, a power known as the Song of Creation. The bards of the College of Creation draw on that primeval song through dance, music, and poetry.',
        'Барды считают космос произведением искусства — творением первых драконов и богов. Эта творческая работа включала в себя гармоники, которые продолжают пронизывать бытие до сих пор, силу, известную как Песнь Созидания. Барды коллегии созидания исполняют эту первобытную песню через танец, музыку и стихи.'),

        // 8. College of Spirits (VRGtR)
        sc('spirits', 'College of Spirits', 'Коллегия Духов', [
            f('guiding_whispers', 
              'Guiding Whispers', 
              'Направляющий шёпот', 
              'You can reach out to spirits to guide you and others. You learn the Guidance cantrip, which doesn\'t count against the number of bard cantrips you know. For you, it has a range of 60 feet.', 
              'Вы можете обратиться к духам, чтобы они направили вас и других. Вы изучаете заговор указание [guidance], который не учитывается при подсчёте известных вам заговоров барда. Для вас он имеет дистанцию 60 футов.', 
              3
            ),
            f('spiritual_focus', 
              'Spiritual Focus', 
              'Спиритическая фокусировка', 
              'You employ tools that aid you in channeling spirits, be they historical figures or fictional archetypes. You can use the following objects as a spellcasting focus for your bard spells: a candle, crystal ball, skull, spirit board, or tarokka deck.\n\nStarting at 6th level, when you cast a bard spell that deals damage or restores hit points through the Spiritual Focus, roll a d6, and you gain a bonus to one damage or healing roll of the spell equal to the number rolled.', 
              'Вы используете инструменты, которые помогают вам обращаться к духам, будь то исторические личности или вымышленные архетипы. Вы можете использовать следующие предметы в качестве фокусировки для заклинаний барда: свечу, хрустальный шар, череп, спиритическую доску или колоду Тарокка.\n\nНачиная с 6-го уровня, когда вы с помощью спиритической фокусировки накладываете заклинание барда, которое наносит урон или восстанавливает хиты, бросьте к6, и вы получите бонус к одному броску урона или исцеления этого заклинания, равный выпавшему результату.', 
              3,
              'Use specific items as a spellcasting focus. At 6th level, gain a +1d6 bonus to one damage or healing roll when using the focus.',
              'Используйте особые предметы как фокусировку. С 6-го уровня добавляйте +1к6 к одному броску урона или исцеления при использовании фокусировки.'
            ),
            f('tales_from_beyond', 
              'Tales from Beyond', 
              'Истории с того света', 
              'You reach out to spirits who tell their tales through you. While you are holding your Spiritual Focus, you can use a bonus action to expend one use of your Bardic Inspiration and roll on the Spirit Tales table using your Bardic Inspiration die to determine the tale the spirits direct you to tell. You retain the tale in mind until you bestow the tale\'s effect or you finish a short or long rest.\n\nYou can use an action to choose one creature you can see within 30 feet of you (this can be you) to be the target of the tale\'s effect. Once you do so, you can\'t bestow the tale\'s effect again until you roll it again.\n\nYou can retain only one of these tales in mind at a time, and rolling on the Spirit Tales table immediately ends the effect of the previous tale.\n\nIf the tale requires a saving throw, the DC equals your spell save DC.', 
              'Вы обращаетесь к духам, которые рассказывают свои истории через вас. Пока вы держите свою спиритическую фокусировку, вы можете бонусным действием потратить одно использование вашего «Вдохновения барда» и совершить бросок по таблице «Истории духов», используя кость «Вдохновения барда», чтобы узнать историю, которую духи поведают вам. Вы сохраняете историю в памяти до тех пор, пока не используете её эффект или не закончите короткий или продолжительный отдых.\n\nДействием вы можете выбрать одно существо, которое вы видите в пределах 30 футов от себя (вы можете выбрать себя), которое станет целью эффекта истории. Сделав это, вы не можете использовать этот же эффект, пока не совершите повторный бросок.\n\nОдновременно вы можете держать в голове только одну из этих историй, повторный бросок по таблице «Истории духов» немедленно прекращает действие эффекта предыдущего броска.\n\nЕсли история требует совершения спасброска, её Сл равна Сл спасброска ваших заклинаний.', 
              3,
              'Bonus Action: Expend Inspiration to roll on the Spirit Tales table. Action: Apply the effect to a creature within 30 feet.',
              'Бонусное действие: Потратьте Вдохновение, чтобы бросить по таблице Историй Духов. Действие: Примените эффект к существу в пределах 30 футов.'
            ),
            f('spirit_session', 
              'Spirit Session', 
              'Спиритический сеанс', 
              'Spirits provide you with supernatural insights. You can conduct an hour-long ritual channeling spirits (which can be done during a short or long rest) using your Spiritual Focus. You can conduct the ritual with a number of willing creatures equal to your proficiency bonus (including yourself). At the end of the ritual, you temporarily learn one spell of your choice from any class.\n\nThe spell you choose must be of a level equal to or less than the number of creatures that conducted the ritual or the spell\'s level must not exceed your proficiency bonus, and the spell must be of a school of Divination or Necromancy. The chosen spell counts as a bard spell for you but doesn\'t count against the number of bard spells you know.\n\nOnce you perform the ritual, you can\'t do so again until you start a long rest, and you know the chosen spell until you start a long rest.', 
              'Духи дарят вам сверхъестественные озарения. Вы можете провести часовой ритуал обращения к духам (который может быть выполнен во время короткого или продолжительного отдыха), используя свою спиритическую фокусировку. Вы можете провести ритуал вместе с несколькими согласными существами, количество которых равно вашему бонусу мастерства (включая вас). В конце ритуала вы временно изучаете одно заклинание по вашему выбору из списка заклинаний любого класса.\n\nВыбранное заклинание должно иметь уровень не выше количества существ, проводивших ритуал, должно быть того уровня, который вы способны накладывать, и должно принадлежать к школе Прорицания или Некромантии. Выбранное заклинание считается для вас заклинанием барда, но не учитываются при подсчёте известных вам заклинаний барда.\n\nПосле проведения ритуала вы не можете провести его снова, пока не начнёте продолжительный отдых, и вы помните выбранное заклинание, пока не начнёте продолжительный отдых.', 
              6,
              'Perform a 1-hour ritual to temporarily learn one Divination or Necromancy spell from any class list (level up to Proficiency Bonus).',
              'Проведите часовой ритуал, чтобы временно изучить одно заклинание Прорицания или Некромантии из списка любого класса (уровень до Бонуса Мастерства).'
            ),
            f('mystical_connection', 
              'Mystical Connection', 
              'Мистическая связь', 
              'You now have the ability to nudge the spirits of Tales from Beyond toward certain tales. Whenever you roll on the Spirit Tales table, you can roll the die twice and choose which of the two effects to bestow. If you roll the same number on both dice, you can ignore the number and choose any effect on the table.', 
              'Теперь у вас есть возможность побудить духов рассказать определённые истории. Каждый раз, когда вы совершаете бросок по таблице «Истории с того света», вы можете бросить кость дважды и выбрать, какой из двух эффектов использовать.\n\nЕсли на костях выпало одинаковое значение, то вы можете проигнорировать его и выбрать любой эффект из таблицы.', 
              14,
              'When you roll on the Spirit Tales table, roll the die twice and choose the result. If you roll doubles, choose any effect.',
              'При броске по таблице Историй Духов бросайте кость дважды и выбирайте результат. При дубле выберите любой эффект.'
            )
        ], 'VRGtR',
        'Bards of the College of Spirits seek stories with inherent power—be they legends, histories, or fictions—and bring them to life. Using occult trappings, these bards conjure spiritual embodiments of powerful forces to change the world once more. Such spirits are capricious, though, and what a bard summons isn\'t always entirely under their control.',
        'Барды коллегии духов ищут истории с изначально заложенной в них силой — будь то легенды, сказания или вымыслы — и воплощают их в жизнь. Используя оккультные приёмы, эти барды вызывают спиритические воплощения могущественных сил, чтобы те вновь изменили мир. Впрочем, такие духи капризны, и то, что вызывает бард, не всегда находится под контролем.'
        )
    ] 
};

export default BARD;
