
export const SPELLS_LEVEL8 = `
<!-- LEVEL 8 -->
<spell><name>Антимагическое поле</name><level>8</level><school>A</school><time>1 действие</time><range>На себя (10 футов)</range><components>V, S, M</components><duration>Концентрация, 1 час</duration><text>Создает сферу, подавляющую магию. Заклинания и маг. предметы не работают внутри.</text><classes>Жрец, Волшебник</classes></spell>
<spell><name>Клон</name><level>8</level><school>N</school><time>1 час</time><range>Касание</range><components>V, S, M</components><duration>Мгновенная</duration><text>Создает инертную копию существа. Если оригинал умирает, душа переносится в клон.</text><classes>Волшебник</classes></spell>
<spell><name>Личный план</name><level>8</level><school>C</school><time>1 действие</time><range>60 футов</range><components>S</components><duration>1 час</duration><text>Создает дверь в пустую комнату 30х30 футов на демиплане.</text><classes>Колдун, Волшебник</classes></spell>
<spell><name>Подчинение чудовища</name><level>8</level><school>EN</school><time>1 действие</time><range>60 футов</range><components>V, S</components><duration>Концентрация, 1 час</duration><text>Вы управляете действиями существа (Спас Мудрости).</text><classes>Бард, Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Слабоумие</name><level>8</level><school>EN</school><time>1 действие</time><range>150 футов</range><components>V, S, M</components><duration>Мгновенная</duration><text>Интеллект и Харизма цели становятся равны 1. Она не может колдовать (Спас Интеллекта).</text><classes>Бард, Друид, Колдун, Волшебник</classes></spell>
<spell><name>Лабиринт</name><level>8</level><school>C</school><time>1 действие</time><range>60 футов</range><components>V, S</components><duration>Концентрация, 10 минут</duration><text>Изгоняет цель в лабиринт на демиплане. Проверка Интеллекта (Сл 20) чтобы выйти.</text><classes>Волшебник</classes></spell>
<spell><name>Слово силы: Оглушение</name><level>8</level><school>EN</school><time>1 действие</time><range>60 футов</range><components>V</components><duration>Мгновенная</duration><text>Оглушает существо с &lt; 150 хитов.</text><classes>Бард, Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Солнечный взрыв</name><level>8</level><school>EV</school><time>1 действие</time><range>150 футов</range><components>V, S, M</components><duration>Мгновенная</duration><text>Взрыв света радиусом 60 футов. Урон 12d6 излучением и ослепление (Спас Телосложения).</text><roll>12d6</roll><classes>Друид, Чародей, Волшебник</classes></spell>
<spell><name>Землетрясение</name><level>8</level><school>EV</school><time>1 действие</time><range>500 футов</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Вызывает землетрясение в радиусе 100 футов. Разрушает строения, открывает трещины.</text><classes>Жрец, Друид, Чародей</classes></spell>
<spell><name>Зажигательное облако</name><level>8</level><school>C</school><time>1 действие</time><range>150 футов</range><components>V, S</components><duration>Концентрация, 1 минута</duration><text>Облако дыма наносит 10d8 урона огнём.</text><roll>10d8</roll><classes>Друид, Чародей, Волшебник</classes></spell>
<spell><name>Сокрытие разума</name><level>8</level><school>AB</school><time>1 действие</time><range>Касание</range><components>V, S</components><duration>24 часа</duration><text>Защищает разум от чтения мыслей, эмоций и психического урона.</text><classes>Бард, Волшебник</classes></spell>
<spell><name>Антипатия/Симпатия</name><level>8</level><school>EN</school><time>1 час</time><range>60 футов</range><components>V, S, M</components><duration>10 дней</duration><text>Заставляет существ определенного типа избегать или стремиться к цели.</text><classes>Бард, Друид, Волшебник</classes></spell>
<spell><name>Святая аура</name><level>8</level><school>AB</school><time>1 действие</time><range>На себя</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Святая аура дает преимущество на спасы союзникам и помеху на атаки врагам.</text><classes>Жрец</classes></spell>
<spell><name>Формы животных</name><level>8</level><school>T</school><time>1 действие</time><range>30 футов</range><components>V, S</components><duration>Концентрация, 24 часа</duration><text>Превращает любое количество существ в зверей (ПО 4 или ниже).</text><classes>Друид</classes></spell>
<spell><name>Контроль погоды</name><level>8</level><school>T</school><time>10 минут</time><range>На себя (5 миль)</range><components>V, S, M</components><duration>Концентрация, 8 часов</duration><text>Меняет погоду на улице.</text><classes>Жрец, Друид, Волшебник</classes></spell>
<spell><name>Цунами</name><level>8</level><school>C</school><time>1 минута</time><range>Вид</range><components>V, S</components><duration>Концентрация, 6 раундов</duration><text>Стена воды высотой 300 футов. Урон 6d10 дробящим.</text><roll>6d10</roll><classes>Друид</classes></spell>
<spell><name>Телепатия</name><level>8</level><school>EV</school><time>1 действие</time><range>Неограниченная</range><components>V, S, M</components><duration>24 часа</duration><text>Создает телепатическую связь с одним существом. Вы можете общаться на любом расстоянии, даже между планами.</text><classes>Волшебник, Бард</classes></spell>
<spell><name>Иллюзорный дракон</name><level>8</level><school>I</school><time>1 действие</time><range>120 футов</range><components>S</components><duration>Концентрация, 1 минута</duration><text>Огромный теневой дракон. Дыхание 7d6 урона. Испуг врагов.</text><roll>7d6</roll><classes>Волшебник</classes></spell>
<spell><name>Ужасное увядание Аби-Дальзима</name><level>8</level><school>N</school><time>1 действие</time><range>150 футов</range><components>V, S, M</components><duration>Мгновенная</duration><text>Вытягивает влагу из существ в кубе 30 футов. 12d8 некротикой (Спас Телосложения).</text><roll>12d8</roll><classes>Волшебник, Чародей</classes></spell>
<spell><name>Сводящая с ума тьма</name><level>8</level><school>EV</school><time>1 действие</time><range>150 футов</range><components>V, M</components><duration>Концентрация, 10 минут</duration><text>Сфера тьмы 60 футов. 8d8 психического урона (Спас Мудрости).</text><roll>8d8</roll><classes>Волшебник, Колдун</classes></spell>
<spell><name>Разрыв реальности</name><level>8</level><school>C</school><time>1 действие</time><range>60 футов</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Цель страдает от случайных видений и разрывов реальности (Урон, Стан, Слепота).</text><classes>Волшебник</classes></spell>
<spell><name>Могучая крепость</name><level>8</level><school>C</school><time>1 минута</time><range>1 миля</range><components>V, S, M</components><duration>Мгновенная</duration><text>Создает огромную каменную крепость с едой и слугами на 7 дней. (500 зм)</text><classes>Волшебник</classes></spell>
<spell><name>Заточение</name><level>9</level><school>A</school><time>1 минута</time><range>30 футов</range><components>V, S, M</components><duration>Пока не развеяно</duration><text>Создает магическое узилище для существа (Погребение, Сковывание, Особая тюрьма и т.д.). Спас Мудрости.</text><classes>Колдун, Волшебник</classes></spell>
`;