
export const SPELLS_LEVEL7 = `
<!-- LEVEL 7 -->
<spell><name>Задержанный огненный шар</name><level>7</level><school>EV</school><time>1 действие</time><range>150 футов</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Создает шар, который взрывается позже. Урон 12d6 + 1d6 за каждый ход задержки.</text><roll>12d6</roll><classes>Чародей, Волшебник</classes></spell>
<spell><name>Эфирность</name><level>7</level><school>T</school><time>1 действие</time><range>На себя</range><components>V, S</components><duration>8 часов</duration><text>Вы переходите на Эфирный План.</text><classes>Бард, Жрец, Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Перст смерти</name><level>7</level><school>N</school><time>1 действие</time><range>60 футов</range><components>V, S</components><duration>Мгновенная</duration><text>Наносит 7d8 + 30 урона некротикой. Гуманоид, убитый этим, восстает как зомби под вашим контролем.</text><roll>7d8+30</roll><classes>Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Силовая клетка</name><level>7</level><school>EV</school><time>1 действие</time><range>100 футов</range><components>V, S, M</components><duration>1 час</duration><text>Создает непроницаемую клетку или ящик из силового поля.</text><classes>Бард, Колдун, Волшебник</classes></spell>
<spell><name>Перемещение между планами</name><level>7</level><school>C</school><time>1 действие</time><range>Касание</range><components>V, S, M</components><duration>Мгновенная</duration><text>Перемещает вас и 8 существ на другой план существования. Или изгоняет врага (атака заклинанием + спас Харизмы).</text><classes>Жрец, Друид, Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Радужные брызги</name><level>7</level><school>EV</school><time>1 действие</time><range>На себя (60-фт конус)</range><components>V, S</components><duration>Мгновенная</duration><text>8 разноцветных лучей с разными эффектами (урон 10d6 огнем/холодом/кислотой/электр/ядом, окаменение, или изгнание).</text><roll>10d6</roll><classes>Чародей, Волшебник</classes></spell>
<spell><name>Обратная гравитация</name><level>7</level><school>T</school><time>1 действие</time><range>100 футов</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Меняет гравитацию в цилиндре 50 футов. Существа падают вверх.</text><classes>Друид, Чародей, Волшебник</classes></spell>
<spell><name>Телепортация</name><level>7</level><school>C</school><time>1 действие</time><range>10 футов</range><components>V</components><duration>Мгновенная</duration><text>Мгновенно перемещает вас и до 8 существ в любое место на том же плане.</text><classes>Бард, Чародей, Волшебник</classes></spell>
<spell><name>Огненная буря</name><level>7</level><school>EV</school><time>1 действие</time><range>150 футов</range><components>V, S</components><duration>Мгновенная</duration><text>Шторм огня (10 кубов по 10 футов). Урон 7d10 огнём (Спас Ловкости половина).</text><roll>7d10</roll><classes>Жрец, Друид, Чародей</classes></spell>
<spell><name>Корона звезд</name><level>7</level><school>EV</school><time>1 действие</time><range>На себя</range><components>V, S</components><duration>1 час</duration><text>Создает 7 звезд. Бонусным действием можно метнуть звезду (4d12 излучением).</text><roll>4d12</roll><classes>Колдун, Волшебник</classes></spell>
<spell><name>Слово силы: Боль</name><level>7</level><school>EN</school><time>1 действие</time><range>60 футов</range><components>V</components><duration>Мгновенная</duration><text>Цель с &lt; 100 хитов испытывает сильную боль (помеха на атаки, проверки, спасы, скорость 10).</text><classes>Колдун, Волшебник, Бард</classes></spell>
<spell><name>Великолепный особняк Морденкайнена</name><level>7</level><school>C</school><time>1 минута</time><range>300 футов</range><components>V, S, M</components><duration>24 часа</duration><text>Создает экстрапланарное жилище с едой и слугами.</text><classes>Бард, Волшебник</classes></spell>
<spell><name>Воскрешение</name><level>7</level><school>N</school><time>1 час</time><range>Касание</range><components>V, S, M</components><duration>Мгновенная</duration><text>Воскрешает существо, умершее не более 100 лет назад.</text><classes>Бард, Жрец</classes></spell>
<spell><name>Регенерация</name><level>7</level><school>T</school><time>1 минута</time><range>Касание</range><components>V, S, M</components><duration>1 час</duration><text>Цель восстанавливает 4d8 + 15 хитов, и по 1 хиту каждый ход. Отращивает конечности.</text><roll>4d8+15</roll><classes>Бард, Жрец, Друид</classes></spell>
<spell><name>Мираж</name><level>7</level><school>I</school><time>10 минут</time><range>Вид</range><components>V, S</components><duration>10 дней</duration><text>Меняет вид местности в радиусе 1 мили. Иллюзия осязаема.</text><classes>Бард, Друид, Волшебник</classes></spell>
<spell><name>Символ</name><level>7</level><school>A</school><time>1 минута</time><range>Касание</range><components>V, S, M</components><duration>Пока не развеяно</duration><text>Начертить глиф с эффектом (Смерть, Раздор, Страх, Надежда, Безумие, Боль, Сон, Оглушение).</text><classes>Бард, Жрец, Волшебник</classes></spell>
<spell><name>Сон синей вуали</name><level>7</level><school>C</school><time>10 минут</time><range>20 футов</range><components>V, S, M</components><duration>6 часов</duration><text>Вы и до 8 существ переноситесь в другой мир, если у вас есть магический предмет из этого мира.</text><classes>Бард, Чародей, Волшебник, Колдун</classes></spell>
`;
