
export const SPELLS_LEVEL9 = `
<!-- LEVEL 9 -->
<spell><name>Пожелание</name><level>9</level><school>C</school><time>1 действие</time><range>На себя</range><components>V</components><duration>Мгновенная</duration><text>Могущественнейшее заклинание смертных. Может копировать любое заклинание 8 уровня или ниже, или создавать уникальные эффекты с риском.</text><classes>Чародей, Волшебник</classes></spell>
<spell><name>Метеоритный дождь</name><level>9</level><school>EV</school><time>1 действие</time><range>1 миля</range><components>V, S</components><duration>Мгновенная</duration><text>4 метеора падают в 4 точки. Радиус 40 футов. Урон 20d6 огнём и 20d6 дробящим.</text><roll>40d6</roll><classes>Чародей, Волшебник</classes></spell>
<spell><name>Остановка времени</name><level>9</level><school>T</school><time>1 действие</time><range>На себя</range><components>V</components><duration>Мгновенная</duration><text>Вы останавливаете время на 1d4+1 ходов. Ходы совершаете подряд.</text><classes>Чародей, Волшебник</classes></spell>
<spell><name>Слово силы: Смерть</name><level>9</level><school>EN</school><time>1 действие</time><range>60 футов</range><components>V</components><duration>Мгновенная</duration><text>Заставляет существо с &lt; 100 хитов мгновенно умереть.</text><classes>Бард, Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Предвидение</name><level>9</level><school>D</school><time>1 минута</time><range>Касание</range><components>V, S, M</components><duration>8 часов</duration><text>Цель получает преимущество на все броски, а враги атакуют её с помехой. Нельзя застать врасплох.</text><classes>Бард, Друид, Колдун, Волшебник</classes></spell>
<spell><name>Истинное превращение</name><level>9</level><school>T</school><time>1 действие</time><range>30 футов</range><components>V, S, M</components><duration>Концентрация, 1 час</duration><text>Превращает существо в другое существо или предмет. Если продержать час, превращение становится постоянным.</text><classes>Бард, Колдун, Волшебник</classes></spell>
<spell><name>Врата</name><level>9</level><school>C</school><time>1 действие</time><range>60 футов</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Открывает портал на другой план существования. Может призвать конкретное существо по имени.</text><classes>Жрец, Чародей, Волшебник, Колдун</classes></spell>
<spell><name>Астральная проекция</name><level>9</level><school>N</school><time>1 час</time><range>10 футов</range><components>V, S, M</components><duration>Особая</duration><text>Проецирует вас и до 8 спутников на Астральный План.</text><classes>Жрец, Колдун, Волшебник</classes></spell>
<spell><name>Смена формы</name><level>9</level><school>T</school><time>1 действие</time><range>На себя</range><components>V, S, M</components><duration>Концентрация, 1 час</duration><text>Вы превращаетесь в другое существо. Вы можете менять форму в свой ход.</text><classes>Друид, Волшебник</classes></spell>
<spell><name>Истинное воскрешение</name><level>9</level><school>N</school><time>1 час</time><range>Касание</range><components>V, S, M</components><duration>Мгновенная</duration><text>Полностью воскрешает существо (даже без тела), снимает все недуги.</text><classes>Жрец, Друид</classes></spell>
<spell><name>Слово силы: Исцеление</name><level>9</level><school>EV</school><time>1 действие</time><range>Касание</range><components>V, S</components><duration>Мгновенная</duration><text>Полностью исцеляет существо и снимает состояния.</text><classes>Бард, Жрец</classes></spell>
<spell><name>Исполнение желаний</name><level>9</level><school>C</school><time>1 действие</time><range>На себя</range><components>V, S, M</components><duration>Мгновенная</duration><text>Вы можете изменить реальность, исполнив желание (альтернатива Wish для других классов, если используется).</text><classes>Джинн (Колдун)</classes></spell>
<spell><name>Психический крик</name><level>9</level><school>EN</school><time>1 действие</time><range>90 футов</range><components>S</components><duration>Мгновенная</duration><text>До 10 существ. Урон 14d6 психикой и ошеломление (Спас Интеллекта).</text><roll>14d6</roll><classes>Бард, Чародей, Колдун, Волшебник</classes></spell>
<spell><name>Радужная стена</name><level>9</level><school>EV</school><time>1 действие</time><range>60 футов</range><components>V, S</components><duration>10 минут</duration><text>Стена из 7 слоев с разными эффектами.</text><classes>Волшебник</classes></spell>
<spell><name>Массовое лечение</name><level>9</level><school>EV</school><time>1 действие</time><range>60 футов</range><components>V, S</components><duration>Мгновенная</duration><text>Восстанавливает 700 хитов, распределенных между любым количеством существ.</text><roll>700</roll><classes>Жрец, Друид</classes></spell>
<spell><name>Шторм возмездия</name><level>9</level><school>C</school><time>1 действие</time><range>Вид</range><components>V, S</components><duration>Концентрация, 1 минута</duration><text>Создает шторм с разными эффектами каждый раунд (гром, кислота, молнии, град).</text><classes>Друид</classes></spell>
<spell><name>Жуткое видение</name><level>9</level><school>I</school><time>1 действие</time><range>120 футов</range><components>V, S</components><duration>Концентрация, 1 минута</duration><text>Все существа в радиусе 30 футов видят свои страхи. Урон 4d10 психикой (Спас Мудрости).</text><roll>4d10</roll><classes>Волшебник, Колдун</classes></spell>
<spell><name>Клинок разрушения</name><level>9</level><school>C</school><time>1 бонусное действие</time><range>60 футов</range><components>V, S</components><duration>Концентрация, 1 минута</duration><text>Создает клинок. 2 атаки по 4d12 силовым. Крит на 18-20 (доп урон).</text><roll>4d12</roll><classes>Волшебник, Чародей, Колдун</classes></spell>
<spell><name>Неуязвимость</name><level>9</level><school>A</school><time>1 действие</time><range>На себя</range><components>V, S, M</components><duration>Концентрация, 10 минут</duration><text>Иммунитет ко всему урону.</text><classes>Волшебник</classes></spell>
<spell><name>Массовый полиморф</name><level>9</level><school>T</school><time>1 действие</time><range>120 футов</range><components>V, S, M</components><duration>Концентрация, 1 час</duration><text>Превращает до 10 существ в зверей (Спас Мудрости). ПО существа должно позволять форму.</text><classes>Бард, Чародей, Волшебник</classes></spell>
<spell><name>Пожирание времени</name><level>9</level><school>N</school><time>1 действие</time><range>90 футов</range><components>V, S, M</components><duration>Мгновенная</duration><text>10d12 некротикой (Спас Телосложения). Цель стареет до смертного одра.</text><roll>10d12</roll><classes>Волшебник</classes></spell>
<spell><name>Прожорливая пустота</name><level>9</level><school>EV</school><time>1 действие</time><range>1000 футов</range><components>V, S, M</components><duration>Концентрация, 1 минута</duration><text>Сфера 20 футов. Затягивает существ. 5d10 силовым. Уничтожает предметы.</text><roll>5d10</roll><classes>Волшебник</classes></spell>
`;
