
import { ClassData } from '../../types';
import { f, sc } from '../dataHelpers';

const ROGUE_BASE = [
    f('expertise_1', 
      'Expertise', 
      'Компетентность', 
      'At 1st level, choose two of your skill proficiencies, or one of your skill proficiencies and your proficiency with thieves\' tools. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.', 
      'На 1-м уровне выберите два ваших владения в навыках или одно владение навыком и владение воровскими инструментами. Ваш бонус мастерства удваивается для всех проверок характеристик, которые вы совершаете, используя любое из выбранных владений.', 
      1),
      
    f('sneak_attack', 
      'Sneak Attack', 
      'Скрытая атака', 
      'Beginning at 1st level, you know how to strike subtly and exploit a foe\'s distraction. Once per turn, you can deal an extra 1d6 damage to one creature you hit with an attack if you have advantage on the attack roll. The attack must use a finesse or a ranged weapon.\n\nYou don\'t need advantage on the attack roll if another enemy of the target is within 5 feet of it, that enemy isn\'t incapacitated, and you don\'t have disadvantage on the attack roll.\n\nThe amount of the extra damage increases as you gain levels in this class, as shown in the Sneak Attack column of the Rogue table.', 
      'Начиная с 1-го уровня, вы знаете, как наносить точные удары и использовать отвлечение врага. Один раз в ход вы можете нанести дополнительные 1к6 урона существу, по которому вы попали атакой, если у вас есть преимущество на бросок атаки. Атака должна использовать фехтовальное или дальнобойное оружие.\n\nВам не нужно иметь преимущество при атаке, если другой враг цели находится в пределах 5 футов от неё, этот враг дееспособен, и у вас нет помехи на бросок атаки.\n\nКоличество дополнительного урона увеличивается с получением уровней в этом классе, как показано в колонке «Скрытая атака» таблицы Плута.', 
      1),
    
    f('thieves_cant', 
      'Thieves\' Cant', 
      'Воровской жаргон', 
      'During your rogue training you learned thieves\' cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation. Only another creature that knows thieves\' cant understands such messages. It takes four times longer to convey such a message than it does to speak the same idea plainly.\n\nIn addition, you understand a set of secret signs and symbols used to convey short, simple messages, such as whether an area is dangerous or the territory of a thieves\' guild, whether loot is nearby, or whether the people in an area are easy marks or will provide a safe house for thieves on the run.', 
      'Во время своего обучения вы выучили воровской жаргон, тайную смесь диалекта, жаргона и шифра, которая позволяет вам скрывать сообщения в, казалось бы, обычном разговоре. Только другое существо, знающее воровской жаргон, понимает такие сообщения. Передача такого сообщения занимает вчетверо больше времени, чем если бы вы говорили ту же идею прямо.\n\nКроме того, вы понимаете набор секретных знаков и символов, используемых для передачи коротких, простых сообщений, таких как: является ли область опасной или территоей воровской гильдии, есть ли поблизости добыча, являются ли люди в этом месте лёгкой добычей или предоставят убежище для беглых воров.', 
      1),
    
    f('cunning_action', 
      'Cunning Action', 
      'Хитрое действие', 
      'Starting at 2nd level, your quick thinking and agility allow you to move and act quickly. You can take a bonus action on each of your turns in combat. This action can be used only to take the Dash, Disengage, or Hide action.', 
      'Начиная со 2-го уровня, ваше быстрое мышление и проворство позволяют вам двигаться и действовать быстрее. Вы можете совершать бонусное действие в каждый ваш ход в бою. Это действие может быть использовано только для действий Рывок, Отход или Засада (Спрятаться).', 
      2),
    
    f('rogue_archetype', 
      'Roguish Archetype', 
      'Архетип плута', 
      'At 3rd level, you choose an archetype that you emulate in the exercise of your rogue abilities. Your archetype choice grants you features at 3rd level and then again at 9th, 13th, and 17th level.', 
      'На 3-м уровне вы выбираете архетип, которому вы подражаете в использовании своих плутовских способностей. Ваш выбор архетипа даёт вам умения на 3-м уровне, а также на 9-м, 13-м и 17-м уровнях.', 
      3),
    
    f('steady_aim', 
      'Steady Aim (Optional)', 
      'Прицеливание (Опционально)', 
      'As a bonus action, you give yourself advantage on your next attack roll on the current turn. You can use this bonus action only if you haven\'t moved during this turn, and after you use the bonus action, your speed is 0 until the end of the current turn.', 
      'Бонусным действием вы даёте себе преимущество на следующий бросок атаки в текущем ходу. Вы можете использовать это бонусное действие, только если ещё не перемещались в этом ходу, и после использования ваша скорость становится равна 0 до конца текущего хода.', 
      3),

    f('uncanny_dodge', 
      'Uncanny Dodge', 
      'Невероятное уклонение', 
      'Starting at 5th level, when an attacker that you can see hits you with an attack, you can use your reaction to halve the attack\'s damage against you.', 
      'Начиная с 5-го уровня, когда нападающий, которого вы видите, попадает по вам атакой, вы можете использовать реакцию, чтобы уменьшить вдвое урон этой атаки по вам.', 
      5),
      
    f('expertise_6', 
      'Expertise (Level 6)', 
      'Компетентность (Уровень 6)', 
      'At 6th level, you can choose two more of your proficiencies (in skills or with thieves\' tools) to gain this benefit.', 
      'На 6-м уровне вы можете выбрать ещё два владения (навыки или воровские инструменты), чтобы получить эту же выгоду.', 
      6),
    
    f('evasion', 
      'Evasion', 
      'Увёртливость', 
      'Beginning at 7th level, you can nimbly dodge out of the way of certain area effects, such as a red dragon\'s fiery breath or an ice storm spell. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail.', 
      'Начиная с 7-го уровня, вы можете ловко уклоняться от воздействия по площади, такого как огненное дыхание красного дракона или заклинание ледяной шторм. Если вы попадаете под эффект, позволяющему совершить спасбросок Ловкости, чтобы получить только половину урона, вы не получаете урона при успехе и получаете только половину урона при провале.', 
      7),
    
    f('reliable_talent', 
      'Reliable Talent', 
      'Надёжный талант', 
      'You have refined your chosen skills until they approach perfection. Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10.', 
      'Вы отточили свои навыки почти до совершенства. Всякий раз, когда вы совершаете проверку характеристики, которая позволяет добавить бонус мастерства, вы можете считать любые результаты 9 и ниже на к20 как 10.', 
      11),
    
    f('blindsense', 
      'Blindsense', 
      'Слепое зрение', 
      'If you are able to hear, you are aware of the location of any hidden or invisible creature within 10 feet of you.', 
      'Если вы можете слышать, то знаете о местонахождении всех скрытых и невидимых существ в пределах 10 футов от себя.', 
      14),
    
    f('slippery_mind', 
      'Slippery Mind', 
      'Скользкий разум', 
      'You have acquired greater mental strength. You gain proficiency in Wisdom saving throws.', 
      'Вы обрели большую ментальную силу. Вы получаете владение спасбросками Мудрости.', 
      15),
    
    f('elusive', 
      'Elusive', 
      'Неуловимый', 
      'You are so evasive that attackers rarely gain the upper hand against you. No attack roll has advantage against you while you aren\'t incapacitated.', 
      'Вы настолько увёртливы, что нападающие редко могут взять над вами верх. Броски атаки по вам не могут совершаться с преимуществом, пока вы дееспособны.', 
      18),
    
    f('stroke_of_luck', 
      'Stroke of Luck', 
      'Удача', 
      'You have an uncanny knack for succeeding when you need to. If your attack misses a target within range, you can turn the miss into a hit. Alternatively, if you fail an ability check, you can treat the d20 roll as a 20.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.', 
      'Вы обладаете сверхъестественным даром преуспевать, когда это необходимо. Если ваша атака промахивается по цели в пределах досягаемости, вы можете превратить промах в попадание. В качестве альтернатива, если вы проваливаете проверку характеристики, вы можете считать результат броска к20 равным 20.\n\nИспользовав эту особенность, вы не можете использовать её снова, пока не завершите короткий или продолжительный отдых.', 
      20),
];

export const ROGUE: ClassData = { 
    id: 'rogue', 
    name: { en: 'Rogue', ru: 'Плут' }, 
    hitDie: 8, 
    primaryAbility: ['dex'], 
    savingThrows: ['dex', 'int'], 
    skillsChoice: { count: 4, options: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleight_of_hand', 'stealth'] }, 
    features: ROGUE_BASE, 
    multiclassRequirements: [{ requirements: { dex: 13 } }],
    subclasses: [ 
        // 1. Thief
        sc('thief', 'Thief', 'Вор', [ 
            f('fast_hands', 
              'Fast Hands', 
              'Быстрые руки', 
              'You can use the bonus action granted by your Cunning Action to make a Dexterity (Sleight of Hand) check, use your thieves\' tools to disarm a trap or open a lock, or take the Use an Object action.', 
              'Вы можете использовать бонусное действие, предоставленное вашим Хитрым действием, чтобы совершить проверку Ловкости (Ловкость рук), использовать воровские инструменты для обезвреживания ловушки или вскрытия замка, или же совершить действие Использование предмета.', 
              3,
              'Bonus Action: Sleight of Hand check, use Thieves\' Tools to disarm/open, or the Use an Object action.',
              'Бонусное действие: проверка Ловкости рук, использование воровских инструментов или действие Использование предмета.'
            ),
            f('second_story_work', 
              'Second-Story Work', 
              'Форточник', 
              'You gain the ability to climb faster than normal; climbing no longer costs you extra movement. In addition, when you make a running jump, the distance you cover increases by a number of feet equal to your Dexterity modifier.', 
              'Вы получаете возможность лазать быстрее обычного; лазание больше не стоит вам дополнительного перемещения. Кроме того, когда вы совершаете прыжок с разбега, расстояние, которое вы преодолеваете, увеличивается на число футов, равное вашему модификатору Ловкости.', 
              3,
              'Climbing costs no extra movement. Running jump distance increases by your Dexterity modifier.',
              'Лазание не требует дополнительного движения. Дистанция прыжка с разбега увеличивается на модификатор Ловкости.'
            ),
            f('supreme_sneak', 
              'Supreme Sneak', 
              'Высокая скрытность', 
              'You have advantage on a Dexterity (Stealth) check if you move no more than half your speed on the same turn.', 
              'Вы совершаете с преимуществом проверки Ловкости (Скрытность), если в этом ходу перемещались не более чем на половину своей скорости.', 
              9,
              'Advantage on Stealth checks if moving no more than half speed during the turn.',
              'Преимущество на Скрытность, если вы переместились не более чем на половину своей скорости за ход.'
            ),
            f('use_magic_device', 
              'Use Magic Device', 
              'Использование магических предметов', 
              'You have learned enough about the workings of magic that you can improvise the use of items even when they are not intended for you. You ignore all class, race, and level requirements on the use of magic items.', 
              'Вы узнаёте достаточно о магических процессах, чтобы импровизировать при использовании предметов, даже если раньше вы не умели ими пользоваться. Вы игнорируете все требования класса, расы и уровня при использовании магических предметов.', 
              13,
              'Ignore all class, race, and level requirements when using any magic items.',
              'Игнорирование всех требований класса, расы и уровня при использовании любых магических предметов.'
            ),
            f('thiefs_reflexes', 
              'Thief\'s Reflexes', 
              'Воровские рефлексы', 
              'You have become adept at laying ambushes and quickly escaping danger. You can take two turns during the first round of any combat. You take your first turn at your normal initiative and your second turn at your initiative minus 10. You can\'t use this feature when you are surprised.', 
              'Вы обретаете большой опыт организации засад и быстрого отступления при опасности. Вы можете совершить два хода во время первого раунда боя. Совершите первый ход согласно своей нормальной инициативе, и второй ход с инициативой на 10 меньше. Вы не можете использовать это умение, если захвачены врасплох.', 
              17,
              'Take two turns in the first round of combat (Normal Init and Init -10). Not usable if surprised.',
              'Два хода в первом раунде боя (по инициативе и инициативе -10). Не работает при захвате врасплох.'
            )
        ], 'PHB'), 

        // 2. Arcane Trickster
        sc('arcane_trickster', 'Arcane Trickster', 'Мистический Ловкач', [ 
            f('spellcasting_at', 
              'Spellcasting', 
              'Использование заклинаний', 
              'You gain the ability to cast spells. You learn three cantrips: Mage Hand and two other cantrips of your choice from the wizard spell list. You learn three 1st-level wizard spells of your choice, two of which you must choose from the enchantment and illusion spells on the wizard spell list.\n\nIntelligence is your spellcasting ability for your wizard spells.', 
              'Вы получаете способность накладывать заклинания. Вы изучаете три заговора: Волшебная рука и два других заговора на ваш выбор из списка заклинаний волшебника. Вы изучаете три заклинания волшебника 1-го уровня на ваш выбор, два из которых должны быть выбраны из школ Иллюзии и Очарования.\n\nИнтеллект является вашей базовой характеристикой для заклинаний волшебника.', 
              3),
            f('mage_hand_legerdemain', 
              'Mage Hand Legerdemain', 
              'Ловкая волшебная рука', 
              'When you cast Mage Hand, you can make the spectral hand invisible, and you can perform the following additional tasks with it:\n• You can stow one object the hand is holding in a container worn or carried by another creature.\n• You can retrieve an object in a container worn or carried by another creature.\n• You can use thieves\' tools to pick locks and disarm traps at range.\nYou can perform one of these tasks without being noticed by a creature if you succeed on a Dexterity (Sleight of Hand) check contested by the creature\'s Wisdom (Perception) check.\nIn addition, you can use the bonus action granted by your Cunning Action to control the hand.', 
              'Когда вы накладываете заклинание волшебная рука [mage hand], вы можете создать руку невидимой, и совершать ею следующие дополнительные действия:\n\n• Вы можете положить один предмет, удерживаемый рукой, в контейнер, носимый или несомый другим существом.\n• Вы можете достать предмет из контейнера, носимого или несомого другим существом.\n• Вы можете использовать воровские инструменты для вскрытия замков и обезвреживания ловушек в дистанции этого заклинания.\n\nВы можете выполнить одно из этих действий, не будучи замеченным, если успешно совершите проверку Ловкости (Ловкость рук) против проверки Мудрости (Восприятие) существа.\n\nКроме того, вы можете использовать бонусное действие, предоставленное умением «Хитрое действие», для управления рукой.', 
              3),
            f('magical_ambush', 
              'Magical Ambush', 
              'Магическая засада', 
              'If you are hidden from a creature when you cast a spell on it, the creature has disadvantage on any saving throw it makes against the spell this turn.', 
              'Если вы накладываете заклинание на существо, от которого скрыты, существо в этом ходу совершает с помехой спасброски от этого заклинания.', 
              9),
            f('versatile_trickster', 
              'Versatile Trickster', 
              'Многогранный ловкач', 
              'You gain the ability to distract targets with your Mage Hand. As a bonus action on your turn, you can designate a creature within 5 feet of the spectral hand created by the spell. Doing so gives you advantage on attack rolls against that creature until the end of the turn.', 
              'Вы получаете возможность отвлекать цель своей волшебной рукой. В свой ход вы бонусным действием можете обозначить существо в пределах 5 футов от руки, наложенной этим заклинанием. Если вы так делаете, то до конца этого хода совершаете броски атаки по этому существу с преимуществом.', 
              13),
            f('spell_thief', 
              'Spell Thief', 
              'Вор заклинаний', 
              'You gain the ability to magically steal the knowledge of how to cast a spell from another spellcaster.\n\nImmediately after a creature casts a spell that targets you or includes you in its area of effect, you can use your reaction to force the creature to make a saving throw with its spellcasting ability modifier. The DC equals your spell save DC. On a failed save, you negate the spell\'s effect against you, and you steal the knowledge of the spell if it is at least 1st level and of a level you can cast (it doesn\'t need to be a wizard spell). For the next 8 hours, you know the spell and can cast it using your spell slots. The creature can\'t cast that spell until the 8 hours have passed.\n\nOnce you use this feature, you can\'t use it again until you finish a long rest.', 
              'Вы получаете способность магически воровать у другого колдующего знания о том, как накладывать заклинание.\n\nСразу после накладывания заклинания существом, целью которого являетесь вы, или же если вы попали в область действия этого заклинания, вы можете реакцией заставить существо совершить спасбросок его базовой характеристики. Сл равна вашей Сл спасброска заклинания. Если спасбросок провален, вы отрицаете эффект заклинания на себе, и крадёте знание этого заклинания, если оно как минимум 1 уровня, и вы можете накладывать заклинания этого уровня (оно не обязано быть заклинанием волшебника). Вы знаете это заклинание в течение следующих 8 часов и можете его накладывать, используя свои ячейки заклинаний. Существо, у которого вы украли заклинание, не может его накладывать на протяжении 8 часов.\n\nИспользовав это умение, вы не можете использовать его повторно до окончания продолжительного отдыха.', 
              17)
        ]),

        // 3. Assassin
        sc('assassin', 'Assassin', 'Убийца', [
            f('bonus_proficiencies_assassin', 
              'Bonus Proficiencies', 
              'Дополнительные владения', 
              'You gain proficiency with the disguise kit and the poisoner\'s kit.', 
              'Вы получаете владение набором для грима и инструментами отравителя.', 
              3),
            f('assassinate', 
              'Assassinate', 
              'Ликвидация', 
              'You are at your deadliest when you get the drop on your enemies. You have advantage on attack rolls against any creature that hasn\'t taken a turn in the combat yet. In addition, any hit you score against a creature that is surprised is a critical hit.', 
              'Вы становитесь смертоносными для врагов. Вы совершаете с преимуществом броски атаки по всем существам, которые ещё не совершали ход в этом бою. Кроме того, все попадания по существам, захваченным врасплох, являются критическими попаданиями.', 
              3),
            f('infiltration_expertise', 
              'Infiltration Expertise', 
              'Мастер проникновения', 
              'You can unfailingly create false identities for yourself. You must spend seven days and 25 gp to establish the history, profession, and affiliations for an identity. You can\'t establish an identity that belongs to another person. For example, you might acquire appropriate clothing, letters of introduction, and official-looking certification.\n\nOther creatures believe you to be that person until given an obvious reason not to.', 
              'Вы можете создавать себе ложную биографию. Вы должны потратить семь дней и 25 золотых монет, чтобы сделать её достоверной и установить нужные связи. Вы не можете взять биографию, принадлежащую другому лицу. Например, вы можете приобрести соответствующую одежду, рекомендательные письма и официального вида сертификаты, чтобы обозначить себя в качестве члена торгового дома из далёкого города, или внушить, что вы из группы богатых торговцев.\n\nПосле принятия новой личности в качестве маскировки другие существа верят, что вы являетесь этой личностью, пока не подадите очевидный повод решить обратное.', 
              9),
            f('impostor', 
              'Impostor', 
              'Самозванец', 
              'You gain the ability to unerringly mimic another person\'s speech, writing, and behavior. You must spend at least three hours studying these three components of the person\'s behavior, listening to speech, examining handwriting, and observing mannerisms.\n\nYour ruse is indiscernible to the casual observer. If a wary creature suspects something is amiss, you have advantage on any Charisma (Deception) check you make to avoid detection.', 
              'Вы получаете способность безошибочно подражать чужой речи, почерку и привычкам. Вы должны провести не менее трёх часов изучения этих трёх компонентов поведения существа, слушая его речь, рассматривая почерк и наблюдая за привычками.\n\nВаши уловки не видны для случайного наблюдателя. Если осторожное существо подозревает что-то неладное, вы совершаете с преимуществом все проверки Харизмы (Обман), чтобы избежать обнаружения.', 
              13),
            f('death_strike', 
              'Death Strike', 
              'Смертельный удар', 
              'You become a master of instant death. When you attack and hit a creature that is surprised, it must make a Constitution saving throw (DC 8 + your Dexterity modifier + your proficiency bonus). On a failed save, double the damage of your attack against the creature.', 
              'Вы становитесь мастером мгновенной смерти. Если вы атакуете и попадаете по существу, захваченному врасплох, оно должно совершить спасбросок Телосложения (Сложность 8 + ваш модификатор Ловкости + ваш бонус мастерства). Проваленный спасбросок означает удвоение урона от вашей атаки по этому существу.', 
              17)
        ], 'PHB'),

        // 4. Scout
        sc('scout', 'Scout', 'Скаут', [
            f('skirmisher', 
              'Skirmisher', 
              'Зачинщик', 
              'You are difficult to pin down during a fight. You can move up to half your speed as a reaction when an enemy ends its turn within 5 feet of you. This movement doesn\'t provoke opportunity attacks.', 
              'К вам трудно подобраться во время боя. Вы можете реакцией переместиться на расстояние до половины вашей скорости, когда враг заканчивает свой ход в пределах 5 футов от вас. Это передвижение не вызывает провоцированных атак по вам.', 
              3,
              'You can move up to half your speed as a reaction when an enemy ends its turn within 5 feet of you, without provoking opportunity attacks.',
              'Вы можете использовать реакцию, чтобы переместиться на расстояние до половины вашей скорости, когда враг заканчивает ход рядом с вами, не вызывая провоцированных атак.'
            ),
            f('survivalist', 
              'Survivalist', 
              'Выживальщик', 
              'You gain proficiency in the Nature and Survival skills if you don\'t already have it. Your proficiency bonus is doubled for any ability check you make that uses either of those proficiencies.', 
              'Вы получаете владение навыками Природа и Выживание, если вы ещё не владеете ими. Ваш бонус мастерства удваивается при любых проверках характеристик, совершённых с использованием любого из этих навыков.', 
              3,
              'You gain proficiency in the Nature and Survival skills, and your proficiency bonus is doubled for checks using them.',
              'Вы получаете владение навыками Природа и Выживание, и ваш бонус мастерства удваивается для проверок с их использованием.'
            ),
            f('superior_mobility', 
              'Superior Mobility', 
              'Превосходная мобильность', 
              'Your walking speed increases by 10 feet. If you have a climbing or swimming speed, this increase applies to that speed as well.', 
              'Ваша скорость ходьбы увеличивается на 10 футов. Если у вас есть скорость лазания или плавания, это увеличение также затрагивает и их.', 
              9,
              'Your walking speed increases by 10 feet. This increase also applies to your swimming and climbing speeds.',
              'Ваша скорость ходьбы увеличивается на 10 футов. Это увеличение также применяется к скорости плавания и лазания.'
            ),
            f('ambush_master', 
              'Ambush Master', 
              'Мастер засад', 
              'You excel at leading ambushes and acting first in a fight. You have advantage on initiative rolls. In addition, the first creature you hit during the first round of a combat becomes easier for you and others to strike; attack rolls against that target have advantage until the start of your next turn.', 
              'Вы превосходно руководите засадами и действуете первым в бою. Вы совершаете броски инициативы с преимуществом. В дополнение к этому, по первому существу, по которому вы попадаете в первый раунд боя, становится легче попасть другим: броски атаки по такой цели совершаются с преимуществом до начала вашего следующего хода.', 
              13,
              'Advantage on initiative. The first creature you hit in the first round grants advantage on attacks against it until your next turn.',
              'Преимущество на инициативу. Первая цель, которую вы поразили в первом раунде, дает преимущество на атаки по ней до вашего следующего хода.'
            ),
            f('sudden_strike', 
              'Sudden Strike', 
              'Внезапный удар', 
              'You can strike with deadly speed. If you take the Attack action on your turn, you can make one additional attack as a bonus action. This attack can benefit from your Sneak Attack even if you have already used it this turn, but you can\'t use your Sneak Attack against the same target more than once in a turn.', 
              'Вы можете наносить удары со смертоносной скоростью. Если в свой ход вы совершаете действие Атака, то можете совершить одну дополнительную атаку бонусным действием. К этой дополнительной атаке может применяться умение «Скрытая атака», даже если вы уже использовали его в этот ход, но вы не можете применять скрытую атаку против одной и той же цели более одного раза за ход.', 
              17,
              'You can make an additional attack as a bonus action. This attack can benefit from Sneak Attack even if you already used it this turn.',
              'Вы можете совершить дополнительную атаку бонусным действием. К ней можно применить Скрытую атаку, даже если вы уже использовали ее в этот ход.'
            )
        ], 'XGE', 
        'You are skilled in stealth and surviving far from the streets of a city, allowing you to scout ahead of your companions during expeditions. Rogues who embrace this archetype are at home in the wilderness and among barbarians and rangers, and many Scouts serve as the eyes and ears of war bands. Ambusher, spy, bounty hunter - these are just a few of the roles that Scouts assume as they range the world.',
        'Вы обучены скрываться и выживать вдали от городских улиц, что позволяет вам во время экспедиций идти на разведку впереди своих компаньонов. Плуты, выбирающие этот архетип, чувствуют себя как дома в дикой местности среди варваров и следопытов, и многие скауты служат глазами и ушами военных отрядов. Налётчик, шпион, охотник за головами — вот лишь некоторые из ролей, которые играют скауты, бродя по свету.'
        ),

        // 5. Swashbuckler (Дуэлянт)
        sc('swashbuckler', 'Swashbuckler', 'Дуэлянт', [
            f('fancy_footwork', 
              'Fancy Footwork', 
              'Ловкое маневрирование', 
              'You learn how to land a strike and then slip away without reprisal. During your turn, if you make a melee attack against a creature, that creature can\'t make opportunity attacks against you for the rest of your turn.', 
              'Вы узнаёте, как наносить удары и сразу же ускользать от контратаки. На протяжении вашего хода, если вы совершаете рукопашную атаку по существу, то до конца вашего хода это существо не может совершать провоцированные атаки против вас.', 
              3,
              'Melee attack against a creature prevents it from making opportunity attacks against you until the end of your turn.',
              'Рукопашная атака по существу запрещает ему совершать по вам спровоцированные атаки до конца вашего хода.'
            ),
            f('rakish_audacity', 
              'Rakish Audacity', 
              'Лихая удаль', 
              'Your confidence propels you into battle. You can give yourself a bonus to your initiative rolls equal to your Charisma modifier.\n\nYou also gain an additional way to use your Sneak Attack; you don\'t need advantage on the attack roll to use your Sneak Attack against a creature if you are within 5 feet of it, no other creatures are within 5 feet of you, and you don\'t have disadvantage on the attack roll. All the other rules for Sneak Attack still apply.', 
              'Вы бросаетесь в бой смело и без колебаний. Вы добавляете свой модификатор Харизмы к результату броска инициативы. Кроме того, теперь для использования скрытой атаки вам не требуется совершать с преимуществом бросок атаки по существу, если оно находится в 5 футов от вас, в пределах 5 футов от вас больше нет других существ и у вас нет помехи на этот бросок. Все прочие правила для классового умения «Скрытая атака» применяются к вам как обычно.', 
              3,
              'Add Charisma modifier to initiative. Use Sneak Attack without advantage if you are within 5 feet of your target and no other creatures are nearby.',
              'Добавляйте модификатор Харизмы к инициативе. Можно использовать Скрытую атаку без преимущества, если вы в 5 футах от цели и рядом нет других существ.'
            ),
            f('panache', 
              'Panache', 
              'Щегольство', 
              'Your charm becomes extraordinarily beguiling. As an action, you can make a Charisma (Persuasion) check contested by a creature\'s Wisdom (Insight) check. The creature must be able to hear you, and the two of you must share a language.\n\nIf you succeed on the check and the creature is hostile to you, it has disadvantage on attack rolls against targets other than you and can\'t make opportunity attacks against targets other than you. This effect lasts for 1 minute, until one of your companions attacks the target or affects it with a spell, or until you and the target are more than 60 feet apart.\n\nIf you succeed on the check and the creature isn\'t hostile to you, it is charmed by you for 1 minute. While charmed, it regards you as a friendly acquaintance. This effect ends immediately if you or your companions do anything harmful to it.', 
              'Ваше обаяние становится необычайно привлекательным. Вы можете действием провести состязание вашей Харизмы (Убеждение) против Мудрости (Проницательность) существа. Существо должно слышать вас и понимать ваш язык.\n\nЕсли вы преуспеваете в этом состязании и существо враждебно к вам, оно совершает с помехой броски атаки по другим целям, кроме вас, и не может совершать провоцированные атаки по другим целям, кроме вас. Этот эффект длится 1 минуту, пока ваш союзник не атакует вашу цель, не воздействует на неё заклинанием или цель не удалится от вас на 60 или более футов.\n\nЕсли вы преуспеваете в этом состязании и существо не враждебно к вам, оно очаровано вами на 1 минуту. Пока существо очаровано, оно считает вас дружественным к себе. Этот эффект заканчивается немедленно, если вы или ваши союзники причините цели вред.', 
              9,
              'Action: Charisma (Persuasion) check against a target\'s Wisdom (Insight). Hostile creatures have disadvantage on attacks against others; neutral creatures are charmed.',
              'Действие: проверка Харизмы (Убеждение) против Мудрости (Проницательность). Враги атакуют других с помехой; нейтральные существа становятся очарованы.'
            ),
            f('elegant_maneuver', 
              'Elegant Maneuver', 
              'Элегантный манёвр', 
              'You can use a bonus action on your turn to gain advantage on the next Dexterity (Acrobatics) or Strength (Athletics) check you make during the same turn.', 
              'В свой ход вы можете использовать бонусное действие для того, чтобы совершить с преимуществом следующую проверку Ловкости (Акробатика) или Силы (Атлетика) на протяжении этого хода.', 
              13,
              'Bonus Action: Gain advantage on the next Dexterity (Acrobatics) or Strength (Athletics) check you make during the turn.',
              'Бонусное действие: преимущество на следующую проверку Ловкости (Акробатика) или Силы (Атлетика) до конца хода.'
            ),
            f('master_duelist', 
              'Master Duelist', 
              'Мастер дуэлянт', 
              'Your mastery of the blade lets you turn failure into success in combat. If you miss with an attack roll, you can roll it again with advantage. Once you do so, you can\'t use this feature again until you finish a short or long rest.', 
              'Ваше мастерство фехтования позволяет вам обратить провал в успех в бою. Если вы промахиваетесь при броске атаки, вы можете совершить бросок снова с преимуществом. Использовав это умение, вы не можете использовать его повторно до окончания короткого или продолжительного отдыха.', 
              17,
              'Reroll a missed attack with advantage once per short or long rest.',
              'Перебросьте промах атаки с преимуществом один раз за короткий или продолжительный отдых.'
            )
        ], 'XGE', 
        'Your focus is on the art of the blade, relying on speed, elegance, and charm in equal parts. While some warriors are brutes in heavy armor, your method of fighting is more like a performance. Swashbucklers and pirates typically follow this archetype, excelling in one-on-one duels and staying just out of reach of their opponents.',
        'Ваше воинское искусство в равной степени опирается как на мастерство фехтования и скорость, так и на элегантность и харизму. В то время, как некоторые воины — громилы в тяжёлых доспехах, ваш метод вести бой больше похож на выступление. Дуэлянты и пираты обычно принадлежат к этому архетипу. Дуэлянты имеют преимущество в поединках один на один, фехтуя двумя руками и держась на безопасном расстоянии от оппонента.'
        ),

        // 6. Inquisitive
        sc('inquisitive', 'Inquisitive', 'Сыщик', [
            f('ear_for_deceit', 
              'Ear for Deceit', 
              'Слух на обман', 
              'Whenever you make a Wisdom (Insight) check to determine whether a creature is lying, treat a roll of 7 or lower on the d20 as an 8.', 
              'Когда вы совершаете проверку Мудрости (Проницательность), чтобы распознать, обманывает ли существо, считайте выпавшие на к20 результаты «7» и ниже за «8».', 
              3),
            f('eye_for_detail', 
              'Eye for Detail', 
              'Внимательный взгляд', 
              'You can use a bonus action on your turn to make a Wisdom (Perception) check to spot a hidden creature or object or to make an Intelligence (Investigation) check to uncover or decipher clues.', 
              'Вы можете бонусным действием совершить проверку Мудрости (Восприятие) с целью заметить спрятанное существо или предмет, либо проверку Интеллекта (Расследование) с целью найти или расшифровать улики.', 
              3),
            f('insightful_fighting', 
              'Insightful Fighting', 
              'Проницательный бой', 
              'As a bonus action, you can make a Wisdom (Insight) check against a creature you can see that isn\'t incapacitated, contested by the target\'s Charisma (Deception) check. If you succeed, you can use your Sneak Attack against that target even if you don\'t have advantage on the attack roll, but not if you have disadvantage on it. This benefit lasts for 1 minute or until you successfully use this feature against a different target.', 
              'Бонусным действием вы можете совершить проверку Мудрости (Проницательность) против существа, которое вы видите и которое не недееспособно, против проверки Харизмы (Обман) цели. При успехе вы можете использовать скрытую атаку против цели даже если у вас нет преимущества на бросок атаки, кроме случая, если у вас помеха на этот бросок.\n\nЭтот эффект длится 1 минуту либо до тех пор, когда вы успешно используете это умение против другой цели.', 
              3),
            f('steady_eye', 
              'Steady Eye', 
              'Неторопливый взгляд', 
              'You have advantage on any Wisdom (Perception) or Intelligence (Investigation) check if you move no more than half your speed on the same turn.', 
              'Вы совершаете с преимуществом все проверки Мудрости (Восприятие) и Интеллекта (Расследование), если в текущем ходу вы перемещались не более, чем на половину своей скорости.', 
              9),
            f('unerring_eye', 
              'Unerring Eye', 
              'Безошибочный взгляд', 
              'As an action, you sense the presence of illusions, shapechangers not in their original form, and other magic designed to deceive the senses within 30 feet of you, provided you aren\'t blinded or deafened. You sense that an effect is attempting to trick you, but you gain no insight into what is hidden or its true nature. You can use this feature a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses of it when you finish a long rest.', 
              'Действием вы можете почувствовать наличие иллюзий, перевёртышей не в их первоначальной форме и прочей магии, предназначенной для обмана чувств, в пределах 30 футов от себя, если вы в этот момент не ослеплены и не оглушены. Вы чувствуете, что присутствует какой-то направленный на обман чувств эффект, но не знаете, что именно сокрыто или какова его истинная природа.\n\nВы можете использовать это умение количество раз, равное модификатору вашей Мудрости (минимум 1), и восстанавливаете потраченные использования после окончания продолжительного отдыха.', 
              13),
            f('eye_for_weakness', 
              'Eye for Weakness', 
              'Взгляд на слабость', 
              'While your Insightful Fighting feature applies to a creature, your Sneak Attack damage against that creature increases by 3d6.', 
              'Пока против существа действует ваше умение «Проницательный бой», урон от вашей «Скрытой атаки» против этого существа увеличиваются на 3к6.', 
              17)
        ]),

        // 7. Mastermind
        sc('mastermind', 'Mastermind', 'Комбинатор', [
            f('master_of_intrigue', 
              'Master of Intrigue', 
              'Интриган', 
              'You gain proficiency with the disguise kit, the forgery kit, and one gaming set of your choice. You also learn two languages of your choice.\n\nAdditionally, you can unerringly mimic the speech patterns and accent of a creature that you hear speak for at least 1 minute, enabling you to pass yourself off as a native speaker of a particular land, provided that you know the language.', 
              'Вы получаете владение набором для грима, набором фальсификатора и одним игровым набором на ваш выбор. Вы также изучаете два языка на ваш выбор.\n\nКроме того, вы можете безошибочно имитировать речевые обороты и акцент существа, речь которого вы слушали не менее 1 минуты, что позволяет вам выдать себя за коренного жителя определённой земли, при условии, что вы знаете этот язык.', 
              3),
            f('master_of_tactics', 
              'Master of Tactics', 
              'Мастер тактики', 
              'You can use the Help action as a bonus action. Additionally, when you use the Help action to aid an ally in attacking a creature, the target of that attack can be within 30 feet of you, rather than within 5 feet of you, if the target can see or hear you.', 
              'Вы можете использовать действие Помощь как бонусное действие. Кроме того, когда вы используете действие Помощь для содействия союзнику в атаке существа, цель этой атаки может находиться в пределах 30 футов от вас, а не 5 футов, если цель может видеть или слышать вас.', 
              3),
            f('insightful_manipulator', 
              'Insightful Manipulator', 
              'Проницательный манипулятор', 
              'If you spend at least 1 minute observing or interacting with another creature outside combat, you can learn certain information about its capabilities compared to your own. The DM tells you if the creature is your equal, superior, or inferior in regard to two of the following characteristics of your choice:\n- Intelligence score\n- Wisdom score\n- Charisma score\n- Class levels (if any)', 
              'Если вы проводите не менее 1 минуты, наблюдая или взаимодействуя с другим существом вне боя, вы можете узнать определённую информацию о его способностях по сравнению с вашими. Мастер сообщает вам, является ли существо равным, превосходящим или уступающим вам в отношении двух из следующих характеристик на ваш выбор:\n- Значение Интеллекта\n- Значение Мудрости\n- Значение Харизмы\n- Уровни в классе (если есть)', 
              9),
            f('misdirection', 
              'Misdirection', 
              'Перенаправление', 
              'You can sometimes cause another creature to suffer an attack meant for you. When you are targeted by an attack while a creature within 5 feet of you is granting you cover against that attack, you can use your reaction to have the attack target that creature instead of you.', 
              'Вы иногда можете заставить другое существо принять на себя атаку, предназначенную вам. Когда вы становитесь целью атаки, и существо в пределах 5 футов от вас даёт вам укрытие от этой атаки, вы можете реакцией перенаправить атаку на это существо вместо себя.', 
              13),
            f('soul_of_deceit', 
              'Soul of Deceit', 
              'Душа обмана', 
              'Your thoughts can\'t be read by telepathy or other means unless you allow it. You can present false thoughts by succeeding on a Charisma (Deception) check contested by the mind reader\'s Wisdom (Insight) check.\n\nAdditionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful if you so choose, and you can\'t be compelled to tell the truth by magic.', 
              'Ваши мысли нельзя прочитать с помощью телепатии или других средств, если вы не позволите это. Вы можете предоставить ложные мысли, преуспев в проверке Харизмы (Обман) против проверки Мудрости (Проницательность) читающего мысли.\n\nКроме того, независимо от того, что вы говорите, магия, определяющая, говорите ли вы правду, показывает, что вы говорите правду, если вы этого хотите, и вас нельзя заставить говорить правду с помощью магии.', 
              17)
        ]),

        // 8. Phantom
        sc('phantom', 'Phantom', 'Фантом', [
            f('whispers_of_the_dead', 
              'Whispers of the Dead', 
              'Шёпот мёртвых', 
              'Echoes of those who have died cling to you. Whenever you finish a short or long rest, you can choose one skill or tool proficiency that you lack and gain it, as a ghostly presence shares its knowledge with you. You lose this proficiency when you use this feature to choose a different proficiency that you lack.', 
              'Отголоски тех, кто умер, окутывают вас. Каждый раз, когда вы заканчиваете короткий или продолжительный отдых, призрачная сущность делится с вами знаниями, позволяя получить владение одним навыком или инструментом, которым вы ещё не владеете. Вы теряете это владение при использовании этого умения для замены владения на другое.', 
              3,
              'Whenever you finish a short or long rest, you gain proficiency in one skill or tool of your choice until you choose another.',
              'Каждый раз, когда вы заканчиваете короткий или продолжительный отдых, вы получаете владение одним навыком или инструментом на ваш выбор, пока не выберете другой.'
            ),
            f('wails_from_the_grave', 
              'Wails from the Grave', 
              'Могильные вопли', 
              'As you nudge someone closer to the grave, you can channel the power of death to harm someone else as well. Immediately after you deal your Sneak Attack damage to a creature on your turn, you can target a second creature that you can see within 30 feet of the first creature. Roll half the number of Sneak Attack dice for your level (round up), and the second creature takes necrotic damage equal to the roll\'s total, as wails of the dead sound around it for a moment.\n\nYou can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.', 
              'Когда из-за вас противник оказывается на волосок от гибели, вы можете направить силу смерти и нанести урон кому-то ещё. Сразу после того, как вы нанесёте урон «Скрытой атакой» по существу в свой ход, вы можете выбрать целью второе существо, которое вы видите в пределах 30 футов от первого существа. Совершите бросок половины костей «Скрытой атаки» на вашем уровне (с округлением в большую сторону), и второе существо получит урон некротической энергией, равный выпавшему на костях значению. На мгновение вокруг него будут слышны вопли мёртвых.\n\nВы можете использовать это умение количество раз, равное вашему бонусу мастерства. Вы восстанавливаете все потраченные использования после окончания продолжительного отдыха.', 
              3,
              'When you deal Sneak Attack damage, you can target a second creature within 30 feet to take necrotic damage equal to half your Sneak Attack dice.',
              'Когда вы наносите урон Скрытой атакой, вы можете выбрать второе существо в пределах 30 футов, которое получит урон некротической энергией, равный половине костей Скрытой атаки.'
            ),
            f('tokens_of_the_departed', 
              'Tokens of the Departed', 
              'Частица души усопшего', 
              'When a life ends in your presence, you\'re able to snatch a token from the departing soul, a sliver of its life essence that takes physical form: as a reaction when a creature you can see dies within 30 feet of you, you can open your free hand and create a Tiny trinket, a Soul Trinket. The DM determines the form of this trinket, or you can roll on the Trinkets table.\n\nYou can have a maximum number of Soul Trinkets equal to your proficiency bonus, and you can\'t create a new one while at your maximum.\n\nYou can use Soul Trinkets in the following ways:\n\n* While a Soul Trinket is on your person, you have advantage on death saving throws and Constitution saving throws, for your vitality is enhanced by the life essence within the object.\n* When you deal Sneak Attack damage on your turn, you can destroy one of your Soul Trinkets that is on your person and then immediately use Wails from the Grave, without expending a use of that feature.\n* As an action, you can destroy one of your Soul Trinkets, no matter where it is located. When you do so, you can ask the spirit associated with the trinket one question. The spirit appears to you and answers in a language it knew in life. It\'s under no obligation to be truthful, and it answers as concisely as possible, eager to be free. The spirit knows only what it knew in life, as determined by the DM.', 
              'Когда в вашем присутствии кто-то умирает, вы можете запечатлеть частицу души этого существа в виде физической сущности. Когда существо, которое вы можете видеть в радиусе 30 футов от вас, погибает, вы можете реакцией открыть ладонь своей свободной руки и создать в ней Крошечную безделушку. Форму безделушки определяет Мастер, или вы можете совершить бросок по таблице «Безделушки» для её определения.\n\nМаксимальное количество подобных безделушек равно вашему бонусу мастерства, и вы не можете создавать новые, если достигли максимального количества.\n\nВы можете использовать безделушки следующим образом:\n\n* Пока безделушка находится у вас, вы совершаете с преимуществом спасброски от смерти и спасброски Телосложения, поскольку ваша жизненная сила возрастает за счёт сущности, содержащейся в этой безделушке.\n* Когда вы в свой ход наносите урон «Скрытой атакой», вы можете уничтожить одну из своих безделушек, находящихся при вас, а затем немедленно использовать умение «Могильные вопли» без расходования использований.\n* Действием вы можете уничтожить одну из своих безделушек вне зависимости от того, где она находится. Совершая это действие, вы можете задать один вопрос духу, заключенному в этой безделушке. Дух появляется перед вами и отвечает на языке, который он знал при жизни. Ответ не обязан быть правдивым, более того, он будет максимально кратким, так как дух стремится скорее покинуть этот мир. Дух знает только то, что он знал при жизни, по выбору Мастера.', 
              9,
              'Reaction when a creature dies within 30 feet: Create a Soul Trinket. While holding it, you have advantage on death and Constitution saving throws. You can destroy it to ask a question or use Wails from the Grave freely.',
              'Реакция, когда существо умирает в 30 футах: Создать Безделушку души. Пока она у вас, вы имеете преимущество на спасброски от смерти и Телосложения. Можно уничтожить её, чтобы задать вопрос или использовать Могильные вопли бесплатно.'
            ),
            f('ghost_walk', 
              'Ghost Walk', 
              'Призрачная походка', 
              'You can phase partially into the realm of the dead, becoming like a ghost. As a bonus action, you assume a spectral form. While in this form, you have a flying speed of 10 feet, you can hover, and attack rolls have disadvantage against you. You can also move through creatures and objects as if they were difficult terrain, but you take 1d10 force damage if you end your turn inside a creature or an object.\n\nYou stay in this form for 10 minutes or until you end it as a bonus action. To use this feature, you must destroy one of your Soul Trinkets.', 
              'Вы можете частично перейти в царство мёртвых, став подобием призрака. Бонусным действием вы принимаете призрачную форму. Находясь в этой форме, вы получаете скорость полёта, равную 10 футам, можете парить, а броски атаки по вам совершаются с помехой. Вы также можете перемещаться сквозь других существ и предметы, как если бы они были труднопроходимой местностью, но вы получите 1к10 урона силовым полем, если окончите ход внутри существа или объекта.\n\nВы остаётесь в этой форме 10 минут или до тех пор, пока не окончите её бонусным действием. Чтобы использовать это умение вновь, вы должны закончить продолжительный отдых или уничтожить одну из своих безделушек в качестве части бонусного действия для активации «Призрачной походки».', 
              13,
              'Bonus Action: Destroy a Soul Trinket to assume a spectral form for 10 minutes. You gain a flying speed of 10 feet, can hover, and attacks against you have disadvantage.',
              'Бонусное действие: Уничтожьте Безделушку души, чтобы принять призрачную форму на 10 минут. Вы получаете скорость полёта 10 футов, можете парить, а атаки по вам совершаются с помехой.'
            ),
            f('deaths_friend', 
              'Death\'s Friend', 
              'Друг смерти', 
              'Your association with death has become so close that you gain the following benefits:\n\n* When you use your Wails from the Grave, you can deal the necrotic damage to both the first and the second creature.\n* At the end of a long rest, a Soul Trinket appears in your hand if you have no Soul Trinkets, as the spirits of the dead are drawn to you.', 
              'Ваша связь со смертью стала настолько тесной, что вы получаете следующие преимущества:\n\n* Когда вы используете «Могильные вопли», вы можете нанести урон некротической энергией как первому, так и второму существу.\n* В конце продолжительного отдыха в вашей руке появляется безделушка, если у вас нет никаких безделушек, так как духи мертвецов тянутся к вам.', 
              17,
              'When you use Wails from the Grave, the first target also takes the necrotic damage. At the end of a long rest, if you have no Soul Trinkets, one appears in your hand.',
              'Когда вы используете Могильные вопли, первая цель также получает урон некротической энергией. В конце продолжительного отдыха, если у вас нет Безделушек души, одна появляется в вашей руке.'
            )
        ], 'TCE'),

        // 9. Soulknife
        sc('soulknife', 'Soulknife', 'Клинок души', [ // Renamed from Пси-клинок
    f('psionic_power_rogue',
      'Psionic Power',
      'Псионическая сила',
      'You harbor a wellspring of psionic energy within yourself. You have a pool of Psionic Energy dice (d6). You have a number of these dice equal to twice your proficiency bonus. You regain all your expended Psionic Energy dice when you finish a long rest. In addition, as a bonus action, you can regain one expended Psionic Energy die, but you can\'t do so again until you finish a short or long rest.\n\nThe size of your Psionic Energy dice increases at 5th level (d8), 11th level (d10), and 17th level (d12).\n\n**Psi-Bolstered Knack.** When your nonpsionic training fails you, your psionic power can help: if you fail an ability check using a skill or tool with which you have proficiency, you can roll one Psionic Energy die and add the number rolled to the check, potentially turning failure into success. You expend the die only if the roll succeeds.\n\n**Psychic Whispers.** You can establish telepathic communication with others—perfect for silent infiltration. As an action, choose one or more creatures you can see, up to a number of creatures equal to your proficiency bonus, and then roll one Psionic Energy die. For a number of hours equal to the number rolled, the chosen creatures can speak telepathically with you, and you can speak telepathically with them. To send or receive a message (no action required), you and the other creature must be within 1 mile of each other. A creature can\'t use this telepathy if it can\'t speak any languages, and a creature can end the telepathic connection at any time (no action required). You and the creature don\'t need to speak a common language to understand each other.\nThe first time you use this power after each long rest, you don\'t expend the Psionic Energy die. All other times you use the power, you expend the die.', 
      'В вас скрыт источник псионической энергии. Эта псионическая энергия представляется в виде костей псионической энергии к6. Количество имеющихся у вас костей псионической энергии равно вашему удвоенному бонусу мастерства. Вы восстанавливаете все израсходованные кости псионической энергии, когда заканчиваете продолжительный отдых. Кроме того, бонусным действием вы можете восстановить себе одну израсходованную кость псионической энергии, но не можете сделать это снова, пока не закончите короткий или продолжительный отдых.\n\nТип вашей кости псионической энергии меняется по мере роста уровня в этом классе: на 5-м уровне (к8), на 11-м уровне (к10) и на 17-м уровне (к12).\n\n**Пси-усиленная сноровка.** Если вы проваливаете проверку характеристики, используя навык или инструмент, которым владеете, вы можете совершить бросок кости псионической энергии и добавить выпавшее значение к значению, полученному при проверке, потенциально обращая провал в успех. Вы расходуете кость только в том случае, если бросок успешен.\n\n**Психический шёпот.** Действием выберите одно или нескольких существ, которых вы можете видеть — вы можете связаться с количеством существ, равном вашему бонусу мастерства или меньше, после чего бросьте кость псионической энергии. Результат броска определяет то, в течение скольких часов выбранные существа могут телепатически общаться с вами, а вы с ними (до 1 мили). Вы и другие существа должны быть на расстоянии не дальше 1 мили друг от друга. Существо не может использовать эту телепатию, если оно не может говорить ни на одном языке. Когда вы впервые используете эту способность после окончания продолжительного отдыха, вы не расходуете кость псионической энергии. Во всех остальных случаях кость расходуется.', 
      3,
      // NEW SHORT DESC
      'You get Psionic Energy dice (d6, scales with level). Use them for Psi-Bolstered Knack to boost failed checks or Psychic Whispers for telepathy.',
      'Вы получаете кости псионической энергии (к6, растет с уровнем). Используйте их для Пси-усиленной сноровки, чтобы улучшить проваленные проверки, или для Психического шёпота для телепатии.'
    ),
    f('psychic_blades',
      'Psychic Blades',
      'Психические клинки',
      'You can manifest your psionic power as shimmering blades of psychic energy. Whenever you take the Attack action, you can manifest a psychic blade from your free hand and make the attack with that blade. This magic blade is a simple melee weapon with the finesse and thrown properties. It has a normal range of 60 feet and no long range, and on a hit, it deals psychic damage equal to 1d6 plus the ability modifier you used for the attack roll. The blade vanishes immediately after it hits or misses its target, and it leaves no mark on its target if it deals damage.\n\nAfter you attack with the blade, you can make a melee or ranged weapon attack with a second psychic blade as a bonus action on the same turn, provided your other hand is free to create it. The damage die of this bonus attack is 1d4, instead of 1d6.', 
      'Вы можете проявлять свои псионические силы в виде мерцающих клинков из психической энергии. Когда вы собираетесь совершить действие Атака, вы можете проявить психический клинок в своей свободной руке и совершить атаку им. Этот магический клинок — простое рукопашное оружие, обладающее свойствами «фехтовальное» и «метательное». Его нормальная дистанция равна 60 футам, зоны максимальной дистанции у оружия нет. При попадании оно наносит урон психической энергией, равный 1к6 + модификатор характеристики, которую вы использовали для совершения броска атаки. Клинок мгновенно исчезает после попадания или промаха по цели.\n\nПосле того, как вы атакуете этим клинком, вы можете бонусным действием совершить рукопашную или дальнобойную атаку оружием, используя второй психический клинок при условии, что у вас свободна другая рука для его создания. Кость урона этой бонусной атаки равна 1к4, а не 1к6.', 
      3,
      // NEW SHORT DESC
      'Manifest psychic blades when you attack. They deal psychic damage. You can make a bonus action attack with a second blade.',
      'Вы можете материализовать психические клинки при атаке. Они наносят урон психической энергией. Вы можете совершить дополнительную атаку вторым клинком бонусным действием.'
    ),
    f('soul_blades',
      'Soul Blades',
      'Клинки души',
      'Your Psychic Blades are now an expression of your psi-infused soul, giving you these powers:\n\n**Homing Strikes.** If you make an attack roll with your Psychic Blades and miss the target, you can roll one Psionic Energy die and add the number rolled to the attack roll. If this causes the attack to hit, you expend the Psionic Energy die.\n\n**Psychic Teleportation.** As a bonus action, you manifest one of your Psychic Blades, expend one Psionic Energy die and roll it. You throw the blade at an unoccupied space you can see, up to a number of feet away equal to 10 times the number rolled. You then teleport to that space, and the blade vanishes.', 
      'Ваши Психические клинки теперь являются выражением вашей души, наполненной пси-энергией, и даруют вам следующие способности, расходующие ваши кости псионической энергии:\n\n**Самонаводящиеся удары.** Если вы совершаете бросок атаки, используя свои психические клинки, и промахиваетесь по цели, то вы можете совершить бросок одной кости псионической энергии и добавить выпавший результат к броску атаки. Если вы попадаете атакой с использованием этого бонуса, то ваша кость псионической энергии расходуется.\n\n**Психическая телепортация.** Бонусным действием вы проявляете один из своих психических клинков, расходуете кость псионической энергии и бросаете её, после чего вы мечете клинок в видимое вами свободное пространство на количество футов, не превышающее 10-кратный результат броска кости псионической энергии. После этого вы телепортируетесь в это пространство, а клинок исчезает.', 
      9,
      // NEW SHORT DESC
      'Use Homing Strikes to add a die to missed attacks. Use Psychic Teleportation to throw a blade and teleport to it.',
      'Используйте Наводящие удары, чтобы добавить кость к промахнувшейся атаке. Используйте Психическую телепортацию, чтобы метнуть клинок и телепортироваться к нему.'
    ),
    f('psychic_veil',
      'Psychic Veil',
      'Психическая завеса',
      'You can weave a veil of psychic static to mask yourself. As an action, you can magically become invisible, along with anything you are wearing or carrying, for 1 hour or until you dismiss this effect (no action required). This invisibility ends if you deal damage to a creature or if you force a creature to make a saving throw.\n\nOnce you use this feature, you can\'t do so again until you finish a long rest, unless you expend a Psionic Energy die to use this feature again.', 
      'Вы можете соткать завесу из психической энергии, которая укроет вас. Действием вы можете магическим образом стать невидимым вместе со всем, что вы несёте или носите, на 1 час или до тех пор, пока вы самостоятельно не окончите этот эффект (действия не требуется). Эта невидимость заканчивается раньше, если вы наносите существу урон или заставляете его совершить спасбросок.\n\nКогда вы используете действие подобным образом, вы не сможете сделать это вновь, пока не закончите продолжительный отдых или не потратите кость псионической энергии на повторное использование этого умения.', 
      13,
      // NEW SHORT DESC
      'Become invisible for 1 hour as an action. Ends if you deal damage or force a save. Free once per long rest.',
      'Станьте невидимым на 1 час действием. Заканчивается, если нанести урон или заставить сделать спасбросок. Бесплатно один раз за долгий отдых.'
    ),
    f('rend_mind',
      'Rend Mind',
      'Раздирание разума',
      'You can sweep your Psychic Blades directly through a creature\'s mind. When you use your Psychic Blades to deal Sneak Attack damage to a creature, you can force that target to make a Wisdom saving throw (DC 8 + your proficiency bonus + your Dexterity modifier). If the save fails, the target is stunned for 1 minute. The stunned target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n\nOnce you use this feature, you can\'t use it again until you finish a long rest, unless you expend three Psionic Energy dice to use it again.', 
      'Вы можете прорезать своими психическими клинками разум существа. Когда вы используете свои психические клинки, чтобы нанести урон от «Скрытой атаки» существу, вы можете заставить это существо совершить спасбросок Мудрости (Сл 8 + ваш бонус мастерства + ваш модификатор Ловкости). Если существо проваливает спасбросок, то оно становится ошеломлённым на 1 минуту. Ошеломлённое существо может повторять спасбросок в конце каждого своего хода, оканчивая на себе эффект при успехе.\n\nКогда вы используете умение подобным образом, вы не сможете сделать это вновь, пока не закончите продолжительный отдых или не потратите 3 кости псионической энергии на повторное использование этого умения.', 
      17,
      // NEW SHORT DESC
      'Deal Sneak Attack damage to stun a target (Wisdom save). It can repeat the save each turn.',
      'Нанесите урон Скрытой атакой, чтобы ошеломить цель (спасбросок Мудрости). Она может повторять спасбросок каждый ход.'
    )
], 'TCE')
    ] 
};

export default ROGUE;
