
import { ClassData } from '../../types';
import { f, sc } from '../dataHelpers';

const WIZARD_BASE = [
    f('spellcasting_wizard', 
      'Spellcasting', 
      'Использование заклинаний', 
      'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.\n\n**Cantrips.** You know three cantrips of your choice from the wizard spell list. You learn additional wizard cantrips of your choice at higher levels.\n\n**Spellbook.** At 1st level, you have a spellbook containing six 1st-level wizard spells of your choice. Your spellbook is the repository of the wizard spells you know, except your cantrips, which are fixed in your mind.\n\n**Preparing and Casting Spells.** To cast one of these spells, you must expend a slot of the spell\'s level or higher. You regain all expended spell slots when you finish a long rest. You prepare the list of wizard spells that are available for you to cast. To do so, choose a number of wizard spells from your spellbook equal to your Intelligence modifier + your wizard level (minimum of one spell). The spells must be of a level for which you have spell slots.\n\n**Spellcasting Ability.** Intelligence is your spellcasting ability for your wizard spells.\n\n**Ritual Casting.** You can cast a wizard spell as a ritual if that spell has the ritual tag and you have the spell in your spellbook. You don\'t need to have the spell prepared.\n\n**Spellcasting Focus.** You can use an arcane focus as a spellcasting focus for your wizard spells.', 
      'Как ученик тайной магии, вы обладаете книгой заклинаний, содержащей заклинания, показывающие первые проблески вашей истинной силы.\n\n**Заговоры.** Вы знаете три заговора на ваш выбор из списка заклинаний волшебника. Вы узнаёте дополнительные заговоры волшебника на более высоких уровнях.\n\n**Книга заклинаний.** На 1-м уровне у вас есть книга заклинаний, содержащая шесть заклинаний волшебника 1-го уровня на ваш выбор.\n\n**Подготовка и накладывание заклинаний.** Для накладывания одного из этих заклинаний вы должны потратить ячейку уровня заклинания или выше. Вы восстанавливаете все потраченные ячейки заклинаний по окончании продолжительного отдыха. Вы подготавливаете список заклинаний, доступных для накладывания. Для этого выберите количество заклинаний из вашей книги заклинаний, равное модификатору Интеллекта + ваш уровень волшебника (минимум одно). Уровень заклинаний не должен превышать уровень ячеек, имеющихся у вас.\n\n**Базовая характеристика.** Интеллект является вашей базовой характеристикой для заклинаний волшебника.\n\n**Ритуальное колдовство.** Вы можете накладывать заклинание волшебника как ритуал, если у этого заклинания есть метка ритуала и оно есть в вашей книге заклинаний. Вам не нужно иметь это заклинание подготовленным.\n\n**Фокусировка.** Вы можете использовать магическую фокусировку в качестве фокусировки для заклинаний волшебника.', 
      1),
    
    f('arcane_recovery', 
      'Arcane Recovery', 
      'Магическое восстановление', 
      'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. the spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.', 
      'Вы научились восстанавливать часть магической энергии, изучая свою книгу заклинаний. Один раз в день, когда вы заканчиваете короткий отдых, вы можете выбрать и восстановить затраченные ячейки заклинаний. Суммарный уровень ячеек не должен превышать половину вашего уровня волшебника (округляя в большую сторону), и ни одна ячейка не может быть 6-го уровня или выше.', 
      1),
    
    f('arcane_tradition', 
      'Arcane Tradition', 
      'Магическая традиция', 
      'When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic. Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.', 
      'На 2-м уровне вы выбираете магическую традицию, формирующую вашу практику магии. Ваш выбор даёт вам умения на 2-м, 6-м, 10-м и 14-м уровнях.', 
      2),
      
    f('ability_score_improvement_wizard', 
      'Ability Score Improvement', 
      'Увеличение характеристик', 
      'When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1.', 
      'При достижении 4-го, 8-го, 12-го, 16-го и 19-го уровней вы можете повысить значение одной из ваших характеристик на 2 или двух характеристик на 1.', 
      4),

    f('cantrip_formulas', 
      'Cantrip Formulas (Optional)', 
      'Формулы заговоров (Опц.)', 
      'You have scribed a set of arcane formulas in your spellbook that you can use to formulate a cantrip in your mind. Whenever you finish a long rest and consult those formulas in your spellbook, you can replace one wizard cantrip you know with another cantrip from the wizard spell list.', 
      'Вы записали набор магических формул в свою книгу заклинаний, которые вы можете использовать для формулирования заговора в своём уме. Всякий раз, когда вы заканчиваете длительный отдых и сверяетесь с этими формулами в своей книге заклинаний, вы можете заменить один известный вам заговор волшебника другим заговором из списка заклинаний волшебника.', 
      3),

    f('spell_mastery', 
      'Spell Mastery', 
      'Мастерство заклинаний', 
      'At 18th level, you have achieved such mastery over certain spells that you can cast them at will. Choose a 1st-level wizard spell and a 2nd-level wizard spell that are in your spellbook. You can cast those spells at their lowest level without expending a spell slot when you have them prepared. If you want to cast either spell at a higher level, you must expend a spell slot as normal. By spending 8 hours in study, you can exchange one or both of the spells you chose for different spells of the same levels.', 
      'На 18-м уровне вы достигаете такого мастерства в определённых заклинаниях, что можете накладывать их неограниченно. Выберите одно заклинание волшебника 1-го уровня и одно заклинание волшебника 2-го уровня, которые есть в вашей книге заклинаний. Вы можете накладывать эти заклинания на их минимальном уровне без траты ячеек заклинаний, если они у вас подготовлены. Если вы хотите наложить одно из этих заклинаний на более высоком уровне, вы должны потратить ячейку заклинаний как обычно. Потратив 8 часов на изучение, вы можете заменить одно или оба выбранных заклинания другими заклинаниями тех же уровней.', 
      18),
    
    f('signature_spells', 
      'Signature Spells', 
      'Фирменные заклинания', 
      'When you reach 20th level, you gain mastery over two powerful spells and can cast them with little effort. Choose two 3rd-level wizard spells in your spellbook as your signature spells. You always have these spells prepared, they don\'t count against the number of spells you have prepared, and you can cast each of them once at 3rd level without expending a spell slot. When you do so, you can\'t do so again until you finish a short or long rest. If you want to cast either spell at a higher level, you must expend a spell slot as normal.', 
      'Достигнув 20-го уровня, вы получаете власть над двумя мощными заклинаниями и можете накладывать их с небольшим усилием. Выберите два заклинания волшебника 3-го уровня из своей книги заклинаний в качестве своих фирменных заклинаний. У вас всегда подготовлены эти заклинания, они не учитываются в количестве подготовленных заклинаний, и вы можете наложить каждое из них один раз на 3-м уровне без траты ячейки заклинаний. Сделав это, вы не можете сделать это снова, пока не закончите короткий или длительный отдых. Если вы хотите наложить одно из этих заклинаний на более высоком уровне, вы должны потратить ячейку заклинаний как обычно.', 
      20),
];

export const WIZARD: ClassData = { 
    id: 'wizard', 
    name: { en: 'Wizard', ru: 'Волшебник' }, 
    hitDie: 6, 
    primaryAbility: ['int'], 
    savingThrows: ['int', 'wis'], 
    skillsChoice: { count: 2, options: ['arcana', 'history', 'insight', 'investigation', 'medicine', 'religion'] }, 
    features: WIZARD_BASE, 
    spellcastingAbility: 'int', 
    multiclassRequirements: [{ requirements: { int: 13 } }],
    subclasses: [
        // 1. School of Evocation
        sc('evocation', 'School of Evocation', 'Школа Воплощения', [
            f('evocation_savant', 
              'Evocation Savant', 
              'Мастер Воплощения', 
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an evocation spell into your spellbook is halved.', 
              'Начиная со 2-го уровня, золото и время, которые вы тратите на копирование заклинания школы Воплощения в свою книгу заклинаний, уменьшаются вдвое.', 
              2),
            f('sculpt_spells', 
              'Sculpt Spells', 
              'Построение заклинаний', 
              'Beginning at 2nd level, you can create pockets of relative safety within the effects of your evocation spells. When you cast an evocation spell that affects other creatures that you can see, you can choose a number of them equal to 1 + the spell\'s level. The chosen creatures automatically succeed on their saving throws against the spell, and they take no damage if they would normally take half damage on a successful save.', 
              'Начиная со 2-го уровня, когда вы накладываете разрушительное заклинание, то можете создать относительно безопасные участки внутри зоны поражения, которые оно не затрагивает. При накладывании заклинания школы Воплощения, воздействующего на других существ, которых вы видите, вы можете выбрать количество существ, равное 1 + уровень заклинания. Выбранные существа автоматически преуспевают в спасбросках от этого заклинания и не получают урона, если по описанию должны получить половину урона от заклинания при успешном спасброске.', 
              2,
              'Choose 1 + spell level creatures to auto-succeed save and take no damage.',
              'Выберите 1 + уровень заклинания существ: авто-успех спаса, нет урона.'
            ),
            f('potent_cantrip', 
              'Potent Cantrip', 
              'Мощный заговор', 
              'Starting at 6th level, your damaging cantrips affect even creatures that avoid the brunt of the effect. When a creature succeeds on a saving throw against your cantrip, the creature takes half the cantrip\'s damage (if any) but suffers no additional effect from the cantrip.', 
              'Начиная с 6-го уровня, ваши наносящие урон заговоры воздействуют даже на тех существ, которые избегают основного эффекта. Если существо преуспевает в спасброске от вашего заговора, оно получает половину урона от него (если есть), но не получает дополнительных эффектов от него.', 
              6),
            f('empowered_evocation', 
              'Empowered Evocation', 
              'Усиленное воплощение', 
              'Beginning at 10th level, you can add your Intelligence modifier to one damage roll of any wizard evocation spell you cast.', 
              'Начиная с 10-го уровня, при броске урона от заклинания школы Воплощения волшебника, наложенного вами, вы добавляете к одному броску урона свой модификатор Интеллекта.', 
              10),
            f('overchannel', 
              'Overchannel', 
              'Перегрузка', 
              'Starting at 14th level, you can increase the power of your simpler spells. When you cast a wizard spell of 1st through 5th level that deals damage, you can deal maximum damage with that spell. The first time you do so, you suffer no adverse effect. If you use this feature again before you finish a long rest, you take 2d12 necrotic damage for each level of the spell, immediately after you cast it. Each time you use this feature again before finishing a long rest, the necrotic damage per spell level increases by 1d12. This damage ignores resistance and immunity.', 
              'Начиная с 14-го уровня, вы можете увеличить силу своих простейших заклинаний. Когда вы накладываете наносящее урон заклинание волшебника от 1-го до 5-го уровня, вы можете нанести им максимальный урон.\n\nБез вреда для себя вы можете использовать это умение один раз. Если вы повторно используете это умение до окончания продолжительного отдыха, то получаете 2к12 урона некротической энергией за каждый уровень заклинания сразу после его накладывания. Каждый следующий раз при использовании данного умения до окончания продолжительного отдыха урон некротической энергией увеличивается на 1к12 за каждый уровень. Этот урон игнорирует сопротивление и иммунитет.', 
              14)
        ]),

        // 2. School of Conjuration
        sc('conjuration', 'School of Conjuration', 'Школа Вызова', [
            f('conjuration_savant', 
              'Conjuration Savant', 
              'Мастер созидания', 
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a conjuration spell into your spellbook is halved.', 
              'Начиная со 2-го уровня, золото и время, которое вы тратите на копирование заклинания школы Вызова в свою книгу заклинаний, уменьшаются вдвое.', 
              2),
            f('minor_conjuration', 
              'Minor Conjuration', 
              'Малый вызов', 
              'Starting at 2nd level when you select this school, you can use your action to conjure up an inanimate object in your hand or on the ground in an unoccupied space that you can see within 10 feet of you. This object can be no larger than 3 feet on a side and weigh no more than 10 pounds, and its form must be that of a nonmagical object that you have seen. The object is visibly magical, radiating dim light out to 5 feet. The object disappears after 1 hour, when you use this feature again, or if it takes or deals any damage.', 
              'Начиная со 2-го уровня, вы можете действием создать неодушевлённый предмет в своей руке или на земле в свободном пространстве, которое вы можете видеть, и которое расположено в пределах 10 футов от вас. Этот предмет не должен превышать в длину 3 фута (90 сантиметров) и весить более 10 фунтов, и его форма должна быть как у немагического предмета, который вы уже видели. Видно, что предмет магический, и он излучает тусклый свет в пределах 5 футов.\n\nПредмет исчезает через 1 час, когда вы используете это умение вновь, или когда он получает или наносит любой урон.', 
              2,
              'Action: Conjure inanimate object (max 3ft/10lbs). Lasts 1 hour.',
              'Действие: Создать предмет (макс 3фт/10фунт). 1 час.'
            ),
            f('benign_transposition', 
              'Benign Transposition', 
              'Безопасное перемещение', 
              'Starting at 6th level, you can use your action to teleport up to 30 feet to an unoccupied space that you can see. Alternatively, you can choose a space within range that is occupied by a Small or Medium creature. If that creature is willing, you both teleport, swapping places. Once you use this feature, you can\'t use it again until you finish a long rest or you cast a conjuration spell of 1st level or higher.', 
              'Начиная с 6-го уровня, вы можете действием телепортироваться на 30 футов в свободное пространство, которое можете видеть. В качестве альтернативы, вы можете выбрать пространство в пределах этого диапазона, занятое существом Маленького или Среднего размера. Если это существо согласно, вы оба телепортируетесь, меняясь местами. Использовав это умение один раз, вы не можете использовать его вновь до окончания продолжительного отдыха или пока не наложите заклинание школы Вызова 1-го уровня или выше.', 
              6,
              'Action: Teleport 30ft or swap with willing creature. Recharge on long rest or casting conjuration spell (1+).',
              'Действие: Телепорт 30фт или обмен местами. Перезарядка: Закл. Вызова (1+) или Долгий отдых.'
            ),
            f('focused_conjuration', 
              'Focused Conjuration', 
              'Фокусированный вызов', 
              'Beginning at 10th level, while you are concentrating on a conjuration spell, your concentration can\'t be broken as a result of taking damage.', 
              'Начиная с 10-го уровня, когда вы концентрируетесь на заклинании школы Вызова, ваша концентрация не может быть нарушена в результате получения урона.', 
              10,
              'Damage can\'t break concentration on conjuration spells.',
              'Урон не сбивает концентрацию на заклинаниях Вызова.'
            ),
            f('durable_summons', 
              'Durable Summons', 
              'Надёжный призыв', 
              'Starting at 14th level, any creature that you summon or create with a conjuration spell has 30 temporary hit points.', 
              'Начиная с 14-го уровня, все призванные или созданные вами заклинанием школы Вызова существа имеют 30 временных хитов.', 
              14,
              'Summoned creatures gain 30 temp HP.',
              'Призванные существа получают 30 врем. ХП.'
            )
        ]),

        // 3. School of Divination
        sc('divination', 'School of Divination', 'Школа Прорицания', [
            f('divination_savant',
              'Divination Savant',
              'Мастер Прорицания',
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a divination spell into your spellbook is halved.',
              'Начиная со 2-го уровня, золото и время, которое вы тратите на копирование заклинания школы Прорицания в свою книгу заклинаний, уменьшаются вдвое.',
              2),
            f('portent',
              'Portent',
              'Знамение',
              'Starting at 2nd level when you choose this school, glimpses of the future begin to press in on your awareness. When you finish a long rest, roll two d20s and record the numbers rolled. You can replace any attack roll, saving throw, or ability check made by you or a creature that you can see with one of these foretelling rolls. You must choose to do so before the roll, and you can replace a roll in this way only once per turn.\n\nEach foretelling roll can be used only once. When you finish a long rest, you lose any unused foretelling rolls.',
              'Начиная со 2-го уровня, когда вы выбираете эту школу, в вашем сознании возникают проблески будущего. Когда вы заканчиваете продолжительный отдых, сделайте два броска к20 и запишите их результаты. Вы можете заменить любой бросок атаки, спасбросок, или проверку характеристики, совершенную вами или существом, которое вы можете видеть, одним из этих бросков предсказания. Вы должны сделать выбор о том, что так поступаете, до броска, и вы можете заменить значение броска подобным путём только один раз за ход.\n\nКаждый бросок предсказания может быть использован только один раз. Когда вы заканчиваете продолжительный отдых, вы теряете все неиспользованные броски предсказания.',
              2,
              'Roll 2 d20s after Long Rest. Replace any roll with one of them (before rolling).',
              'Бросьте 2 к20 после Долгого отдыха. Замените любой бросок одним из них (до броска).'
            ),
            f('expert_divination',
              'Expert Divination',
              'Эксперт Прорицания',
              'Beginning at 6th level, casting divination spells comes so easily to you that it expends only a fraction of your spellcasting efforts. When you cast a divination spell of 2nd level or higher using a spell slot, you regain one expended spell slot. The slot you regain must be of a level lower than the spell you cast and can\'t be higher than 5th level.',
              'Начиная с 6-го уровня, вы так легко накладываете заклинания школы Прорицания, что расходуете лишь малую часть своих сил. Когда вы накладываете заклинание школы Прорицания 2-го уровня или выше, используя ячейку заклинаний, вы восстанавливаете одну уже израсходованную ячейку заклинаний. Восстанавливаемая ячейка должна быть ниже уровнем, чем заклинание, которое вы накладываете, и не может быть выше 5-го уровня.',
              6,
              'Regain lower-level slot when casting Divination spell (2nd+).',
              'Восстановите ячейку меньшего круга при накладывании Прорицания (2+ круг).'
            ),
            f('the_third_eye',
              'The Third Eye',
              'Третий Глаз',
              'Starting at 10th level, you can use your action to increase your powers of perception. When you do so, choose one of the following benefits, which lasts until you are incapacitated or you take a short or long rest. You can\'t use the feature again until you finish a rest.\n\n**Darkvision.** You gain darkvision out to a range of 60 feet.\n\n**Ethereal Sight.** You can see into the Ethereal Plane within 60 feet of you.\n\n**Greater Comprehension.** You can read any language.\n\n**See Invisibility.** You can see invisible creatures and objects within 10 feet of you that are within line of sight.',
              'Начиная с 10-го уровня, вы можете действием увеличить силу восприятия. Когда вы так поступаете, выберите одно преимущество, которое будет длиться, пока вы не станете недееспособны или пока вы не совершите короткий или продолжительный отдых. Вы не можете использовать это умение повторно, пока не завершите отдых.\n\n**Тёмное зрение.** Вы получаете тёмное зрение в пределах 60 футов.\n\n**Эфирный взгляд.** Ваше зрение простирается на Эфирный план в пределах 60 футов.\n\n**Большое понимание.** Вы можете читать на любых языках.\n\n**Видеть невидимое.** Вы можете видеть находящихся на линии обзора невидимых существ и предметы в пределах 10 футов.',
              10,
              'Action: Gain Darkvision, Ethereal Sight, Read All Languages, or See Invisibility (10ft).',
              'Действие: Получить Темное зрение, Эфирный взгляд, Чтение всех языков или Видеть невидимое (10фт).'
            ),
            f('greater_portent',
              'Greater Portent',
              'Великое Знамение',
              'Starting at 14th level, the visions in your dreams intensify and paint a more accurate picture in your mind of what is to come. You roll three d20s for your Portent feature, rather than two.',
              'Начиная с 14-го уровня, видения в ваших грёзах усиливаются и рисуют более точную картину того, что грядёт. Вы совершаете три броска к20 для вашего умения «Знамение» вместо двух.',
              14,
              'Roll 3 d20s for Portent.',
              'Бросьте 3 к20 для Знамения.'
            )
        ]),
        
        // 4. Bladesinging (TCoE)
        sc('bladesinging', 'Bladesinging', 'Песнь Клинка', [
            f('training_in_war_and_song', 
              'Training in War and Song', 
              'Обучение войне и песне', 
              'When you adopt this tradition at 2nd level, you gain proficiency with light armor, and you gain proficiency with one type of one-handed melee weapon of your choice. You also gain proficiency in the Performance skill if you don\'t already have it.', 
              'Когда вы выбираете эту традицию на 2-м уровне, вы получаете владение лёгкими доспехами, и вы получаете владение одним видом одноручного рукопашного оружия на ваш выбор. Вы также получаете владение навыком Выступление, если у вас его ещё нет.', 
              2),
            f('bladesong', 
              'Bladesong', 
              'Песнь клинка', 
              'Starting at 2nd level, you can invoke a secret elven magic called the Bladesong, provided that you aren\'t wearing medium or heavy armor or using a shield. It graces you with supernatural speed, agility, and focus.\n\nYou can use a bonus action to start the Bladesong, which lasts for 1 minute. It ends early if you are incapacitated, if you don medium or heavy armor or a shield, or if you use two hands to make an attack with a weapon. You can also dismiss the Bladesong at any time (no action required).\n\nWhile your Bladesong is active, you gain the following benefits:\n• You gain a bonus to your AC equal to your Intelligence modifier (minimum of +1).\n• Your walking speed increases by 10 feet.\n• You have advantage on Dexterity (Acrobatics) checks.\n• You gain a bonus to any Constitution saving throw you make to maintain your concentration on a spell. The bonus equals your Intelligence modifier (minimum of +1).\n\nYou can use this feature a number of times equal to your proficiency bonus, and you regain all expended uses of it when you finish a long rest.', 
              'Начиная со 2-го уровня, вы можете воззвать к секретной эльфийской магии, называемой Песнью клинка, при условии, что вы не носите средние или тяжёлые доспехи и не используете щит. Она одаряет вас сверхъестественной скоростью, ловкостью и концентрацией.\n\nВы можете использовать бонусное действие, чтобы начать Песнь клинка, которая длится 1 минуту. Она заканчивается раньше, если вы становитесь недееспособны, если вы надеваете средние или тяжёлые доспехи или щит, или если вы используете две руки для совершения атаки оружием. Вы также можете прекратить Песнь клинка в любое время (действие не требуется).\n\nПока ваша Песнь клинка активна, вы получаете следующие преимущества:\n• Вы получаете бонус к КД, равный вашему модификатору Интеллекта (минимум +1).\n• Ваша скорость ходьбы увеличивается на 10 футов.\n• Вы совершаете с преимуществом проверки Ловкости (Акробатика).\n• Вы получаете бонус к любому спасброску Телосложения, который вы совершаете для поддержания концентрации на заклинании. Бонус равен вашему модификатору Интеллекта (минимум +1).\n\nВы можете использовать это умение количество раз, равное вашему бонусу мастерства, и восстанавливаете все потраченные использования после окончания длительного отдыха.', 
              2),
            f('extra_attack_bladesinger', 
              'Extra Attack', 
              'Дополнительная атака', 
              'Starting at 6th level, you can attack twice, instead of once, whenever you take the Attack action on your turn. Moreover, you can cast one of your cantrips in place of one of those attacks.', 
              'Начиная с 6-го уровня, если вы совершаете действие Атака в свой ход, вы можете совершить две атаки вместо одной. Более того, вы можете наложить один из своих заговоров вместо одной из этих атак.', 
              6),
            f('song_of_defense', 
              'Song of Defense', 
              'Песнь защиты', 
              'Beginning at 10th level, you can direct your magic to absorb damage while your Bladesong is active. When you take damage, you can use your reaction to expend one spell slot and reduce that damage to you by an amount equal to five times the spell slot\'s level.', 
              'Начиная с 10-го уровня, вы можете направлять свою магию на поглощение урона, пока ваша Песнь клинка активна. Когда вы получаете урон, вы можете реакцией потратить одну ячейку заклинаний и уменьшить этот урон по вам на количество, равное уровню ячейки заклинания, умноженному на 5.', 
              10),
            f('song_of_victory', 
              'Song of Victory', 
              'Песнь победы', 
              'Starting at 14th level, you add your Intelligence modifier (minimum of +1) to the damage of your melee weapon attacks while your Bladesong is active.', 
              'Начиная с 14-го уровня, вы добавляете свой модификатор Интеллекта (минимум +1) к урону ваших рукопашных атак оружием, пока ваша Песнь клинка активна.', 
              14)
        ]),

        // 5. Order of Scribes (TCoE)
        sc('scribes', 'Order of Scribes', 'Орден Писцов', [
            f('wizardly_quill', 
              'Wizardly Quill', 
              'Волшебное перо', 
              'At 2nd level, as a bonus action, you can magically create a Tiny quill. It doesn\'t require ink, and the time you must spend to copy a spell into your spellbook equals 2 minutes per spell level if you use the quill for the transcription. You can erase anything you write with the quill if you wave the feather over the text as a bonus action.', 
              'На 2-м уровне вы можете бонусным действием магически создать Крошечное перо. Оно не требует чернил, и время, которое вы должны потратить на копирование заклинания в книгу заклинаний, равно 2 минутам за уровень заклинания, если вы используете перо. Вы можете стереть всё написанное пером, если помашете им над текстом бонусным действием.', 
              2),
            f('awakened_spellbook', 
              'Awakened Spellbook', 
              'Пробуждённая книга заклинаний', 
              'Using your spellbook as a focus, when you cast a wizard spell with a spell slot, you can temporarily replace its damage type with a type that appears in another spell in your spellbook, which magically alters the spell\'s formula for this casting only. The latter spell must be of the same level as the spell slot you expend.\n\nAlso, when you cast a wizard spell as a ritual, you can use the spell\'s normal casting time, rather than adding 10 minutes to it. Once you use this benefit, you can\'t do so again until you finish a long rest.', 
              'Используя книгу заклинаний как фокусировку, при накладывании заклинания волшебника ячейкой, вы можете временно заменить его тип урона на тип, встречающийся в другом заклинании в вашей книге (того же уровня). Это магически изменяет формулу только для этого накладывания.\n\nТакже, когда вы накладываете заклинание волшебника как ритуал, вы можете использовать обычное время накладывания заклинания, а не добавлять к нему 10 минут. 1 раз за долгий отдых.', 
              2),
            f('manifest_mind', 
              'Manifest Mind', 
              'Проявленный разум', 
              'At 6th level, you can conjure the mind of your Awakened Spellbook. As a bonus action, you can cause the mind to manifest as a Tiny spectral object. It can pass through creatures but not objects. It has darkvision 60ft, telepathy with you. You can see/hear through it. You can cast wizard spells as if they were in the spectral mind\'s space.', 
              'На 6-м уровне вы можете призвать разум вашей Пробуждённой книги. Бонусным действием вы можете заставить разум проявиться как Крошечный призрачный объект. Он может проходить сквозь существ. Тёмное зрение 60фт, телепатия с вами. Вы можете видеть/слышать через него. Вы можете накладывать заклинания волшебника, как если бы находились в пространстве призрачного разума.', 
              6),
            f('master_scrivener', 
              'Master Scrivener', 
              'Мастер-переписчик', 
              'At 10th level, whenever you finish a long rest, you can create one magic scroll by touching paper or parchment and using your Wizardly Quill. The scroll contains an enhanced version of one of your spells (1st or 2nd level, cast at +1 level).', 
              'На 10-м уровне, когда вы заканчиваете долгий отдых, вы можете создать один магический свиток (заклинание 1 или 2 уровня, накладывается на уровень выше).', 
              10),
            f('one_with_the_word', 
              'One with the Word', 
              'Единство со словом', 
              'At 14th level, your connection to your spellbook enables you to ignore damage. If you take damage while your Awakened Spellbook\'s mind is manifested, you can prevent all of that damage by using your reaction to dismiss the spectral mind. If you do so, you can\'t manifest the spectral mind again until you finish 1d6 long rests. Also, you can temporarily banish spells from your book to revive yourself if you drop to 0 HP (optional mechanic, usually simplified in apps).', 
              'На 14-м уровне, если вы получаете урон, пока разум Книги проявлен, вы можете реакцией предотвратить весь урон, отозвав призрачный разум. Восстановление разума: 1к6 долгих отдыхов.', 
              14)
        ]),

        // 6. War Magic (XGtE)
        sc('war_magic', 'War Magic', 'Военная магия', [
            f('arcane_deflection',
              'Arcane Deflection',
              'Магическое отражение',
              'At 2nd level, you have learned to weave your magic to fortify yourself against harm. When you are hit by an attack or you fail a saving throw, you can use your reaction to gain a +2 bonus to your AC against that attack or a +4 bonus to that saving throw.\n\nWhen you use this feature, you can\'t cast spells other than cantrips until the end of your next turn.',
              'Вы обучаетесь тому, как плести магию так, чтобы укрепить своё сопротивление всякому вреду. Когда по вам попадает атака или вы проваливаете спасбросок, вы можете реакцией получить бонус +2 к КД от этой атаки или бонус +4 к этому спасброску.\n\nКогда вы использовали это умение, вы не можете накладывать никаких заклинаний, кроме заговоров до конца своего следующего хода.',
              2,
              undefined, undefined 
            ),
            f('tactical_wit',
              'Tactical Wit',
              'Тактическая смекалка',
              'Starting at 2nd level, your ability to assess tactical situations allows you to act quickly in battle. You can give yourself a bonus to your initiative rolls equal to your Intelligence modifier.',
              'Ваша способность оценивать тактические ситуации позволяет вам действовать быстрее в бою. Вы можете получить бонус к броску инициативы равный вашему модификатору Интеллекта.',
              2,
              undefined, undefined
            ),
            f('power_surge',
              'Power Surge',
              'Всплеск мощи',
              'Starting at 6th level, you can store magical energy within yourself to later empower your damaging spells. In its stored form, this energy is called a power surge.\n\nYou can store a maximum number of power surges equal to your Intelligence modifier (minimum of one). Whenever you finish a long rest, your number of power surges resets to one. Whenever you successfully end a spell with Dispel Magic or Counterspell, you gain one power surge, as you steal magic from the spell you foiled. If you end a short rest with no power surges, you gain one power surge.\n\nOnce per turn when you deal damage to a creature or object with a wizard spell, you can spend one power surge to deal extra force damage to that target. The extra damage equals half your wizard level.',
              'Вы можете запасать магическую энергию внутри себя, чтобы позднее усилить ею свои наносящие урон заклинания. В состоянии такого запаса эта энергия называется «Всплеском мощи».\n\nМаксимальное число ваших запасённых всплесков мощи равно вашему модификатору Интеллекта (минимум один). Когда вы завершаете продолжительный отдых, число всплесков в вашем запасе становится равным одному. Когда вы успешно отменяете заклинание с использованием заклинаний рассеивание магии [dispel magic] или контрзаклинание [counterspell], вы получаете один всплеск мощи, так как вы забираете магию из заклинания, которое отменили. Если вы заканчиваете короткий отдых не имея запасённых всплесков мощи, вы получаете один в свой запас.\n\nОдин раз за ход, когда вы наносите урон существу или предмету заклинанием волшебника, вы можете потратить один всплеск мощи чтобы нанести дополнительный урон цели силовым полем. Дополнительный урон равен половине вашего уровня волшебника.',
              6,
              'Store magical energy to deal extra force damage.',
              'Запасайте магическую энергию, чтобы наносить дополнительный урон силовым полем.'
            ),
            f('durable_magic',
              'Durable Magic',
              'Стойкая магия',
              'Beginning at 10th level, the magic you channel helps ward off harm. While you maintain concentration on a spell, you have a +2 bonus to AC and all saving throws.',
              'Магия, которую вы поддерживаете, позволяет вам более эффективно защищаться. Пока вы поддерживаете концентрацию на заклинании, вы получаете бонус +2 к КД и всем спасброскам.',
              10,
              undefined, undefined
            ),
            f('deflecting_shroud',
              'Deflecting Shroud',
              'Отражающий покров',
              'At 14th level, your Arcane Deflection becomes infused with deadly magic. When you use your Arcane Deflection feature, you can cause magical energy to arc to up to three creatures of your choice that you can see within 60 feet of you. Each target takes force damage equal to half your wizard level.',
              'Ваше магическое отражение наделяется смертоносной магией. Когда вы используете своё умение «Магическое отражение», вы можете испустить разряды магической энергии. До трёх существ по вашему выбору, которых вы можете видеть в пределах 60 футов, получают урон силовым полем, равный половине вашего уровня волшебника каждое.',
              14,
              'Arcane Deflection deals force damage to nearby enemies.',
              'При использовании Магического отражения наносите урон силовым полем существам в пределах 60 футов.'
            )
        ]),

        // 7. Chronurgy Magic (EGtW)
        sc('chronurgy', 'Chronurgy Magic', 'Хронургия', [
            f('chronal_shift', 
              'Chronal Shift', 
              'Хрональный сдвиг', 
              'At 2nd level, you can magically exert limited control over the flow of time around a creature. As a reaction, after you or a creature you can see within 30 feet of you makes an attack roll, an ability check, or a saving throw, you can force the creature to reroll. You make this decision after you see whether the roll succeeds or fails. The target must use the result of the second roll. You can use this ability twice, and you regain any expended uses when you finish a long rest.', 
              'На 2-м уровне вы можете магически оказывать ограниченное влияние на течение времени. Реакцией, после того как вы или существо в 30 футах совершает бросок атаки, проверку или спасбросок, вы можете заставить перебросить кость. Вы принимаете решение после того, как узнаете результат. Цель обязана использовать второй результат. Использований: 2 (восст. долгий отдых).', 
              2),
            f('temporal_awareness', 
              'Temporal Awareness', 
              'Временная осведомлённость', 
              'Starting at 2nd level, you can add your Intelligence modifier to your initiative rolls.', 
              'Начиная со 2-го уровня, вы можете добавлять модификатор Интеллекта к броскам инициативы.', 
              2),
            f('momentary_stasis', 
              'Momentary Stasis', 
              'Мгновенный стазис', 
              'At 6th level, as an action, you can magically force a Large or smaller creature you can see within 60 feet of you to make a Constitution saving throw against your spell save DC. Unless the saving throw is a success, the creature is encased in a field of magical energy until the end of your next turn. While encased in this way, the creature is incapacitated and has a speed of 0. Uses = Int mod.', 
              'На 6-м уровне действием вы можете заставить существо (Большое или меньше) в 60 футах совершить спасбросок Телосложения. При провале оно заключено в поле энергии до конца вашего следующего хода (недееспособно, скорость 0). Использований: модификатор Интеллекта.', 
              6),
            f('arcane_abeyance', 
              'Arcane Abeyance', 
              'Магическая отсрочка', 
              'At 10th level, when you cast a spell using a spell slot of 4th level or lower, you can condense the spell\'s magic into a tiny gray bead. The spell is frozen in time at the moment of casting and held within the bead for 1 hour. A creature holding the bead can use its action to release the spell within, whereupon the bead disappears.', 
              'На 10-м уровне, когда вы накладываете заклинание 4-го уровня или ниже, вы можете сконденсировать его в серую бусину. Заклинание заморожено во времени на 1 час. Существо, держащее бусину, может действием высвободить заклинание.', 
              10),
            f('convergent_future', 
              'Convergent Future', 
              'Сходящееся будущее', 
              'At 14th level, you can peer through possible futures and magically pull one of them into events around you. When you or a creature you can see within 60 feet of you makes an attack roll, an ability check, or a saving throw, you can use your reaction to ignore the die roll and decide whether the number rolled is the minimum needed to succeed or one less than that number (your choice). When you use this feature, you gain one level of exhaustion. Only by finishing a long rest can you remove a level of exhaustion gained in this way.', 
              'На 14-м уровне вы можете заглянуть в возможные варианты будущего и притянуть один из них. Когда вы или существо в 60 футах совершает бросок, вы можете реакцией проигнорировать бросок и решить, будет ли результат минимально необходимым для успеха или на единицу меньше (успех или провал по выбору). При использовании вы получаете 1 уровень истощения.', 
              14)
        ]),

        // 8. School of Illusion (PHB)
        sc('illusion', 'School of Illusion', 'Школа Иллюзии', [
            f('illusion_savant',
              'Illusion Savant',
              'Мастер иллюзий',
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an illusion spell into your spellbook is halved.',
              'Начиная со 2-го уровня, золото и время, которые вы тратите на копирование заклинания школы Иллюзии в свою книгу заклинаний, уменьшаются вдвое.',
              2),
            f('improved_minor_illusion',
              'Improved Minor Illusion',
              'Улучшенная малая иллюзия',
              'When you choose this school at 2nd level, you learn the Minor Illusion cantrip. If you already know this cantrip, you learn a different wizard cantrip of your choice. The cantrip doesn\'t count against your number of cantrips known.\n\nWhen you cast Minor Illusion, you can create both a sound and an image with a single casting of the spell.',
              'На 2-м уровне вы узнаёте заговор Малая иллюзия. Если вы уже знаете этот заговор, вы узнаёте любой другой заговор волшебника на свой выбор. Этот заговор не учитывается в общем количестве известных вам заговоров.\n\nПри накладывании заклинания Малая иллюзия вы можете использовать эффекты звука и изображения вместе единым заклинанием.',
              2),
            f('malleable_illusions',
              'Malleable Illusions',
              'Пластичные иллюзии',
              'Starting at 6th level, when you cast an illusion spell that has a duration of 1 minute or longer, you can use your action to change the nature of that illusion (using the spell\'s normal parameters for the illusion), provided that you can see the illusion.',
              'Начиная с 6-го уровня, если вы наложили заклинание школы Иллюзии длительностью как минимум 1 минута, вы можете действием изменить характер этой иллюзии (используя обычные ограничения для этой иллюзии), при условии, что можете видеть эту иллюзию.',
              6),
            f('illusory_self',
              'Illusory Self',
              'Собственная иллюзорность',
              'Beginning at 10th level, you can create an illusory duplicate of yourself as an instant, almost instinctual reaction to danger. When a creature makes an attack roll against you, you can use your reaction to interpose the illusory duplicate between the attacker and yourself. The attack automatically misses you, then the illusion dissipates.\n\nOnce you use this feature, you can\'t use it again until you finish a short or long rest.',
              'Начиная с 10-го уровня, вы можете инстинктивно создать иллюзорную копию самого себя в ответ на внезапную опасность. Если существо совершает по вам бросок атаки, вы можете реакцией создать иллюзорную копию между атакующим и собой. Атака автоматически промахивается по вам и уничтожает иллюзию.\n\nПосле использования данного умения вы должны закончить короткий или продолжительный отдых, прежде чем сможете воспользоваться им вновь.',
              10),
            f('illusory_reality',
              'Illusory Reality',
              'Иллюзорная реальность',
              'By 14th level, you have learned the secret of weaving shadow magic into your illusions to give them a semi-reality. When you cast an illusion spell of 1st level or higher, you can choose one inanimate, nonmagical object that is part of the illusion and make that object real. You can do this on your turn as a bonus action while the spell is ongoing. The object remains real for 1 minute. For example, you can create an illusion of a bridge over a chasm and then make it real long enough for your allies to cross.\n\nThe object can\'t deal damage or otherwise directly harm anyone.',
              'К 14-му уровню вы постигли секреты плетения теневых заклятий, что делает ваши иллюзии наполовину реальными. Когда вы накладываете заклинание Иллюзии 1-го уровня или выше, вы можете выбрать любой неодушевлённый и немагический объект, являющийся частью данной иллюзии, чтобы сделать его реальным. Вы можете сделать это в свой ход бонусным действием, пока действует заклинание. Объект становится реальным на 1 минуту. Например, вы можете создать иллюзию моста через разлом и держать его реальным достаточно долго, чтобы ваши союзники могли по нему перебраться.\n\nОбъект не может причинять урон или непосредственно навредить кому-либо.',
              14)
        ]),
        
        // 9. School of Necromancy (PHB)
        sc('necromancy', 'School of Necromancy', 'Школа Некромантии', [
            f('necromancy_savant',
              'Necromancy Savant',
              'Мастер некромантии',
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a necromancy spell into your spellbook is halved.',
              'Начиная со 2-го уровня, золото и время, которое вы тратите на копирование заклинания школы Некромантии в свою книгу заклинаний, уменьшаются вдвое.',
              2),
            f('grim_harvest',
              'Grim Harvest',
              'Мрачная жатва',
              'At 2nd level, you gain the ability to reap life energy from creatures you kill with your spells. Once per turn when you kill one or more creatures with a spell of 1st level or higher, you regain hit points equal to twice the spell\'s level, or three times its level if the spell belongs to the School of Necromancy. You don\'t gain this benefit for killing constructs or undead.',
              'На 2-м уровне вы получаете возможность собирать жизненные силы существ, которых вы убиваете своими заклинаниями. Один раз за ход, когда вы убиваете одно или несколько существ заклинанием 1-го и более высокого уровня, вы восстанавливаете хиты в количестве, равном удвоенному уровню этого заклинания, или утроенному, если заклинание принадлежало школе Некромантии. Вы не получаете это преимущество, убивая конструктов и нежить.',
              2,
              'Kill creature with spell 1+: Regain HP equal to 2x spell level (3x if Necromancy).',
              'Убийство заклинанием 1+: Лечение 2х круг (3х если Некромантия).'
            ),
            f('undead_thralls',
              'Undead Thralls',
              'Неживые рабы',
              'At 6th level, you add the Animate Dead spell to your spellbook if it is not there already. When you cast Animate Dead, you can target one additional corpse or pile of bones, creating another zombie or skeleton, as appropriate.\n\nWhenever you create an undead using a necromancy spell, it has additional benefits:\n• The creature\'s hit point maximum is increased by an amount equal to your wizard level.\n• The creature adds your proficiency bonus to its weapon damage rolls.',
              'На 6-м уровне вы добавляете заклинание Восставший труп в свою книгу заклинаний, если его в ней ещё нет. Когда вы накладываете заклинание Восставший труп, вы можете сделать его целью один дополнительный труп или кучу костей, создавая зомби или скелета соответственно.\n\nКаждый раз, когда вы создаёте Нежить, используя заклинание школы Некромантии, она получает дополнительные преимущества:\n• Максимум хитов создаваемой Нежити увеличивается на значение, равное вашему уровню волшебника.\n• Создаваемые существа добавляют ваш бонус мастерства к броскам урона оружием.',
              6,
              'Animate Dead: +1 target. Undead get +HP (Wiz Lvl) and +PB to dmg.',
              'Восставший труп: +1 цель. Нежить: +ХП (Ур. Волш) и +БМ к урону.'
            ),
            f('inured_to_undeath',
              'Inured to Undeath',
              'Единение с не-жизнью',
              'Beginning at 10th level, you have resistance to necrotic damage, and your hit point maximum can\'t be reduced. You have spent so much time dealing with undead and the forces that animate them that you have become inured to some of their worst effects.',
              'Начиная с 10-го уровня, вы получаете сопротивление урону некротической энергией, и максимум ваших хитов уже не может уменьшаться. Вы провели так много времени в контакте с нежитью и оживляющей их энергией, что научились преодолевать их самые опасные побочные эффекты.',
              10,
              'Resistance to Necrotic damage. Max HP cannot be reduced.',
              'Сопротивление некротическому урону. Максимум хитов не может быть уменьшен.'
            ),
            f('command_undead',
              'Command Undead',
              'Управление нежитью',
              'Starting at 14th level, you can use magic to bring undead under your control, even those created by other wizards. As an action, you can choose one undead that you can see within 60 feet of you. That creature must make a Charisma saving throw against your wizard spell save DC. If it succeeds, you can\'t use this feature on it again. If it fails, it becomes friendly to you and obeys your commands until you use this feature again.\n\nIntelligent undead are harder to control in this way. If the target has an Intelligence of 8 or higher, it has advantage on the saving throw. If it fails the saving throw and has an Intelligence of 12 or higher, it can repeat the saving throw at the end of every hour until it succeeds and breaks free.',
              'На 14-м уровне вы можете магией подчинить себе нежить, даже если она создана другим волшебником. Вы можете действием выбрать одну нежить в пределах 60 футов от себя, которую можете видеть. Это существо должно совершить спасбросок Харизмы против Сл вашего заклинания волшебника. Если он успешен, вы не можете больше использовать это умение на данной цели. Если он провален, цель становится дружественной по отношению к вам и подчиняется вашим командам, пока вы не используете это умение снова.\n\nРазумную нежить сложнее контролировать таким образом. Если у цели Интеллект 8 или выше, она совершает спасбросок с преимуществом. Если она проваливает спасбросок и имеет Интеллект 12 или выше, она может повторять спасбросок в конце каждого часа, пока не преуспеет и не высвободится.',
              14,
              'Action: Control Undead (Cha save). Smart undead resist easier.',
              'Действие: Подчинить нежить (спас Хар). Умная нежить сопротивляется лучше.'
            )
        ]),
        
        // 10. School of Abjuration (PHB)
        sc('abjuration', 'School of Abjuration', 'Школа Ограждения', [
            f('abjuration_savant', 
              'Abjuration Savant', 
              'Мастер Ограждения', 
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an abjuration spell into your spellbook is halved.', 
              'Начиная со 2-го уровня, золото и время, которые вы тратите на копирование заклинания школы Ограждения в свою книгу заклинаний, уменьшаются вдвое.', 
              2),
            f('arcane_ward', 
              'Arcane Ward', 
              'Магическая защита', 
              'Starting at 2nd level, you can weave magic around yourself for protection. When you cast an abjuration spell of 1st level or higher, you can simultaneously create a magical ward on yourself that lasts until you finish a long rest. The ward has hit points equal to twice your wizard level + your Intelligence modifier. Whenever you take damage, the ward takes the damage instead. If this damage reduces the ward to 0 hit points, you take any remaining damage. While the ward has 0 hit points, it can\'t absorb damage, but its magic remains. Whenever you cast an abjuration spell of 1st level or higher, the ward regains a number of hit points equal to twice the level of the spell. Once you create the ward, you can\'t create it again until you finish a long rest.', 
              'Начиная со 2-го уровня, вы можете плести вокруг себя магию для защиты. Когда вы накладываете заклинание школы Ограждения 1-го уровня или выше, вы можете одновременно с этим создать магическую защиту, существующую до окончания продолжительного отдыха. Защита имеет хиты, равные вашему удвоенному уровню волшебника + модификатор Интеллекта. Когда вы получаете урон, его вместо вас получает защита. Если урон опускает хиты защиты до 0, то оставшийся урон получаете вы. Когда у защиты 0 хитов, она не может поглощать урон, но магия остаётся. Если вы накладываете заклинание школы Ограждения 1-го уровня или выше, защита восстанавливает хиты, равные удвоенному уровню заклинания. Единожды создав защиту, вы не можете создать её вновь, пока не закончите продолжительный отдых.', 
              2,
              'Cast Abjuration spell (1st+): Create Ward (HP = 2*Lvl + Int). Absorbs damage. Recharge on cast.',
              'Закл. Ограждения (1+): Щит (ХП = 2*Ур + Инт). Поглощает урон. Восст. при касте.'
            ),
            f('projected_ward', 
              'Projected Ward', 
              'Проекция защиты', 
              'Starting at 6th level, when a creature that you can see within 30 feet of you takes damage, you can use your reaction to cause your Arcane Ward to absorb that damage. If this damage reduces the ward to 0 hit points, the warded creature takes any remaining damage.', 
              'Начиная с 6-го уровня, когда видимое вами существо в пределах 30 футов получает урон, вы можете реакцией поглотить этот урон вашей Магической защитой. Если урон опускает хиты защиты до 0, защищаемое существо получает остаток урона.', 
              6,
              'Reaction: Arcane Ward absorbs damage for ally within 30ft.',
              'Реакция: Магическая защита поглощает урон союзника в 30фт.'
            ),
            f('improved_abjuration', 
              'Improved Abjuration', 
              'Улучшенное ограждение', 
              'Beginning at 10th level, when you cast an abjuration spell that requires you to make an ability check as part of casting that spell (as in Counterspell and Dispel Magic), you add your proficiency bonus to that ability check.', 
              'Начиная с 10-го уровня, когда вы накладываете заклинание школы Ограждения, требующее проверки характеристики (как Контрзаклинание или Рассеивание магии), вы добавляете к этой проверке бонус мастерства.', 
              10,
              'Add Proficiency Bonus to Counterspell/Dispel Magic checks.',
              'Добавить Бонус Мастерства к проверкам Контрзаклинания/Рассеивания.'
            ),
            f('spell_resistance', 
              'Spell Resistance', 
              'Сопротивление заклинаниям', 
              'Starting at 14th level, you have advantage on saving throws against spells. Furthermore, you have resistance against the damage of spells.', 
              'Начиная с 14-го уровня, вы совершаете спасброски от заклинаний с преимуществом. Кроме того, вы получаете сопротивление урону от заклинаний.', 
              14,
              'Advantage on saves vs spells. Resistance to spell damage.',
              'Преимущество на спасы от заклинаний. Сопротивление урону заклинаний.'
            )
        ]),

        // 11. School of Enchantment (PHB)
        sc('enchantment', 'School of Enchantment', 'Школа Очарования', [
            f('enchantment_savant',
              'Enchantment Savant',
              'Мастер Очарования',
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an enchantment spell into your spellbook is halved.',
              'Начиная со 2-го уровня, золото и время, которое вы тратите на копирование заклинания школы Очарования в свою книгу заклинаний, уменьшаются вдвое.',
              2),
            f('hypnotic_gaze',
              'Hypnotic Gaze',
              'Гипнотический взгляд',
              'Starting at 2nd level when you choose this school, your soft words and enchanting gaze can magically enthrall another creature. As an action, choose one creature that you can see within 5 feet of you. If the target can see or hear you, it must succeed on a Wisdom saving throw against your wizard spell save DC or be charmed by you until the end of your next turn. The charmed creature\'s speed drops to 0, and the creature is incapacitated and visibly dazed.\n\nOn subsequent turns, you can use your action to maintain this effect, extending its duration until the end of your next turn. However, the effect ends if you move more than 5 feet away from the creature, if the creature can neither see nor hear you, or if the creature takes damage.\n\nOnce the effect ends, or if the creature succeeds on its initial saving throw against this effect, you can\'t use this feature on that creature again until you finish a long rest.',
              'Начиная со 2-го уровня, ваши тихие слова и завораживающий взгляд волшебным образом могут одурманить другое существо. Выберите действием одно видимое вами существо в пределах 5 футов от себя. Если цель может видеть или слышать вас, она должна преуспеть в спасброске Мудрости против Сл вашего заклинания волшебника, иначе она будет очарована вами до конца вашего следующего хода. Скорость очарованного существа падает до 0, оно недееспособно и выглядит потрясённым.\n\nВ следующие ходы вы можете действием поддерживать этот эффект, продлевая его до конца своего следующего хода. Однако эффект прекращается, если вы удалитесь от существа более чем на 5 футов, если существо не может больше ни видеть, ни слышать вас, или если существо получает урон.\n\nПосле окончания эффекта, или если существо успешно совершило спасбросок от него, вы не можете использовать данное умение против этого существа, пока не закончите продолжительный отдых.',
              2,
              'Action: Charm creature within 5 ft (Wis save). Speed 0, Incapacitated. Maintain as Action.',
              'Действие: Очаровать существо в 5 фт (спас Муд). Скор. 0, Недееспособно. Поддержание Действием.'
            ),
            f('instinctive_charm',
              'Instinctive Charm',
              'Инстинктивное очарование',
              'Beginning at 6th level, when a creature you can see within 30 feet of you makes an attack roll against you, you can use your reaction to divert the attack, provided that another creature is within the attack\'s range. The attacker must make a Wisdom saving throw against your wizard spell save DC. On a failed save, the attacker must target the creature that is closest to it, not including you or itself. If multiple creatures are closest, the attacker chooses which one to target. On a successful save, you can\'t use this feature on the attacker again until you finish a long rest.\n\nYou must choose to use this feature before knowing whether the attack hits or misses. Creatures that can\'t be charmed are immune to this effect.',
              'Начиная с 6-го уровня, когда существо, которое вы видите, и которое находится в пределах 30 футов от вас, совершает бросок атаки по вам, вы можете реакцией перенаправить атаку, при условии, что есть другое существо, находящееся в пределах досягаемости этой атаки. Атакующий должен совершить спасбросок Мудрости против Сл вашего заклинания волшебника. При провале атакующий должен выбрать в качестве цели ближайшее существо (кроме вас и себя). Если есть несколько потенциальных целей, атакующий сам выбирает из них цель. При успехе вы не можете использовать данное умение против атакующего, пока не закончите продолжительный отдых.\n\nВы обязаны решить, будете ли использовать это умение, до того как будет известно, попала атака или промахнулась. Существа, которых нельзя очаровать, обладают иммунитетом к этому эффекту.',
              6,
              'Reaction: Divert attack to nearest creature (Wis save).',
              'Реакция: Перенаправить атаку на ближайшее существо (спас Муд).'
            ),
            f('split_enchantment',
              'Split Enchantment',
              'Усиленное очарование',
              'Starting at 10th level, when you cast an enchantment spell of 1st level or higher that targets only one creature, you can have it target a second creature.',
              'Начиная с 10-го уровня, при накладывании вами заклинания школы Очарования 1-го уровня или выше, которое нацеливается только на одно существо, вы можете сделать целью второе существо.',
              10,
              'Target two creatures with single-target Enchantment spells.',
              'Две цели для одиночных заклинаний Очарования.'
            ),
            f('alter_memories',
              'Alter Memories',
              'Ложные воспоминания',
              'At 14th level, you gain the ability to make a creature unaware of your magical influence on it. When you cast an enchantment spell to charm one or more creatures, you can alter one creature\'s understanding so that it remains unaware of being charmed.\n\nAdditionally, once before the spell expires, you can use your action to try to make the chosen creature forget some of the time it spent charmed. The creature must succeed on an Intelligence saving throw against your wizard spell save DC or lose memories of its time spent charmed for a number of hours equal to 1 + your Charisma modifier (minimum 1). You can make it forget less time, and the amount of time can\'t exceed the duration of your enchantment spell.',
              'На 14-м уровне вы получаете способность заставить существо забыть о магическом воздействии, которое вы на него оказали. При накладывании заклинания школы Очарования, которое очаровывает одно или несколько существ, вы можете изменить восприятие и воспоминания одного из них так, что оно забудет о том, что было очаровано.\n\nКроме того, перед тем как заклинание развеется, вы можете действием попытаться заставить выбранное существо забыть некоторые моменты его пребывания в очарованном состоянии. Существо должно преуспеть в спасброске Интеллекта против Сл вашего заклинания волшебника, иначе оно потеряет воспоминания за промежуток времени, измеряемый в часах и равный 1 + ваш модификатор Харизмы (минимум 1). Вы можете заставить существо забыть меньшее количество времени. Количество забытого времени не может превышать продолжительность самого заклинания.',
              14,
              'Charm targets don\'t know they were charmed. Action to erase memory (Int save).',
              'Очарованные не знают о чарах. Действие стереть память (спас Инт).'
            )
        ]),

        // 12. School of Transmutation (PHB)
        sc('transmutation', 'School of Transmutation', 'Школа Преобразования', [
            f('transmutation_savant', 
              'Transmutation Savant', 
              'Мастер Преобразования', 
              'Beginning when you select this school at 2nd level, the gold and time you must spend to copy a transmutation spell into your spellbook is halved.', 
              'Начиная со 2-го уровня, золото и время, которое вы тратите на копирование заклинания школы Преобразования в свою книгу заклинаний, уменьшаются вдвое.', 
              2),
            f('minor_alchemy', 
              'Minor Alchemy', 
              'Малая Алхимия', 
              'Starting at 2nd level when you select this school, you can temporarily alter the physical properties of one nonmagical object, changing it from one substance into another. You perform a special alchemical procedure on one object composed entirely of wood, stone (but not a gemstone), iron, copper, or silver, transforming it into a different one of those materials. For each 10 minutes you spend performing the procedure, you can transform up to 1 cubic foot of material. After 1 hour, or until you lose your concentration (as if you were concentrating on a spell), the material reverts to its original substance.', 
              'Начиная со 2-го уровня, вы можете временно изменять физические свойства одного немагического предмета, превращая структуру вещества из одной в другую. Вы совершаете специальную алхимическую процедуру на одном предмете, состоящем полностью из дерева, камня (но не драгоценного камня), железа, меди или серебра, превращая его в один из этих материалов. За каждые 10 минут вы можете преобразовать до 1 кубического фута материала. Через 1 час, или когда вы теряете концентрацию (как если бы вы концентрировались на заклинании), материал возвратится в своё первоначальное состояние.', 
              2,
              'Change wood/stone/iron/copper/silver to another material (Concentration, 1 hr).',
              'Превратить дерево/камень/железо/медь/серебро в другой материал (Конц., 1 час).'
            ),
            f('transmuters_stone', 
              'Transmuter\'s Stone', 
              'Камень Преобразования', 
              'Starting at 6th level, you can spend 8 hours creating a transmuter\'s stone that stores transmutation magic. You can benefit from the stone yourself or give it to another creature. A creature gains a benefit of your choice as long as the stone is in the creature\'s possession. When you create the stone, choose the benefit from the following options:\n• Darkvision out to a range of 60 feet\n• An increase to speed of 10 feet while the creature is unencumbered\n• Proficiency in Constitution saving throws\n• Resistance to acid, cold, fire, lightning, or thunder damage (your choice whenever you choose this benefit)\n\nEach time you cast a transmutation spell of 1st level or higher, you can change the effect of your stone if the stone is on your person. If you create a new transmuter\'s stone, the previous one ceases to function.', 
              'Начиная с 6-го уровня, вы можете потратить 8 часов для создания камня преобразования. Вы можете извлечь выгоду из камня самостоятельно, или передать его другому существу. Существо получает выгоду по вашему выбору до тех пор, пока камень находится в его распоряжении. Выберите преимущество при создании:\n• Тёмное зрение в пределах 60 футов\n• Увеличение скорости на 10 футов\n• Владение спасбросками Телосложения\n• Сопротивление звуку, кислоте, огню, холоду или электричеству (выберите при создании)\n\nКаждый раз, когда вы накладываете заклинание школы Преобразования 1-го уровня или выше, вы можете изменить эффект вашего камня, если он находится у вас. Если вы создаёте новый камень преобразования, предыдущий перестаёт работать.', 
              6,
              'Create stone granting Darkvision, Speed, Con Save, or Resistance. Change on cast.',
              'Создать камень: Темное зрение, Скорость, Спас Тел или Сопротивление. Смена при касте.'
            ),
            f('shapechanger_wizard', 
              'Shapechanger', 
              'Перевёртыш', 
              'At 10th level, you add the Polymorph spell to your spellbook, if it is not there already. You can cast Polymorph without expending a spell slot. When you do so, you can target only yourself and transform into a beast whose challenge rating is 1 or lower. Once you cast Polymorph in this way, you can\'t do so again until you finish a short or long rest, though you can still cast it normally using an available spell slot.', 
              'На 10-м уровне вы добавляете заклинание превращение [polymorph] в свою книгу заклинаний, если его еще нет там. Вы можете накладывать превращение, не тратя ячейку заклинаний. Когда вы так поступаете, вы можете выбрать в качестве цели только себя и превратиться можете в Зверя, ПО которого не больше 1. Наложив превращение подобным путём один раз, вы не можете делать это еще раз до завершения короткого или продолжительного отдыха.', 
              10,
              'Cast Polymorph on self (CR 1 Beast) without slot (1/rest).',
              'Превращение на себя (ПО 1 Зверь) без ячейки (1/отдых).'
            ),
            f('master_transmuter', 
              'Master Transmuter', 
              'Гений Преобразования', 
              'Starting at 14th level, you can use your action to consume the reserve of transmutation magic stored within your transmuter\'s stone in a single burst. When you do so, choose one of the following effects. Your transmuter\'s stone is destroyed and can\'t be remade until you finish a long rest.\n\n**Major Transformation.** You can transmute one nonmagical object (max 5ft cube) into another nonmagical object of similar size and mass and equal or lesser value.\n\n**Panacea.** You remove all curses, diseases, and poisons affecting a creature that you touch with the transmuter\'s stone. The creature also regains all its hit points.\n\n**Restore Life.** You cast the Raise Dead spell on a creature you touch with the transmuter\'s stone, without expending a spell slot or needing to have the spell in your spellbook.\n\n**Restore Youth.** You touch the transmuter\'s stone to a willing creature, and that creature\'s apparent age is reduced by 3d10 years, to a minimum of 13 years.', 
              'На 14-м уровне вы можете действием потребить запас магии вашего камня преобразования. Выберите один эффект. Ваш камень уничтожается и не может быть создан снова до конца долгого отдыха.\n\n**Большая трансформация.** Преобразовать немагический предмет (макс 5фт куб) в другой схожего размера/массы и стоимости.\n\n**Панацея.** Снять все проклятия, болезни, яды и полностью исцелить существо касанием.\n\n**Возвращение к жизни.** Наложить Оживление [raise dead] на существо без траты ячейки/подготовки.\n\n**Вернуть молодость.** Уменьшить видимый возраст согласного существа на 3к10 лет (минимум до 13).', 
              14,
              'Destroy stone for: Transform object, Panacea (Full Heal/Cure), Raise Dead, or Restore Youth.',
              'Уничтожить камень ради: Трансформации предмета, Панацеи (Полное леч), Оживления или Молодости.'
            )
        ])
    ]
};
